//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSImmutableModelBase.h"

@class MSImmutableArray;

@interface _MSImmutableRulerData : MSImmutableModelBase
{
    long long _base;
    MSImmutableArray *_guides;
}


@property(nonatomic) long long base; // @synthesize base=_base;
- (void)decodePropertiesWithCoder:(id)arg1;
- (void)encodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) MSImmutableArray *guides; // @synthesize guides=_guides;
- (BOOL)hasDefaultValues;
- (id)initWithMutableModelObject:(id)arg1;

@end

