//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSStylePart.h"

@interface _MSStyleReflection : MSStylePart
{
    double _distance;
    double _strength;
}

- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
@property(nonatomic) double distance; // @synthesize distance=_distance;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (void)fillInEmptyObjects;
- (BOOL)hasDefaultValues;
- (id)immutableModelObject;
- (void)initEmptyObject;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
- (double)primitiveDistance;
- (double)primitiveStrength;
- (void)setAsParentOnChildren;
- (void)setPrimitiveDistance:(double)arg1;
- (void)setPrimitiveStrength:(double)arg1;
@property(nonatomic) double strength; // @synthesize strength=_strength;

@end

