//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSBaseGrid.h"

@interface _MSSimpleGrid : MSBaseGrid
{
    long long _gridSize;
    long long _thickGridTimes;
}

- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (void)fillInEmptyObjects;
@property(nonatomic) long long gridSize; // @synthesize gridSize=_gridSize;
- (BOOL)hasDefaultValues;
- (id)immutableModelObject;
- (void)initEmptyObject;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
- (long long)primitiveGridSize;
- (long long)primitiveThickGridTimes;
- (void)setAsParentOnChildren;
- (void)setPrimitiveGridSize:(long long)arg1;
- (void)setPrimitiveThickGridTimes:(long long)arg1;
@property(nonatomic) long long thickGridTimes; // @synthesize thickGridTimes=_thickGridTimes;

@end

