//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSStylePart.h"

@class MSColor, MSGraphicsContextSettings;

@interface _MSStyleShadow : MSStylePart
{
    BOOL _hasShadow;
    double _blurRadius;
    double _offsetX;
    double _offsetY;
    double _spread;
    MSColor *_color;
    MSGraphicsContextSettings *_contextSettings;
}


@property(nonatomic) double blurRadius; // @synthesize blurRadius=_blurRadius;
@property(retain, nonatomic) MSColor *color; // @synthesize color=_color;
@property(retain, nonatomic) MSGraphicsContextSettings *contextSettings; // @synthesize contextSettings=_contextSettings;
- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (void)fillInEmptyObjects;
- (BOOL)hasDefaultValues;
@property(nonatomic) BOOL hasShadow; // @synthesize hasShadow=_hasShadow;
- (id)immutableModelObject;
- (void)initEmptyObject;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
@property(nonatomic) double offsetX; // @synthesize offsetX=_offsetX;
@property(nonatomic) double offsetY; // @synthesize offsetY=_offsetY;
- (double)primitiveBlurRadius;
- (id)primitiveColor;
- (id)primitiveContextSettings;
- (BOOL)primitiveHasShadow;
- (double)primitiveOffsetX;
- (double)primitiveOffsetY;
- (double)primitiveSpread;
- (void)setAsParentOnChildren;
- (void)setPrimitiveBlurRadius:(double)arg1;
- (void)setPrimitiveColor:(id)arg1;
- (void)setPrimitiveContextSettings:(id)arg1;
- (void)setPrimitiveHasShadow:(BOOL)arg1;
- (void)setPrimitiveOffsetX:(double)arg1;
- (void)setPrimitiveOffsetY:(double)arg1;
- (void)setPrimitiveSpread:(double)arg1;
@property(nonatomic) double spread; // @synthesize spread=_spread;

@end

