//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SVGBasicShape.h"

@interface _SVGEllipseShape : SVGBasicShape
{
    double _cx;
    double _cy;
    double _rx;
    double _ry;
}

+ (id)attributeNames;
+ (id)propertyNames;
+ (id)relationshipNames;
@property(nonatomic) double cx; // @synthesize cx=_cx;
@property(nonatomic) double cy; // @synthesize cy=_cy;
@property(nonatomic) double rx; // @synthesize rx=_rx;
@property(nonatomic) double ry; // @synthesize ry=_ry;

@end

