//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPResponseSerializer.h"

@interface AFPropertyListResponseSerializer : AFHTTPResponseSerializer
{
    unsigned long long _format;
    unsigned long long _readOptions;
}

+ (id)serializer;
+ (id)serializerWithFormat:(unsigned long long)arg1 readOptions:(unsigned long long)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(nonatomic) unsigned long long format; // @synthesize format=_format;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) unsigned long long readOptions; // @synthesize readOptions=_readOptions;
- (id)responseObjectForResponse:(id)arg1 data:(id)arg2 error:(id *)arg3;

@end

