//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BCLicense, NSString, NSURL, NSURLSession;

@interface BCLicenseManager : NSObject
{
    BOOL _completedLoadingLicense;
    BCLicense *_license;
    NSString *_applicationID;
    NSString *_publicCertificate;
    NSURL *_licenseURL;
    NSURLSession *_urlSession;
}


@property(retain, nonatomic) NSString *applicationID; // @synthesize applicationID=_applicationID;
- (void)checkForDeploymentKeyWithPath:(id)arg1 removeFile:(BOOL)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)completeUpdateWithHandler:(CDUnknownBlockType)arg1 status:(long long)arg2 info:(id)arg3 error:(id)arg4;
@property(nonatomic) BOOL completedLoadingLicense; // @synthesize completedLoadingLicense=_completedLoadingLicense;
- (long long)currentLicenseType;
- (void)fallbackToTrial:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)initWithApplicationID:(id)arg1 publicCertificate:(id)arg2 licenseURL:(id)arg3;
@property(retain, nonatomic) BCLicense *license; // @synthesize license=_license;
- (void)licenseStateChanged;
@property(retain, nonatomic) NSURL *licenseURL; // @synthesize licenseURL=_licenseURL;
- (long long)numberOfDaysLeftInTrialMode;
- (void)processDataOfRegistration:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)processLicenseRefreshResult:(id)arg1 error:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)processURL:(id)arg1 handler:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) NSString *publicCertificate; // @synthesize publicCertificate=_publicCertificate;
- (void)registerWithLicenseKey:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)requestTrialLicenseWithHandler:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSURLSession *urlSession; // @synthesize urlSession=_urlSession;
- (void)tryToRefreshLicense:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)updateLicenseWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)validateLicenseWithCompletionHandler:(CDUnknownBlockType)arg1;

@end

