//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSWindowDelegate.h"

@class BCPopoverWindow, NSString, NSView, NSViewController<BCPopoverContentController>;

@interface BCPopover : NSObject <NSWindowDelegate>
{
    BOOL dontSendNextPopoverWindowSizeNotification;
    NSViewController<BCPopoverContentController> *_contentViewController;
    id <BCPopoverDelegate> _delegate;
    BCPopoverWindow *_window;
    NSView *_attachedToView;
    long long _screenEdgeBehaviour;
    long long _layerDependency;
    unsigned long long _preferredEdge;
}


- (struct CGPoint)attachToPointInScreenCoordinates;
@property(retain, nonatomic) NSView *attachedToView; // @synthesize attachedToView=_attachedToView;
- (void)attachedViewDidMove:(id)arg1;
- (void)attachedWindowDidMove:(id)arg1;
- (void)close;
- (void)configureNotifications:(id)arg1;
@property(retain, nonatomic) NSViewController<BCPopoverContentController> *contentViewController; // @synthesize contentViewController=_contentViewController;
- (void)contentViewDidResizeNotification:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <BCPopoverDelegate> delegate; // @synthesize delegate=_delegate;
- (struct CGRect)ensureRectFitsInParentWindow:(struct CGRect)arg1;
- (id)init;
@property(nonatomic) long long layerDependency; // @synthesize layerDependency=_layerDependency;
- (void)move;
- (void)otherPopoverDidShow:(id)arg1;
- (struct CGPoint)pointAtEdge:(unsigned long long)arg1 ofRect:(struct CGRect)arg2;
- (double)popoverArrowPosition;
- (struct CGRect)popoverWindowFrame;
@property(nonatomic) unsigned long long preferredEdge; // @synthesize preferredEdge=_preferredEdge;
- (struct CGRect)screenAnchorRect;
@property(nonatomic) long long screenEdgeBehaviour; // @synthesize screenEdgeBehaviour=_screenEdgeBehaviour;
- (struct CGRect)screenFrame;
@property(retain, nonatomic) BCPopoverWindow *window; // @synthesize window=_window;
- (void)showRelativeToView:(id)arg1 preferredEdge:(unsigned long long)arg2;
- (struct CGRect)windowRectForViewSize:(struct CGSize)arg1 above:(struct CGRect)arg2 pointingTo:(struct CGPoint)arg3 edge:(unsigned long long)arg4;
- (void)windowWillClose:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

