//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSColor;

@interface BCPopoverContentView : NSView
{
    NSColor *_backgroundColor;
    unsigned long long _arrowEdge;
    double _arrowPosition;
}


@property(nonatomic) unsigned long long arrowEdge; // @synthesize arrowEdge=_arrowEdge;
@property(nonatomic) double arrowPosition; // @synthesize arrowPosition=_arrowPosition;
- (struct CGRect)availableContentRect;
@property(copy, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (id)backgroundPath;
- (BOOL)canBecomeKeyView;
- (void)cancelOperation:(id)arg1;
- (void)doCommandBySelector:(SEL)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)keyDown:(id)arg1;

@end

