//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSBezierPath;

@interface MSBooleanOperationChainStep : NSObject
{
    NSBezierPath *_bezierPath;
    long long _operation;
}

+ (id)booleanOperationChainStepWithPath:(id)arg1 operation:(long long)arg2;

@property(retain, nonatomic) NSBezierPath *bezierPath; // @synthesize bezierPath=_bezierPath;
@property(nonatomic) long long operation; // @synthesize operation=_operation;

@end

