//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSColor.h"

#import "MSAsset.h"

@class NSString;

@interface MSColor : _MSColor <MSAsset>
{
}

+ (id)availableRGBColorSpaces;
+ (id)blackColor;
+ (id)colorFromSVGColor:(id)arg1;
+ (id)colorWithHue:(double)arg1 saturation:(double)arg2 brightness:(double)arg3 alpha:(double)arg4;
+ (id)colorWithNSColor:(id)arg1;
+ (id)colorWithRGBADictionary:(id)arg1;
+ (id)colorWithRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
+ (id)colorWithSVGString:(id)arg1;
+ (id)exportingColorSpace;
+ (void)getRed:(double *)arg1 green:(double *)arg2 blue:(double *)arg3 fromHexValue:(id)arg4;
+ (id)hexValueForRed:(double)arg1 green:(double)arg2 blue:(double)arg3;
+ (id)safeNSColor:(id)arg1;
+ (id)screenColorSpace;
+ (void)setForcedColorSpace:(id)arg1;
+ (id)whiteColor;
- (id)HSBColor;
- (id)NSColorForContext:(id)arg1;
- (id)NSColorWithColorSpace:(id)arg1;
- (id)RGBADictionary;
- (unsigned long long)assetType;
@property(readonly, nonatomic) double brightness;
- (id)colorWithAlpha:(double)arg1;
@property(readonly, copy) NSString *description;
- (BOOL)fuzzyIsEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)hexValue;
@property(readonly, nonatomic) double hue;
- (id)initWithRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
- (BOOL)isAssetEqual:(id)arg1;
- (BOOL)isBlack;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isWhite;
- (id)replacementObjectForCoder:(id)arg1;
@property(readonly, nonatomic) double saturation;
- (id)scaledColor:(double)arg1;
- (id)stringValueWithAlpha:(BOOL)arg1;
- (id)stringValueWithAlpha:(BOOL)arg1 alphaMultiplication:(double)arg2;
- (id)svgRepresentation;
- (id)treeAsDictionary;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

