//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSSnapItem.h"

@class NSArray;

@interface MSCompoundSnapItem : MSSnapItem
{
    NSArray *_layers;
    NSArray *_relativeRects;
    struct CGRect _unionRect;
}


- (struct CGRect)boundsRect;
- (void)concatAncestorTransforms;
- (id)initWithLayers:(id)arg1;
- (id)layer;
@property(retain, nonatomic) NSArray *layers; // @synthesize layers=_layers;
- (struct CGRect)originalRect;
- (id)otherLayersForSnapping;
- (struct CGRect)rect;
@property(retain, nonatomic) NSArray *relativeRects; // @synthesize relativeRects=_relativeRects;
- (double)rotation;
- (void)setRect:(struct CGRect)arg1;
@property(nonatomic) struct CGRect unionRect; // @synthesize unionRect=_unionRect;
- (BOOL)shouldConstrainProportions;
- (id)snapLines;

@end

