//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSBaseAction.h"

@interface MSDistributeAction : MSBaseAction
{
}

- (long long)calculateRequiredSpaceBetweenLayers:(id)arg1 forAxis:(unsigned long long)arg2;
- (void)clearCachesIfNecessary:(id)arg1;
- (void)distributeAlongAxis:(unsigned long long)arg1;
- (void)distributeLayers:(id)arg1 withSpace:(long long)arg2 forAxis:(unsigned long long)arg3;
- (id)layersSortedForAxis:(unsigned long long)arg1;
- (BOOL)validate;

@end

