//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CHViewController.h"

#import "NSMenuDelegate.h"

@class MSSharedObject, NSArray, NSButton, NSImage, NSPopUpButton, NSString, NSTextField;

@interface MSElementsInspectorSection : CHViewController <NSMenuDelegate>
{
    NSArray *_layers;
    NSButton *_layerStyleToggle;
    NSButton *_textStyleToggle;
    NSPopUpButton *_sharedObjectsPopUpButton;
    NSTextField *_editNameField;
    NSImage *_initialImage;
    MSSharedObject *_renamingObject;
    CDUnknownBlockType _renameBlock;
}


- (void)applySharedObject:(id)arg1 toLayer:(id)arg2;
- (void)applySharedObjectToSelection:(id)arg1;
- (void)awakeFromNib;
- (void)beginRenameSharedObject:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)createNewSharedObject:(id)arg1;
- (id)currentSharedObject;
- (void)dealloc;
- (id)displayNameForType:(unsigned long long)arg1;
- (id)document;
- (void)duplicateSymbolAction:(id)arg1;
@property(retain, nonatomic) NSTextField *editNameField; // @synthesize editNameField=_editNameField;
- (struct MSModelObject *)firstSharedObjectFromLayers:(unsigned long long)arg1;
- (void)generatePreviewForMenuItem:(id)arg1;
- (BOOL)hasGroupLayers;
- (BOOL)hasOnlyTextLayers;
@property(retain, nonatomic) NSImage *initialImage; // @synthesize initialImage=_initialImage;
- (void)isolateSelectedObject:(id)arg1;
- (BOOL)layer:(id)arg1 conformsToType:(unsigned long long)arg2;
@property(retain, nonatomic) NSButton *layerStyleToggle; // @synthesize layerStyleToggle=_layerStyleToggle;
@property(copy, nonatomic) NSArray *layers; // @synthesize layers=_layers;
- (void)prepareForDisplay;
- (void)reloadData;
- (void)reloadMenu;
@property(copy, nonatomic) CDUnknownBlockType renameBlock; // @synthesize renameBlock=_renameBlock;
- (void)renameSharedObject:(id)arg1;
- (void)renameSharedObjectAction:(id)arg1;
@property(retain, nonatomic) MSSharedObject *renamingObject; // @synthesize renamingObject=_renamingObject;
- (unsigned long long)selectedMenuIndexForType:(unsigned long long)arg1;
@property(retain, nonatomic) NSPopUpButton *sharedObjectsPopUpButton; // @synthesize sharedObjectsPopUpButton=_sharedObjectsPopUpButton;
@property(retain, nonatomic) NSButton *textStyleToggle; // @synthesize textStyleToggle=_textStyleToggle;
- (id)sharedObjectContainerOfType:(unsigned long long)arg1;
- (struct MSModelObject *)sharedObjectOfType:(unsigned long long)arg1 fromLayer:(id)arg2;
- (unsigned long long)sharedObjectType;
- (void)showManageSymbolsSheet:(id)arg1;
- (BOOL)symbolInstances:(id)arg1 couldSwitchToSymbol:(id)arg2;
- (void)updateMenuSelectionToIndex:(unsigned long long)arg1;
- (BOOL)validateMenuItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

