//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSPage, NSMutableDictionary, NSString, NSURL;

@interface MSFramerExporter : NSObject
{
    MSPage *_page;
    NSString *_documentName;
    NSURL *_documentURL;
    NSMutableDictionary *_exportRequestsForLayer;
}


- (struct CGPoint)absoluteOriginForRect:(struct CGRect)arg1 ofLayer:(id)arg2;
- (id)calculateExportRequestForLayer:(id)arg1;
- (id)checkForErrors;
- (id)cleanFilenameFor:(id)arg1;
- (id)coordinatesFor:(id)arg1;
- (id)coordinatesForMask:(id)arg1;
- (id)disableMasksForView:(id)arg1;
- (id)disableShadowsForParentsOfView:(id)arg1;
@property(copy, nonatomic) NSString *documentName; // @synthesize documentName=_documentName;
@property(copy, nonatomic) NSURL *documentURL; // @synthesize documentURL=_documentURL;
- (void)enableLayerMasks:(id)arg1;
- (id)export;
- (id)exportAllowingUI:(BOOL)arg1;
- (void)exportAssetsForView:(id)arg1 inFolder:(id)arg2;
- (void)exportImagesToFolder:(id)arg1 views:(id)arg2;
- (void)exportJSONToFolder:(id)arg1 views:(id)arg2;
- (id)exportRequestForLayer:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *exportRequestsForLayer; // @synthesize exportRequestsForLayer=_exportRequestsForLayer;
- (id)exportSubviewsOfLayer:(id)arg1 exportPath:(id)arg2;
- (void)exportView:(id)arg1 withRequest:(id)arg2 toPath:(id)arg3;
- (id)exportableLayers;
- (id)extractMetadataFrom:(id)arg1;
- (id)firstMaskForLayer:(id)arg1;
- (id)hideSubviewsOfLayer:(id)arg1 exportPath:(id)arg2;
- (id)imageMetadataForLayer:(id)arg1;
- (BOOL)layerGroupHasVisibleContents:(id)arg1;
- (id)maskBoundsFor:(id)arg1;
- (id)metadataForRect:(struct CGRect)arg1;
- (id)metadataFromViews:(id)arg1;
@property(retain, nonatomic) MSPage *page; // @synthesize page=_page;
- (struct CGRect)rectWithStyleSizeForLayer:(id)arg1;
- (void)saveStructureToJSON:(id)arg1 toPath:(id)arg2;
- (void)saveStructureToJSONJS:(id)arg1 toPath:(id)arg2;
- (id)subviewsForView:(id)arg1;
- (id)temporaryFolder;
- (BOOL)viewCanHaveMask:(id)arg1;
- (BOOL)viewHasSubviews:(id)arg1;
- (BOOL)viewIsArtboard:(id)arg1;
- (BOOL)viewShouldBeExtracted:(id)arg1;
- (BOOL)viewShouldBeTraversed:(id)arg1;
- (id)viewsFromLayers:(id)arg1;

@end

