//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSImmutablePage.h"

@class NSArray;

@interface MSImmutablePage : _MSImmutablePage
{
    BOOL _hasBlendedLayer;
    NSArray *_cachedArtboards;
}


@property(retain, nonatomic) NSArray *cachedArtboards; // @synthesize cachedArtboards=_cachedArtboards;
@property(nonatomic) BOOL hasBlendedLayer; // @synthesize hasBlendedLayer=_hasBlendedLayer;
- (id)initWithMutableModelObject:(id)arg1;

@end

