//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MSInspectorNextResponderFixer : NSObject
{
}

+ (long long)compareHorizontalPositionOfView:(id)arg1 withView:(id)arg2;
+ (long long)compareVerticalPositionOfView:(id)arg1 withView:(id)arg2;
+ (id)findNextKeyViewFor:(id)arg1 inView:(id)arg2;
+ (id)firstKeyViewForInView:(id)arg1;
+ (id)orderedSubviewsOfView:(id)arg1;
+ (id)subviewsOfView:(id)arg1;
+ (struct _NSRange)verticalRangeFromView:(id)arg1 inView:(id)arg2;
+ (BOOL)viewCanBeNextKeyView:(id)arg1;
+ (BOOL)viewIntersectsVertically:(id)arg1 withView:(id)arg2;

@end

