//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSSidebarListController.h"

#import "BCOutlineViewDataSource.h"
#import "BCOutlineViewDelegate.h"

@class NSArray, NSString;

@interface MSLayerListController : MSSidebarListController <BCOutlineViewDataSource, BCOutlineViewDelegate>
{
}

- (void)changeSelectionTo:(id)arg1;
- (id)childrenOfNode:(id)arg1;
- (void)handleBadgePressedOnNode:(id)arg1 withAltState:(BOOL)arg2;
- (void)hoverNodeDidChangeTo:(id)arg1;
- (BOOL)isNodeExpandable:(id)arg1;
- (BOOL)isNodeExpanded:(id)arg1;
- (BOOL)isNodeSelected:(id)arg1;
- (id)layerForNode:(id)arg1;
- (long long)mapExpandedStateToLayerListStatus:(unsigned long long)arg1;
- (id)menuItemsForSelectedObjects:(id)arg1;
- (void)removeNodes:(id)arg1;
- (id)rootObject;
- (void)updateNode:(id)arg1 expandedState:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSArray *dragTypes;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

