//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray;

@protocol MSLayerManipulation
- (void)addLayers:(NSArray *)arg1;
- (void)insertLayers:(NSArray *)arg1 afterLayer:(id)arg2;
- (void)insertLayers:(NSArray *)arg1 atIndex:(unsigned long long)arg2;
- (void)insertLayers:(NSArray *)arg1 beforeLayer:(id)arg2;
- (void)removeAllLayers;
- (void)removeLayer:(id)arg1;
- (void)removeLayerAtIndex:(unsigned long long)arg1;
- (void)replaceLayersWithLayers:(NSArray *)arg1;
@end

