//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MSModelObjectInstanceInfo : NSObject
{
    unsigned long long _current;
    unsigned long long _total;
}

@property(nonatomic) unsigned long long current; // @synthesize current=_current;
- (id)description;
@property(nonatomic) unsigned long long total; // @synthesize total=_total;

@end

