//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class MSPDFState, NSAffineTransform, NSDictionary, NSFont, NSMutableAttributedString, NSString;

@interface MSPDFTextState : NSObject <NSCopying>
{
    double _characterSpacing;
    NSFont *_font;
    NSString *_fontName;
    NSDictionary *_fontInfo;
    double _leading;
    NSAffineTransform *_lineTransform;
    unsigned long long _mode;
    double _offset;
    NSAffineTransform *_renderingTransform;
    double _rise;
    double _scale;
    double _size;
    MSPDFState *_state;
    NSMutableAttributedString *_text;
    NSAffineTransform *_transform;
    double _wordSpacing;
}

+ (id)textStateWithState:(id)arg1;

- (void)appendText:(id)arg1;
- (id)attributes;
@property(nonatomic) double characterSpacing; // @synthesize characterSpacing=_characterSpacing;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSFont *font; // @synthesize font=_font;
@property(retain, nonatomic) NSDictionary *fontInfo; // @synthesize fontInfo=_fontInfo;
@property(retain, nonatomic) NSString *fontName; // @synthesize fontName=_fontName;
- (id)init;
@property(nonatomic) double leading; // @synthesize leading=_leading;
@property(retain, nonatomic) NSAffineTransform *lineTransform; // @synthesize lineTransform=_lineTransform;
@property(nonatomic) unsigned long long mode; // @synthesize mode=_mode;
@property(nonatomic) double offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSAffineTransform *renderingTransform; // @synthesize renderingTransform=_renderingTransform;
- (void)resetRenderingTransform;
@property(nonatomic) double rise; // @synthesize rise=_rise;
@property(nonatomic) double scale; // @synthesize scale=_scale;
@property(nonatomic) double size; // @synthesize size=_size;
@property(nonatomic) __weak MSPDFState *state; // @synthesize state=_state;
@property(retain, nonatomic) NSMutableAttributedString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSAffineTransform *transform; // @synthesize transform=_transform;
- (void)setTransform:(id)arg1 resettingLineTransform:(BOOL)arg2;
@property(nonatomic) double wordSpacing; // @synthesize wordSpacing=_wordSpacing;
- (BOOL)shouldClip;
- (BOOL)shouldFill;
- (BOOL)shouldStroke;

@end

