//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSEventHandler.h"

@class MSLayerGroup, MSShapePathLayer;

@interface MSPencilEventHandler : MSEventHandler
{
    BOOL isDragging;
    struct CGPoint lastMouse;
    MSShapePathLayer *_shape;
    MSLayerGroup *_currentGroup;
}


- (void)addCurvePoint:(id)arg1;
- (void)addPoint:(struct CGPoint)arg1;
- (struct CGPoint)adjustPoint:(struct CGPoint)arg1 toLayer:(id)arg2;
- (void)adjustStyleForGroup:(id)arg1;
@property(retain, nonatomic) MSLayerGroup *currentGroup; // @synthesize currentGroup=_currentGroup;
- (void)finishShapeOrRemoveIfEmpty;
- (id)fittedBezierPathFromShapePath:(id)arg1;
- (void)handlerGotFocus;
- (void)handlerWillLoseFocus;
- (void)insertNewShapeForEditingAtPoint:(struct CGPoint)arg1;
- (BOOL)mouseDown:(struct CGPoint)arg1 clickCount:(unsigned long long)arg2 flags:(unsigned long long)arg3;
- (BOOL)mouseDownEvent:(id)arg1;
- (BOOL)mouseDragged:(struct CGPoint)arg1 flags:(unsigned long long)arg2;
- (BOOL)mouseDraggedOutsideViewShouldMoveScrollOrigin;
- (BOOL)mouseMoved:(struct CGPoint)arg1 flags:(unsigned long long)arg2;
- (BOOL)mouseUp:(struct CGPoint)arg1 flags:(unsigned long long)arg2;
- (BOOL)pathShouldClose;
- (void)removeRedundantPoints:(id)arg1;
- (void)removeShape;
- (void)selectShape;
@property(retain, nonatomic) MSShapePathLayer *shape; // @synthesize shape=_shape;
- (BOOL)shouldDrawLayerSelection;
- (id)toolbarIdentifier;
- (void)unflattenResult;

@end

