//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CODebugController.h"

@interface MSPluginDebugController : NSObject <CODebugController>
{
}

- (void)output:(id)arg1 args:(struct __va_list_tag [1])arg2;

@end

