//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSAssetPickerView, NSString;

@protocol MSPresetPickerViewDelegate <NSObject>
- (void)addPresetForPickerView:(MSAssetPickerView *)arg1;
- (unsigned long long)numberOfPresetsInPickerView:(MSAssetPickerView *)arg1;
- (void)pickerView:(MSAssetPickerView *)arg1 didPickPresetAtIndex:(unsigned long long)arg2;
- (void)pickerView:(MSAssetPickerView *)arg1 removePresetAtIndex:(unsigned long long)arg2;

@optional
- (void)drawContentForCellInPickerView:(MSAssetPickerView *)arg1 atIndex:(unsigned long long)arg2 inRect:(struct CGRect)arg3;
- (void)drawFullContentForCellInPickerView:(MSAssetPickerView *)arg1 atIndex:(unsigned long long)arg2 inRect:(struct CGRect)arg3;
- (BOOL)pickerView:(MSAssetPickerView *)arg1 didDragPresetAtIndex:(unsigned long long)arg2 toIndex:(unsigned long long)arg3;
- (void)pickerView:(MSAssetPickerView *)arg1 didHoverPresetAtIndex:(long long)arg2;
- (void)pickerView:(MSAssetPickerView *)arg1 didStopHoverPresetAtIndex:(long long)arg2;
- (id)pickerView:(id)arg1 dragRepresentationForItemAtIndex:(unsigned long long)arg2;
- (BOOL)pickerView:(MSAssetPickerView *)arg1 insertPresetFromDragRepresentation:(id)arg2 atIndex:(unsigned long long)arg3;
- (BOOL)pickerView:(MSAssetPickerView *)arg1 shouldShowMenuForItemAtIndex:(unsigned long long)arg2;
- (NSString *)pickerView:(MSAssetPickerView *)arg1 tooltipForPresetButtonAtIndex:(unsigned long long)arg2;
- (BOOL)pickerViewSupportsDrag:(MSAssetPickerView *)arg1 fromIndex:(unsigned long long)arg2;
- (BOOL)pickerViewSupportsDrop:(MSAssetPickerView *)arg1;
- (void)presetPickerFinishedDragging:(MSAssetPickerView *)arg1;
- (BOOL)shouldShowAddPresetButton:(MSAssetPickerView *)arg1;
@end

