//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSEventHandlerAction.h"

@interface MSRotateAction : MSEventHandlerAction
{
}

- (void)doPerformAction:(id)arg1;
- (void)rotate90C:(id)arg1;
- (void)rotate90CC:(id)arg1;
- (void)rotate:(id)arg1;
- (BOOL)validate;

@end

