//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CHSheetController.h"

@class NSButton, NSPopUpButton, NSTextField, NSTextView;

@interface MSRunCustomScriptSheet : CHSheetController
{
    NSTextView *inputField;
    NSButton *saveButton;
    NSTextField *scriptNameField;
    NSButton *runButton;
    NSPopUpButton *actionButton;
    NSTextView *_logField;
}


- (void)awakeFromNib;
@property(retain, nonatomic) NSTextView *logField; // @synthesize logField=_logField;
- (void)runScript:(id)arg1;
- (void)saveAction:(id)arg1;
- (void)showHelp:(id)arg1;

@end

