//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDocument.h"

@interface MSScriptDocument : NSDocument
{
}

- (void)copyPluginBundle:(id)arg1 toPluginsFolderURL:(id)arg2;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (void)removeExistingPlugin:(id)arg1;
- (BOOL)showBundleAlreadyInstalledAlert:(id)arg1 existingPlugin:(id)arg2;
- (BOOL)showBundleUpgradeAlert:(id)arg1 existingPlugin:(id)arg2;
- (id)titleFromPlugin:(id)arg1;

@end

