//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSEventHandler.h"

@class NSArray;

@interface MSSmartRotateEventHandler : MSEventHandler
{
    struct CGPoint rotationCenter;
    BOOL hasRotationCenterSelected;
    unsigned long long _numberOfRepetitions;
    NSArray *_shapeLayers;
    NSArray *_shapeLayersCopies;
}


- (BOOL)absoluteMouseDown:(struct CGPoint)arg1 clickCount:(unsigned long long)arg2 flags:(unsigned long long)arg3;
- (BOOL)absoluteMouseDragged:(struct CGPoint)arg1 flags:(unsigned long long)arg2;
- (BOOL)absoluteMouseUp:(struct CGPoint)arg1 flags:(unsigned long long)arg2;
- (void)adjustBooleanOperationForShapeCopyIfNecessary:(id)arg1;
- (void)adjustFrameForShapeCopy:(id)arg1 shape:(id)arg2 index:(unsigned long long)arg3;
- (void)adjustGroup;
- (void)adjustRotationForShapeCopy:(id)arg1 atIndex:(unsigned long long)arg2 baseRotation:(double)arg3;
- (void)createShapeCopies;
- (id)currentGroup;
- (void)dealloc;
- (void)determineOriginalRotationCenter;
- (void)drawControlPoints;
- (void)drawInRect:(struct CGRect)arg1;
- (void)findShapes;
- (void)handlerGotFocus;
- (void)handlerWillLoseFocus;
- (id)imageName;
@property(nonatomic) unsigned long long numberOfRepetitions; // @synthesize numberOfRepetitions=_numberOfRepetitions;
- (void)registerUndoObserver;
- (void)rotateCopies;
- (void)rotateCopiesForShape:(id)arg1 shapeIndex:(unsigned long long)arg2;
- (void)rotateCopy:(id)arg1 ofShape:(id)arg2 toIndex:(unsigned long long)arg3;
- (double)rotationForRepetitionAtIndex:(unsigned long long)arg1;
@property(copy, nonatomic) NSArray *shapeLayers; // @synthesize shapeLayers=_shapeLayers;
@property(copy, nonatomic) NSArray *shapeLayersCopies; // @synthesize shapeLayersCopies=_shapeLayersCopies;
- (BOOL)shouldDrawLayerSelection;
- (id)toolbarIdentifier;
- (id)transformForRotatingShape:(id)arg1 toIndex:(unsigned long long)arg2;
- (struct CGPoint)tryToSnapPoint:(struct CGPoint)arg1 toMid:(struct CGPoint)arg2;
- (void)unregisterUndoObserver;
- (void)willUndo:(id)arg1;

@end

