//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSEventHandlerAction.h"

@interface MSStrokeWidthAction : MSEventHandlerAction
{
}

- (BOOL)showInToolbar;
- (void)strokeWidth:(id)arg1;
- (id)tooltip;
- (BOOL)validate;

@end

