//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextField.h"

@class NSArray, NSTextField<MSUpDownProtocol>;

@interface MSTextLabelForUpDownField : NSTextField
{
    NSTextField<MSUpDownProtocol> *_upDownTextField;
    NSArray *_textFields;
}


- (id)advancedUndoManager;
- (void)awakeFromNib;
- (BOOL)canScrub;
- (BOOL)clickShouldDismissPopover:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
@property(copy, nonatomic) NSArray *textFields; // @synthesize textFields=_textFields;
@property(nonatomic) __weak NSTextField<MSUpDownProtocol> *upDownTextField; // @synthesize upDownTextField=_upDownTextField;
- (id)textField;
- (BOOL)trackMouseDraggedInBlock:(CDUnknownBlockType)arg1;

@end

