//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MSTransparencyLayerSavedState : NSObject
{
    BOOL _shouldFlip;
    struct CGContext *_contextRef;
    struct CGRect _deviceRect;
}

@property(nonatomic) struct CGContext *contextRef; // @synthesize contextRef=_contextRef;
@property(nonatomic) struct CGRect deviceRect; // @synthesize deviceRect=_deviceRect;
@property(nonatomic) BOOL shouldFlip; // @synthesize shouldFlip=_shouldFlip;

@end

