//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSRulerViewLayer.h"

@interface MSVerticalRulerViewLayer : MSRulerViewLayer
{
}

- (void)drawInContext:(struct CGContext *)arg1;
- (void)drawMetric:(id)arg1 atPoint:(struct CGPoint)arg2 drawBackground:(BOOL)arg3;
- (id)init;
- (BOOL)isFlipped;

@end

