//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBezierPath.h"

@interface NSBezierPath (NSBezierPath_Slopes)
- (void)appendBezierPathByRemovingMoveToPoint:(id)arg1;
- (id)bezierPathByApplyingModifierBlock:(CDUnknownBlockType)arg1;
- (id)bezierPathByJoiningWithBezierPath:(id)arg1;
- (id)bezierPathByRearrangingSubPathsIfNecessary;
- (id)bezierPathByRemovingSubsequentMoveToComponents;
- (id)bezierPathByReplacingClosePathByLineToComponents;
- (id)bezierPathByReplacingElementAtIndexWithMoveTo:(long long)arg1;
- (id)bezierPathByReplacingMoveToByLineToComponents;
- (id)bezierPathBySmootheningSubPath:(double)arg1;
- (id)bezierPathByTranslatingXBy:(double)arg1 yBy:(double)arg2;
- (id)bezierPathByTrimmingFromLength:(double)arg1;
- (id)bezierPathByTrimmingFromLength:(double)arg1 withMaximumError:(double)arg2;
- (id)bezierPathByTrimmingToLength:(double)arg1;
- (id)bezierPathByTrimmingToLength:(double)arg1 withMaximumError:(double)arg2;
- (id)bezierPathFromIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2;
- (void)drawDebugWithZoom:(double)arg1;
- (id)expandPathBy:(double)arg1;
- (struct CGPoint)firstPoint;
- (BOOL)isEqualToBezierPath:(id)arg1;
- (struct CGPoint)lastPoint;
- (double)length;
- (double)lengthWithMaximumError:(double)arg1;
- (id)placeOnBezierPath:(id)arg1 atOffset:(long long)arg2;
- (struct CGPoint)pointAtIndex:(long long)arg1;
- (struct CGPoint)pointOnPathAtLength:(double)arg1;
- (struct CGPoint)pointOnPathAtLength:(double)arg1 slope:(double *)arg2;
- (double)slopeOfPointAtIndex:(long long)arg1;
- (double)slopeOnPathAtLength:(double)arg1;
- (id)subDivideAtPoint:(struct CGPoint)arg1;
@end

