//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableData.h"

@interface NSMutableData (append)
- (void)jr_appendFormat:(id)arg1;
- (void)jr_appendString:(id)arg1;
@end

