//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSXMLNode.h"

@interface NSXMLNode (SVG)
+ (id)attributeWithName:(id)arg1 numberValue:(double)arg2;
+ (id)attributeWithName:(id)arg1 percentageFractionalValue:(double)arg2;
+ (id)attributeWithName:(id)arg1 percentageValue:(double)arg2;
+ (id)attributeWithName:(id)arg1 pixelValue:(double)arg2;
+ (double)doubleFromString:(id)arg1 scale:(double)arg2;
+ (id)numberFromString:(id)arg1 scale:(double)arg2;
+ (id)numbersFromString:(id)arg1 scale:(double)arg2;
- (id)cssClassNamesWithBase:(id)arg1;
- (double)doubleValue;
- (double)doubleValueFromAttributeWithName:(id)arg1;
- (double)doubleValueWithScale:(double)arg1;
- (long long)integerValue;
- (id)numberValue;
- (id)numberValueWithScale:(double)arg1;
- (id)numberValues;
- (id)numberValuesWithScale:(double)arg1;
- (struct CGRect)rectValue;
- (id)simplifyAttributesIgnoringElements:(id)arg1 attributes:(id)arg2;
@end

