//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSLayerGroup.h"

@class MSColor, MSLayoutGrid, MSRulerData, MSSimpleGrid;

@interface _MSArtboardGroup : _MSLayerGroup <MSLayerGroup>
{
    BOOL _hasBackgroundColor;
    BOOL _includeBackgroundColorInExport;
    MSColor *_backgroundColor;
    MSSimpleGrid *_grid;
    MSRulerData *_horizontalRulerData;
    MSLayoutGrid *_layout;
    MSRulerData *_verticalRulerData;
}


@property(retain, nonatomic) MSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
- (void)fillInEmptyObjects;
@property(retain, nonatomic) MSSimpleGrid *grid; // @synthesize grid=_grid;
@property(nonatomic) BOOL hasBackgroundColor; // @synthesize hasBackgroundColor=_hasBackgroundColor;
- (BOOL)hasDefaultValues;
@property(retain, nonatomic) MSRulerData *horizontalRulerData; // @synthesize horizontalRulerData=_horizontalRulerData;
- (id)immutableModelObject;
@property(nonatomic) BOOL includeBackgroundColorInExport; // @synthesize includeBackgroundColorInExport=_includeBackgroundColorInExport;
- (void)initEmptyObject;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
@property(retain, nonatomic) MSLayoutGrid *layout; // @synthesize layout=_layout;
- (id)primitiveBackgroundColor;
- (id)primitiveGrid;
- (BOOL)primitiveHasBackgroundColor;
- (id)primitiveHorizontalRulerData;
- (BOOL)primitiveIncludeBackgroundColorInExport;
- (id)primitiveLayout;
- (id)primitiveVerticalRulerData;
- (void)setAsParentOnChildren;
- (void)setPrimitiveBackgroundColor:(id)arg1;
- (void)setPrimitiveGrid:(id)arg1;
- (void)setPrimitiveHasBackgroundColor:(BOOL)arg1;
- (void)setPrimitiveHorizontalRulerData:(id)arg1;
- (void)setPrimitiveIncludeBackgroundColorInExport:(BOOL)arg1;
- (void)setPrimitiveLayout:(id)arg1;
- (void)setPrimitiveVerticalRulerData:(id)arg1;
@property(retain, nonatomic) MSRulerData *verticalRulerData; // @synthesize verticalRulerData=_verticalRulerData;

@end

