//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSImmutableModelBase.h"

@class MSImmutableArray, MSPointArray;

@interface _MSImmutableGradient : MSImmutableModelBase
{
    double _elipseLength;
    struct CGPoint _from;
    long long _gradientType;
    MSPointArray *_points;
    BOOL _shouldSmoothenOpacity;
    MSImmutableArray *_stops;
    struct CGPoint _to;
}


- (void)decodePropertiesWithCoder:(id)arg1;
@property(nonatomic) double elipseLength; // @synthesize elipseLength=_elipseLength;
- (void)encodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
@property(nonatomic) struct CGPoint from; // @synthesize from=_from;
@property(nonatomic) long long gradientType; // @synthesize gradientType=_gradientType;
- (BOOL)hasDefaultValues;
- (id)initWithMutableModelObject:(id)arg1;
@property(retain, nonatomic) MSPointArray *points; // @synthesize points=_points;
@property(nonatomic) BOOL shouldSmoothenOpacity; // @synthesize shouldSmoothenOpacity=_shouldSmoothenOpacity;
@property(retain, nonatomic) MSImmutableArray *stops; // @synthesize stops=_stops;
@property(nonatomic) struct CGPoint to; // @synthesize to=_to;

@end

