//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SVGElement.h"

@class NSAffineTransform, NSSet, SVGGradient;

@interface _SVGGradient : SVGElement
{
    BOOL _absolute;
    BOOL _radial;
    NSSet *_linkedFrom;
    SVGGradient *_linkedTo;
    NSSet *_usedByFills;
    NSSet *_usedByStrokes;
    double _fromX;
    double _fromY;
    double _toX;
    double _toY;
    NSAffineTransform *_transform;
}

+ (id)attributeNames;
+ (id)propertyNames;
+ (id)relationshipNames;

@property(nonatomic) BOOL absolute; // @synthesize absolute=_absolute;
- (void)addLinkedFromObject:(id)arg1;
- (void)addUsedByFillsObject:(id)arg1;
- (void)addUsedByStrokesObject:(id)arg1;
@property(nonatomic) double fromX; // @synthesize fromX=_fromX;
@property(nonatomic) double fromY; // @synthesize fromY=_fromY;
@property(retain, nonatomic) NSSet *linkedFrom; // @synthesize linkedFrom=_linkedFrom;
@property(retain, nonatomic) SVGGradient *linkedTo; // @synthesize linkedTo=_linkedTo;
- (void)primitiveAddLinkedFromObject:(id)arg1;
- (void)primitiveAddUsedByFillsObject:(id)arg1;
- (void)primitiveAddUsedByStrokesObject:(id)arg1;
- (void)primitiveRemoveLinkedFromObject:(id)arg1;
- (void)primitiveRemoveUsedByFillsObject:(id)arg1;
- (void)primitiveRemoveUsedByStrokesObject:(id)arg1;
- (void)primitiveSetLinkedTo:(id)arg1;
@property(nonatomic) BOOL radial; // @synthesize radial=_radial;
- (void)removeLinkedFromObject:(id)arg1;
- (void)removeUsedByFillsObject:(id)arg1;
- (void)removeUsedByStrokesObject:(id)arg1;
@property(nonatomic) double toX; // @synthesize toX=_toX;
@property(nonatomic) double toY; // @synthesize toY=_toY;
@property(retain, nonatomic) NSAffineTransform *transform; // @synthesize transform=_transform;
@property(retain, nonatomic) NSSet *usedByFills; // @synthesize usedByFills=_usedByFills;
@property(retain, nonatomic) NSSet *usedByStrokes; // @synthesize usedByStrokes=_usedByStrokes;

@end

