//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AFNetworkReachabilityManager : NSObject
{
    long long _networkReachabilityStatus;
    struct __SCNetworkReachability *_networkReachability;
    unsigned long long _networkReachabilityAssociation;
    CDUnknownBlockType _networkReachabilityStatusBlock;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (id)managerForAddress:(const void *)arg1;
+ (id)managerForDomain:(id)arg1;
+ (id)sharedManager;

- (void)dealloc;
- (id)init;
- (id)initWithReachability:(struct __SCNetworkReachability *)arg1;
@property(readonly, nonatomic, getter=isReachable) BOOL reachable;
@property(readonly, nonatomic, getter=isReachableViaWWAN) BOOL reachableViaWWAN;
@property(readonly, nonatomic, getter=isReachableViaWiFi) BOOL reachableViaWiFi;
- (id)localizedNetworkReachabilityStatusString;
@property(nonatomic) struct __SCNetworkReachability *networkReachability; // @synthesize networkReachability=_networkReachability;
@property(nonatomic) unsigned long long networkReachabilityAssociation; // @synthesize networkReachabilityAssociation=_networkReachabilityAssociation;
@property(nonatomic) long long networkReachabilityStatus; // @synthesize networkReachabilityStatus=_networkReachabilityStatus;
@property(copy, nonatomic) CDUnknownBlockType networkReachabilityStatusBlock; // @synthesize networkReachabilityStatusBlock=_networkReachabilityStatusBlock;
- (void)setReachabilityStatusChangeBlock:(CDUnknownBlockType)arg1;
- (void)startMonitoring;
- (void)stopMonitoring;

@end

