//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BCLineObject : NSObject
{
    unsigned long long _axis;
    double _position;
}

+ (id)lineOnAxis:(unsigned long long)arg1 position:(double)arg2;
@property(nonatomic) unsigned long long axis; // @synthesize axis=_axis;
@property(nonatomic) double position; // @synthesize position=_position;

@end

