//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSPasteboard;

@protocol BCOutlineViewDelegate <NSObject>
- (BOOL)canCopyNodes:(NSArray *)arg1 toParent:(id)arg2 after:(id)arg3;
- (BOOL)canMoveNodes:(NSArray *)arg1 toParent:(id)arg2 after:(id)arg3;
- (void)changeSelectionTo:(NSArray *)arg1;
- (BOOL)copyNodes:(NSArray *)arg1 toParent:(id)arg2 after:(id)arg3;
@property(readonly, nonatomic) NSArray *dragTypes;
- (NSArray *)exportNodes:(NSArray *)arg1;
- (void)handleBadgePressedOnNode:(id)arg1 withAltState:(BOOL)arg2;
- (BOOL)isNodeExpandable:(id)arg1;
- (BOOL)isNodeExpanded:(id)arg1;
- (BOOL)isNodeSelected:(id)arg1;
- (BOOL)moveNodes:(NSArray *)arg1 toParent:(id)arg2 after:(id)arg3;
- (NSArray *)readNodesFromPasteboard:(NSPasteboard *)arg1;
- (void)removeNodes:(NSArray *)arg1;
- (void)updateNode:(id)arg1 expandedState:(unsigned long long)arg2;
- (BOOL)writeNodes:(NSArray *)arg1 toPasteboard:(NSPasteboard *)arg2;

@optional
- (void)hoverNodeDidChangeTo:(id)arg1;
- (NSArray *)menuItemsForSelectedObjects:(NSArray *)arg1;
@end

