//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLProtocol.h"

@interface DataProtocol : NSURLProtocol
{
}

+ (BOOL)canInitWithRequest:(id)arg1;
+ (id)canonicalRequestForRequest:(id)arg1;
+ (id)dataFromLink:(id)arg1 type:(id *)arg2 encoding:(id *)arg3;
- (void)startLoading;
- (void)stopLoading;

@end

