//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, NSBezierPath, NSMutableArray, NSNumber;

@interface FBBezierContour : NSObject <NSCopying>
{
    NSMutableArray *_overlaps;
    NSMutableArray *_edges;
    NSBezierPath *_bezPathCache;
    struct CGRect _bounds;
    struct CGRect _boundingRect;
    NSNumber *_cachedDirection;
    int _inside;
}

+ (id)bezierContourWithCurve:(id)arg1;

- (void)addCurve:(id)arg1;
- (void)addCurveFrom:(id)arg1 to:(id)arg2;
- (void)addOverlap:(id)arg1;
- (void)addReverseCurve:(id)arg1;
- (void)addReverseCurveFrom:(id)arg1 to:(id)arg2;
- (void)addSelfIntersectingContoursToArray:(id)arg1 originalContour:(id)arg2;
- (long long)adjustWindingCount:(long long)arg1 forIntersection:(id)arg2;
- (long long)adjustWindingCount:(long long)arg1 onEdge:(id)arg2 atParameter:(double)arg3;
- (id)allCrossingsWithGroupedCoincidentPairs;
- (id)bezierPath;
- (id)bezierPathFromEdge:(id)arg1 toEdge:(id)arg2;
@property(readonly, nonatomic) struct CGRect boundingRect;
@property(readonly, nonatomic) struct CGRect bounds;
@property(retain, nonatomic) NSNumber *cachedDirection;
- (void)close;
- (id)closestLocationToPoint:(struct CGPoint)arg1;
- (BOOL)containsCrossingUsingNonZeroWindingRule:(id)arg1;
- (BOOL)containsPoint:(struct CGPoint)arg1;
- (BOOL)containsPointUsingNonZeroWindingRule:(struct CGPoint)arg1;
- (BOOL)containsUsingNonZeroWindingRulePoint:(struct CGPoint)arg1 onEdge:(id)arg2 atParameter:(double)arg3;
- (BOOL)contourAndSelfIntersectingContoursContainPoint:(struct CGPoint)arg1;
- (id)contourMadeClockwiseIfNecessary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)crossesOwnContour:(id)arg1;
- (id)crossingContainmentRay:(struct CGPoint)arg1;
- (void)debugDrawColor:(id)arg1 scale:(double)arg2;
- (id)debugPathForContainmentOfCrossing:(id)arg1 transform:(struct CGAffineTransform)arg2;
- (id)debugPathForIntersectionType:(long long)arg1 withTransform:(struct CGAffineTransform)arg2 andSizeTransform:(struct CGAffineTransform)arg3;
- (id)debugPathForJointsWithTransform:(struct CGAffineTransform)arg1 andSizeTransform:(struct CGAffineTransform)arg2;
- (id)debugPathForWindingRuleContainmentAtEdge:(id)arg1 parameter:(double)arg2 point:(struct CGPoint)arg3 withTransform:(struct CGAffineTransform)arg4 andSizeTransform:(struct CGAffineTransform)arg5;
- (id)debugPathForWindingRuleContainmentWithTransform:(struct CGAffineTransform)arg1 andSizeTransform:(struct CGAffineTransform)arg2;
- (id)debugQuickLookObject;
- (id)description;
@property(readonly, nonatomic) int direction;
- (BOOL)doesOverlapContainCrossing:(id)arg1;
- (BOOL)doesOverlapContainParameter:(double)arg1 onEdge:(id)arg2;
@property(readonly, nonatomic) NSArray *edges; // @synthesize edges=_edges;
@property(readonly, nonatomic) struct CGPoint firstPoint;
- (void)forEachEdgeOverlapDo:(CDUnknownBlockType)arg1;
- (id)init;
@property(nonatomic) int inside; // @synthesize inside=_inside;
@property(readonly, nonatomic) __weak NSArray *intersectingContours;
- (BOOL)intersection:(id)arg1 isReallyTheSameAs:(id)arg2;
- (BOOL)intersection:(id)arg1 isReallyTheSameAsCurve:(id)arg2 atParameter:(double)arg3;
- (void)intersectionsWithRay:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) BOOL isClosed;
- (BOOL)isCrossing:(id)arg1 betweenStartEdge:(id)arg2 parameter:(double)arg3 andCrossing:(id)arg4;
@property(readonly, nonatomic) BOOL isEmpty;
- (BOOL)isEquivalent:(id)arg1;
- (BOOL)isInflectionPointOnEdge:(id)arg1 atParameter:(double)arg2;
- (void)markCrossingsAsEntryOrExitWithContour:(id)arg1 markInside:(BOOL)arg2;
- (BOOL)markCrossingsOnEdge:(id)arg1 startParameter:(double)arg2 stopParameter:(double)arg3 otherContours:(id)arg4 isEntry:(BOOL)arg5;
- (void)markSelfCrossingsAsEntryOrExit;
- (BOOL)markSelfCrossingsOnEdge:(id)arg1 startParameter:(double)arg2 stopParameter:(double)arg3 isEntry:(BOOL)arg4 withBlock:(CDUnknownBlockType)arg5;
- (unsigned long long)numberOfIntersectionsWithRay:(id)arg1;
@property(readonly, nonatomic) __weak NSMutableArray *overlaps_;
- (void)removeAllOverlaps;
- (id)reversedContour;
@property(readonly, nonatomic) __weak NSArray *selfIntersectingContours;
- (void)sortCoincidentCrossings;
- (id)startEdge;
- (id)startEdgeSkipHorizontals:(BOOL)arg1 skipInflectionPoints:(BOOL)arg2;
- (void)startingEdge:(id *)arg1 parameter:(double *)arg2 point:(struct CGPoint *)arg3 skipHorizontals:(BOOL)arg4 skipInflectionPoints:(BOOL)arg5;
- (id)testRayForContainment:(struct CGRect)arg1;

@end

