//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSGradientEventHandler.h"

@interface MSAngularGradientEventHandler : MSGradientEventHandler
{
}

- (long long)addStopAtPosition:(struct CGPoint)arg1;
- (struct CGPoint)basePointAtIndex:(unsigned long long)arg1;
- (struct CGRect)bounds;
- (BOOL)canInsertPointAtMouse:(struct CGPoint)arg1;
- (id)handleLinesPath;
- (struct CGPoint)pointAtIndex:(unsigned long long)arg1;
- (double)positionForStop:(struct CGPoint)arg1;
- (void)repairGradientIfNecessary;
- (void)replacePointAtIndex:(long long)arg1 withPoint:(struct CGPoint)arg2;

@end

