//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSKeyedArchiver.h"

@class NSMutableSet;

@interface MSArchiver : NSKeyedArchiver
{
    BOOL _archiveObjectIDs;
    NSMutableSet *_archivedImages;
}

+ (BOOL)archiveRootObject:(id)arg1 withObjectIDs:(BOOL)arg2 toURL:(id)arg3;
+ (id)archivedDataWithHeaderAndRootObject:(id)arg1 withObjectIDs:(BOOL)arg2;
+ (id)archivedDataWithRootObject:(id)arg1 withObjectIDs:(BOOL)arg2;

@property(nonatomic) BOOL archiveObjectIDs; // @synthesize archiveObjectIDs=_archiveObjectIDs;
@property(retain, nonatomic) NSMutableSet *archivedImages; // @synthesize archivedImages=_archivedImages;

@end

