//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSBaseGrid.h"

@interface MSBaseGrid : _MSBaseGrid
{
}

+ (void)initialize;
- (void)drawInRect:(struct CGRect)arg1 baseLine:(struct CGPoint)arg2 atZoom:(double)arg3;
- (id)horizontalGuidesForRulerData:(id)arg1 inRect:(struct CGRect)arg2;
- (void)setIsEnabled:(BOOL)arg1;
- (BOOL)shouldDraw;
- (id)verticalGuidesForRulerData:(id)arg1 inRect:(struct CGRect)arg2;

@end

