//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSAssetCollection, MSColor, MSColorInspectorSectionPattern, MSEventHandlerManager, MSPersistentAssetCollection;

@protocol MSColorInspectorSectionDelegate <NSObject>
- (void)colorDidChangeTo:(MSColor *)arg1;
- (MSAssetCollection *)documentAssets;
- (MSEventHandlerManager *)eventHandler;
- (MSPersistentAssetCollection *)globalAssets;
- (void)inspectorSectionDidUpdate:(MSColorInspectorSectionPattern *)arg1;
- (void)stack;
@end

