//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSBaseAction.h"

@interface MSCreateSharedLayerStyleAction : MSBaseAction
{
}

- (void)createSharedLayerStyle:(id)arg1;
- (void)createSharedObjectFromSelectedLayer;
- (id)displayNameForNewSharedObject;
- (void)doPerformAction:(id)arg1;
- (id)firstLayer;
- (id)imageName;
- (id)label;
- (id)sharedObjectContainer;
- (struct MSModelObject *)sharedObjectInstance;
- (id)toolbarLabel;
- (BOOL)validate;

@end

