//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSBaseAction.h"

@interface MSCreateSymbolAction : MSBaseAction
{
}

- (void)createSymbolAction:(id)arg1;
- (void)doPerformAction:(id)arg1;
- (id)imageName;
- (void)isolateSymbolAction:(id)arg1;
- (id)layerSymbols;
- (void)refreshUI;
- (void)toggleCreateSymbolOrIsolate:(id)arg1;
- (id)toolbarLabel;
- (BOOL)validate;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)willIsolate;

@end

