//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@class NSEvent;

@interface MSDocumentWindow : NSWindow
{
    NSEvent *_lastForwardedKeyEvent;
}


- (BOOL)closePopovers;
- (void)keyDown:(id)arg1;
@property(nonatomic) __weak NSEvent *lastForwardedKeyEvent; // @synthesize lastForwardedKeyEvent=_lastForwardedKeyEvent;
- (void)sendEvent:(id)arg1;
- (BOOL)shouldDismissPopover:(id)arg1 event:(id)arg2;

@end

