//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSExportRequest, NSColorSpace;

@protocol MSExportRenderer <NSObject>

+ (id)exportRendererForRequest:(id)arg1 colorSpace:(id)arg2;

- (id)EPSData;
- (id)JPGData;
- (id)PDFData;
- (id)PNGData;
- (id)TIFFData;
- (id)basicBitmapImageRep;
- (id)bitmapImageRep;
@property(nonatomic) struct CGRect bounds; // @synthesize bounds=_bounds;
- (struct CGRect)boundsForVectorRender;
@property(retain, nonatomic) NSColorSpace *colorSpace; // @synthesize colorSpace=_colorSpace;
- (id)data;
- (void)draw;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawSliceBackgroundIfNecessary;
- (id)image;
@property(nonatomic) BOOL isPrinting; // @synthesize isPrinting=_isPrinting;
@property(retain, nonatomic) MSExportRequest *request; // @synthesize request=_request;

@end

