//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSColor, MSPage, NSSet, NSString;

@protocol MSExportRequest <NSObject>

+ (id)requestWithName:(id)arg1 rect:(struct CGRect)arg2;
+ (id)requestWithRect:(struct CGRect)arg1 scale:(double)arg2;

@property(copy, nonatomic) MSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) BOOL compact; // @synthesize compact=_compact;
@property(nonatomic) double compression; // @synthesize compression=_compression;
@property(copy, nonatomic) NSString *format; // @synthesize format=_format;
@property(nonatomic) BOOL includeArtboardBackground; // @synthesize includeArtboardBackground=_includeArtboardBackground;
@property(copy, nonatomic) NSSet *includedLayerIDs; // @synthesize includedLayerIDs=_includedLayerIDs;
- (id)init;
- (BOOL)layerIsIncluded:(id)arg1;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) unsigned long long options; // @synthesize options=_options;
@property(retain, nonatomic) MSPage *page; // @synthesize page=_page;
@property(nonatomic) BOOL progressive; // @synthesize progressive=_progressive;
@property(nonatomic) struct CGRect rect; // @synthesize rect=_rect;
@property(copy, nonatomic) id rootLayerID; // @synthesize rootLayerID=_rootLayerID;
@property(nonatomic) BOOL saveForWeb; // @synthesize saveForWeb=_saveForWeb;
@property(nonatomic) double scale; // @synthesize scale=_scale;
@property(nonatomic) BOOL shouldTrim; // @synthesize shouldTrim=_shouldTrim;

@end

