//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSGridSheetBase.h"

@interface MSGridSheet : MSGridSheetBase
{
}

- (void)applyObject:(id)arg1 toLayer:(id)arg2;
- (id)cacheObjectForRootLayer:(id)arg1;
- (id)defaultObject;
- (void)setAsDefault:(id)arg1;

@end

