//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSImageCollection.h"

@interface MSImageCollection : _MSImageCollection
{
}

- (void)addImageToIndex:(id)arg1;
- (void)addImageToIndexIfMissing:(id)arg1;
- (id)addNSImage:(id)arg1 convertColourspace:(BOOL)arg2;
- (void)addRawImageDataIndexedBySHA:(id)arg1;
- (id)description;
- (id)imageWithSHA1:(id)arg1;
- (void)purgeImagesNotMatchingSHAs:(id)arg1;
- (id)rawImageDataIndexedBySHAs:(id)arg1;
- (id)treeAsDictionary;
- (unsigned long long)uniqueImageCount;

@end

