//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSImmutableShapeGroup.h"

@class NSBezierPath;

@interface MSImmutableShapeGroup : _MSImmutableShapeGroup
{
    BOOL _isEditingChild;
    NSBezierPath *_bezierPathWithTransformsForMasking;
    NSBezierPath *_bezierInBounds;
}


@property(retain, nonatomic) NSBezierPath *bezierInBounds; // @synthesize bezierInBounds=_bezierInBounds;
@property(retain, nonatomic) NSBezierPath *bezierPathWithTransformsForMasking; // @synthesize bezierPathWithTransformsForMasking=_bezierPathWithTransformsForMasking;
- (id)initWithMutableModelObject:(id)arg1;
@property(nonatomic) BOOL isEditingChild; // @synthesize isEditingChild=_isEditingChild;

@end

