//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSImmutableModelBase.h"

#import "NSFastEnumeration.h"

@class NSArray;

@interface MSImmutableArray : MSImmutableModelBase <NSFastEnumeration>
{
    NSArray *array;
}


@property(readonly, copy, nonatomic) NSArray *array; // @synthesize array;
- (BOOL)containsObject:(id)arg1;
- (unsigned long long)count;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)decodePropertiesWithCoder:(id)arg1;
- (id)description;
- (void)encodePropertiesWithCoder:(id)arg1;
- (void)enumerate:(CDUnknownBlockType)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (id)filteredArrayUsingBlock:(CDUnknownBlockType)arg1;
- (id)firstObject;
- (id)firstObjectSatisfyingTest:(CDUnknownBlockType)arg1;
- (BOOL)hasDefaultValues;
- (unsigned long long)indexOfObject:(id)arg1;
- (id)initWithMutableModelObject:(id)arg1;
- (BOOL)isValidIndex:(unsigned long long)arg1;
- (id)lastObject;
- (id)map:(CDUnknownBlockType)arg1;
- (id)objectAtIndex:(unsigned long long)arg1;
- (id)objectAtIndexOrNil:(unsigned long long)arg1;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;

@end

