//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CHViewController.h"

@class CHViewController<MSInspectorChildController>, MSDocument, MSExportInspectorViewController, MSExportableLayerInspectorViewController, MSNormalInspector, MSPersistentAssetCollection, NSView;

@interface MSInspectorController : CHViewController
{
    NSView *_placeholderView;
    NSView *_alignmentView;
    CHViewController<MSInspectorChildController> *_currentController;
    MSDocument *_document;
    MSPersistentAssetCollection *_globalAssets;
    MSNormalInspector *_normalInspector;
    MSExportableLayerInspectorViewController *_exportableInspector;
    MSExportInspectorViewController *_bottomExporter;
    unsigned long long _oldInspectorLocation;
}


@property(retain, nonatomic) NSView *alignmentView; // @synthesize alignmentView=_alignmentView;
- (void)awakeFromNib;
- (void)beginRenameSharedObject:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) MSExportInspectorViewController *bottomExporter; // @synthesize bottomExporter=_bottomExporter;
- (void)changeColor:(id)arg1;
- (void)changeTextLayerFont:(id)arg1;
- (void)connectAlignmentButtons;
@property(retain, nonatomic) CHViewController<MSInspectorChildController> *currentController; // @synthesize currentController=_currentController;
- (id)currentControllerForReturningToNormalHandler;
- (void)currentHandlerChanged;
- (void)dealloc;
@property(nonatomic) __weak MSDocument *document; // @synthesize document=_document;
- (void)exportSingleSlice:(id)arg1;
@property(retain, nonatomic) MSExportableLayerInspectorViewController *exportableInspector; // @synthesize exportableInspector=_exportableInspector;
- (id)firstTextFieldInView:(id)arg1;
- (void)focusOnFirstTextField;
@property(retain, nonatomic) MSPersistentAssetCollection *globalAssets; // @synthesize globalAssets=_globalAssets;
- (id)handlerManager;
- (void)hideExportBarIfNecessary;
- (id)init;
- (void)layerPositionPossiblyChanged;
- (BOOL)layersAreExportable:(id)arg1;
@property(retain, nonatomic) MSNormalInspector *normalInspector; // @synthesize normalInspector=_normalInspector;
@property(nonatomic) unsigned long long oldInspectorLocation; // @synthesize oldInspectorLocation=_oldInspectorLocation;
@property(retain, nonatomic) NSView *placeholderView; // @synthesize placeholderView=_placeholderView;
- (void)prepareForDisplay;
- (void)reload;
- (void)reloadSharedObjectsSection;
- (id)rootViewController;
- (void)selectionDidChangeTo:(id)arg1;
- (void)shapeSelectionDidChange:(id)arg1;
- (id)sharedObjectsSection;
- (BOOL)shouldShowExportBar;
- (void)showBorderOptionsAction:(id)arg1;
- (void)showFillOptionsAction:(id)arg1;
- (void)undoNotification:(id)arg1;
- (void)validateAlignmentButtons;
- (void)viewDidResize;

@end

