//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class MSUpDownController, NSTimer;

@interface MSIntegratedStepper : NSView
{
    BOOL _keepFiringTimer;
    MSUpDownController *_target;
    NSTimer *_timer;
    NSTimer *_initialSlowTimer;
    long long _highlightMode;
}


- (BOOL)acceptsFirstMouse:(id)arg1;
- (BOOL)clickShouldDismissPopover:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) long long highlightMode; // @synthesize highlightMode=_highlightMode;
@property(retain, nonatomic) NSTimer *initialSlowTimer; // @synthesize initialSlowTimer=_initialSlowTimer;
- (BOOL)isFlipped;
@property(nonatomic) BOOL keepFiringTimer; // @synthesize keepFiringTimer=_keepFiringTimer;
- (void)mouseDown:(id)arg1;
- (void)repeatStepEvent:(id)arg1;
@property(nonatomic) __weak MSUpDownController *target; // @synthesize target=_target;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
- (void)stepWithEvent:(id)arg1;
- (id)timerWithInterval:(double)arg1 repeats:(BOOL)arg2;

@end

