//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MSLayerBuilder : NSObject
{
}

+ (id)layerTreeWithContentsOfURL:(id)arg1 error:(id *)arg2;
+ (id)layerTreeWithDictionary:(id)arg1;
+ (id)layerTreeWithJSON:(id)arg1 relativeToURL:(id)arg2 error:(id *)arg3;
+ (id)styleFromDictionary:(id)arg1;

@end

