//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MSLayer, NSArray;

@protocol MSLayerContainment
- (BOOL)canBeContainedByDocument;
- (BOOL)canBeContainedByGroup;
- (BOOL)canContainLayer:(MSLayer *)arg1;
- (NSArray *)containedLayers;
- (unsigned long long)containedLayersCount;
- (BOOL)containsLayers;
- (BOOL)containsMultipleLayers;
- (BOOL)containsNoOrOneLayers;
- (BOOL)containsOneLayer;
- (void)enumerateLayers:(void (^)(id))arg1;
- (BOOL)enumerateLayersWithOptions:(unsigned long long)arg1 block:(void (^)(id, unsigned long long, char *))arg2;
- (id)firstLayer;
- (unsigned long long)indexOfLayer:(id)arg1;
- (id)lastLayer;
- (id)layerAtIndex:(unsigned long long)arg1;
@end

