//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSTableViewDataSource.h"

@class NSArray, NSString, NSTableView, NSWindow;

@interface MSMissingFontsDialog : NSWindowController <NSTableViewDataSource>
{
    NSWindow *panel;
    NSTableView *tableView;
    BOOL openDocumentAnyway;
    NSArray *_missingFonts;
}


- (void)close:(id)arg1;
- (void)dealloc;
@property(copy, nonatomic) NSArray *missingFonts; // @synthesize missingFonts=_missingFonts;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)openAnyway:(id)arg1;
- (BOOL)runPanelWithMissingFonts:(id)arg1;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

