//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CHSingletonObject.h"

@class NSArray, NSBundle;

@interface MSModelResources : CHSingletonObject
{
    NSBundle *_bundle;
    NSArray *_noiseImages;
    unsigned long long _status;
}

+ (id)sharedInstance;

- (id)URLForImageResource:(id)arg1;
- (id)URLForResource:(id)arg1 withExtension:(id)arg2;
@property(retain, nonatomic) NSBundle *bundle; // @synthesize bundle=_bundle;
- (id)loadNoiseImageWithIndex:(long long)arg1;
@property(copy, nonatomic) NSArray *noiseImages; // @synthesize noiseImages=_noiseImages;
- (void)preloadResources;
- (id)resourcesNeedingMigration;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;

@end

