//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSDocument.h"

@interface MSNonAutosavingDocument : MSDocument
{
}

+ (BOOL)autosavesInPlace;
- (id)fileType;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;

@end

