//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "BCPopoverContentController.h"

@class MSTextLayerSection, NSArray, NSPopUpButton, NSSegmentedControl, NSString;

@interface MSParagraphStyleViewController : NSViewController <BCPopoverContentController>
{
    MSTextLayerSection *_textSection;
    NSArray *_layers;
    NSSegmentedControl *_decorationButton;
    NSPopUpButton *_listPopUpButton;
}


- (void)awakeFromNib;
- (void)changeFontPropertiesOfTextObjectsInBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSSegmentedControl *decorationButton; // @synthesize decorationButton=_decorationButton;
- (void)decorationButtonAction:(id)arg1;
- (id)firstOccurrenceOfAttributeWithName:(id)arg1;
- (long long)indexForBulletListName:(id)arg1;
- (id)init;
@property(retain, nonatomic) NSArray *layers; // @synthesize layers=_layers;
- (void)listPopUpAction:(id)arg1;
@property(retain, nonatomic) NSPopUpButton *listPopUpButton; // @synthesize listPopUpButton=_listPopUpButton;
- (id)markerForBulletListIndex:(long long)arg1;
- (void)prepareBulletListPopUpButton;
- (void)prepareDecorationButton;
@property(nonatomic) __weak MSTextLayerSection *textSection; // @synthesize textSection=_textSection;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

