//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSBaseAction.h"

@interface MSPencilAction : MSBaseAction
{
}

- (void)doPerformAction:(id)arg1;
- (BOOL)isActive;
- (BOOL)isSelectable;
- (void)pencil:(id)arg1;
- (unsigned short)shortcutCharacter;
- (id)tooltip;

@end

