//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSPluginScript.h"

@class NSString;

@interface MSPluginLegacyScript : MSPluginScript
{
    NSString *_processedScript;
}

+ (id)wrappedScript:(id)arg1 handler:(id)arg2;

@property(readonly, copy, nonatomic) NSString *handler;
@property(copy, nonatomic) NSString *processedScript; // @synthesize processedScript=_processedScript;
@property(readonly, copy, nonatomic) NSString *rawScript;
- (id)script;
- (id)scriptWithReplacedImports:(id)arg1 path:(id)arg2 importedURLs:(id)arg3;

@end

