//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSPreferencePane.h"

#import "NSTableViewDelegate.h"

@class BCKeyEventActionTableView, MSPluginManager, NSArray, NSArrayController, NSButton, NSCache, NSControl, NSFont, NSImage, NSLayoutConstraint, NSMenu, NSPredicate, NSString, NSTableCellView, NSTextField;

@interface MSPluginsPreferencePane : MSPreferencePane <NSTableViewDelegate>
{
    BOOL _observingPlugins;
    NSArrayController *_pluginsArrayController;
    NSArray *_filteredPlugins;
    NSPredicate *_pluginFilterPredicate;
    NSImage *_zeroPluginsImage;
    NSString *_zeroPluginsTitle;
    NSString *_zeroPluginsText;
    NSTextField *_filterTextField;
    BCKeyEventActionTableView *_tableView;
    NSButton *_getPluginsButton;
    NSControl *_contextMenuControl;
    NSMenu *_contextMenu;
    MSPluginManager *_pluginManager;
    NSTableCellView *_pluginCellView;
    NSLayoutConstraint *_pluginCellViewWidthConstraint;
    NSCache *_rowHeightCache;
}

+ (id)identifier;
+ (id)title;
+ (id)toolbarIcon;

- (void)awakeFromNib;
@property(nonatomic) __weak NSMenu *contextMenu; // @synthesize contextMenu=_contextMenu;
@property(nonatomic) __weak NSControl *contextMenuControl; // @synthesize contextMenuControl=_contextMenuControl;
- (void)controlTextDidChange:(id)arg1;
- (void)dealloc;
- (void)disablePluginInfo:(id)arg1;
- (void)enablePluginInfo:(id)arg1;
@property(nonatomic) __weak NSTextField *filterTextField; // @synthesize filterTextField=_filterTextField;
@property(copy, nonatomic) NSArray *filteredPlugins; // @synthesize filteredPlugins=_filteredPlugins;
- (void)getPlugins:(id)arg1;
@property(nonatomic) __weak NSButton *getPluginsButton; // @synthesize getPluginsButton=_getPluginsButton;
- (id)initWithPreferencesController:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(nonatomic) BOOL observingPlugins; // @synthesize observingPlugins=_observingPlugins;
- (void)openPluginsFolder:(id)arg1;
@property(retain, nonatomic) NSTableCellView *pluginCellView; // @synthesize pluginCellView=_pluginCellView;
@property(retain, nonatomic) NSLayoutConstraint *pluginCellViewWidthConstraint; // @synthesize pluginCellViewWidthConstraint=_pluginCellViewWidthConstraint;
@property(copy, nonatomic) NSPredicate *pluginFilterPredicate; // @synthesize pluginFilterPredicate=_pluginFilterPredicate;
@property(nonatomic) __weak MSPluginManager *pluginManager; // @synthesize pluginManager=_pluginManager;
@property(readonly, copy, nonatomic) NSArray *pluginSortDescriptors;
@property(retain, nonatomic) NSArrayController *pluginsArrayController; // @synthesize pluginsArrayController=_pluginsArrayController;
- (id)pluginsAtRowIndexes:(id)arg1;
- (void)revealInFinder:(id)arg1;
@property(retain, nonatomic) NSCache *rowHeightCache; // @synthesize rowHeightCache=_rowHeightCache;
- (id)searchString;
@property(nonatomic) __weak BCKeyEventActionTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSImage *zeroPluginsImage; // @synthesize zeroPluginsImage=_zeroPluginsImage;
@property(copy, nonatomic) NSString *zeroPluginsText; // @synthesize zeroPluginsText=_zeroPluginsText;
@property(copy, nonatomic) NSString *zeroPluginsTitle; // @synthesize zeroPluginsTitle=_zeroPluginsTitle;
- (void)tableContextMenu:(id)arg1;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (void)toggleItemsEnabled:(id)arg1;
- (void)togglePluginEnabled:(id)arg1;
- (void)toggleSelectedItemsEnabled;
- (void)toggleSelectedItemsEnabled:(id)arg1;
- (void)uninstallPlugins:(id)arg1;
- (void)uninstallSelectedPlugins;
- (void)uninstallSelectedPlugins:(id)arg1;
- (void)updateUIForPluginsChange;
- (void)viewDocumentation:(id)arg1;
@property(readonly, copy, nonatomic) NSFont *zeroPluginsTitleFont;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

