//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSColorSpace;

@interface MSSliceExporter : NSObject
{
    BOOL _honorSaveForWebPreference;
    NSColorSpace *_colorSpace;
}

+ (id)dataForRequest:(id)arg1;
+ (id)dataForRequest:(id)arg1 colorSpace:(id)arg2;
+ (id)dataForRequest:(id)arg1 colorSpace:(id)arg2 honorSaveForWeb:(BOOL)arg3;

- (void)clearLayerCaches:(id)arg1;
@property(retain, nonatomic) NSColorSpace *colorSpace; // @synthesize colorSpace=_colorSpace;
- (id)dataForRequest:(id)arg1;
- (void)displayNoSlicesWarning;
- (void)exportSlice:(id)arg1;
- (void)exportSlices:(id)arg1;
@property(nonatomic) BOOL honorSaveForWebPreference; // @synthesize honorSaveForWebPreference=_honorSaveForWebPreference;
- (id)makeFilenameProperPathIfNecessary:(id)arg1;
- (id)openPanelWithOptions:(id)arg1;
- (id)savePanelWithDefaultFilename:(id)arg1 options:(id)arg2;
- (void)saveSlices:(id)arg1 toFolder:(id)arg2;
- (void)showSavePanelToExportIndividualSlice:(id)arg1 options:(id)arg2;
- (void)showSaveToFolderPanelToExportSlices:(id)arg1 options:(id)arg2;
- (id)strippedSliceName:(id)arg1;
- (BOOL)warnForPossiblyOverwritingFilesWithSlices:(id)arg1 toFolder:(id)arg2;
- (void)writeSlice:(id)arg1 toPathWithName:(id)arg2;
- (void)writeSliceWithCurrentSettings:(id)arg1 toPathWithName:(id)arg2;

@end

