//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CHSheetController.h"

@class NSTextField;

@interface MSSmartRotateSheet : CHSheetController
{
    NSTextField *_explanationLabel;
    long long _numberOfCopies;
}


- (void)awakeFromNib;
- (void)cancel:(id)arg1;
- (void)confirm:(id)arg1;
- (id)doc;
@property(retain, nonatomic) NSTextField *explanationLabel; // @synthesize explanationLabel=_explanationLabel;
@property(nonatomic) long long numberOfCopies; // @synthesize numberOfCopies=_numberOfCopies;
- (void)setNilValueForKey:(id)arg1;

@end

