//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSBaseRenderer.h"

@class MSRenderingContext, MSStyleFill, NSBezierPath;

@interface MSStyleFillRenderer : MSBaseRenderer
{
    BOOL _hasInnerStroke;
    MSRenderingContext *_context;
    MSStyleFill *_fill;
    NSBezierPath *_path;
    long long _fillIndex;
    double _zoomValue;
    struct CGRect _rect;
}

+ (void)drawFill:(id)arg1 forPath:(id)arg2 atIndex:(long long)arg3 inRect:(struct CGRect)arg4 hasInnerStroke:(BOOL)arg5 context:(id)arg6;

- (struct CGImage *)CGImageForPatternTile;
@property(nonatomic) __weak MSRenderingContext *context; // @synthesize context=_context;
- (void)drawCGImageTile:(struct CGImage *)arg1;
- (void)drawColorFill;
- (void)drawGradientFill;
- (void)drawNoise;
- (void)drawPatternFill;
- (void)drawPatternStretch;
- (void)drawPatternTile;
@property(retain, nonatomic) MSStyleFill *fill; // @synthesize fill=_fill;
@property(nonatomic) long long fillIndex; // @synthesize fillIndex=_fillIndex;
@property(nonatomic) BOOL hasInnerStroke; // @synthesize hasInnerStroke=_hasInnerStroke;
@property(retain, nonatomic) NSBezierPath *path; // @synthesize path=_path;
- (void)prepareAlphaForContext:(struct CGContext *)arg1;
@property(nonatomic) struct CGRect rect; // @synthesize rect=_rect;
- (void)render;
@property(nonatomic) double zoomValue; // @synthesize zoomValue=_zoomValue;

@end

