//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSTextStyle.h"

@interface MSTextStyle : _MSTextStyle
{
}

+ (id)styleWithAttributes:(id)arg1;
- (void)setAttributes:(id)arg1;
- (void)syncOwningTextLayerWithThisStyle;
- (id)treeAsDictionary;

@end

