//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSLayerSection.h"

#import "BCPopoverDelegate.h"
#import "MSColorInspectorDelegate.h"
#import "NSComboBoxDataSource.h"
#import "NSMenuDelegate.h"

@class BCPopover, MSColorPreviewButton, MSLineHeightTextFieldCell, NSButton, NSPopUpButton, NSSegmentedControl, NSString, NSTextField, NSView;

@interface MSTextLayerSection : MSLayerSection <NSMenuDelegate, BCPopoverDelegate, MSColorInspectorDelegate, NSComboBoxDataSource>
{
    NSView *_basicView;
    NSView *_symbolExclusionView;
    NSButton *_fontFamilyButton;
    NSPopUpButton *_fontWeightPopUpButton;
    NSTextField *_fontSizeField;
    MSColorPreviewButton *_colorPickerButton;
    NSTextField *_kerningField;
    NSTextField *_lineHeightField;
    MSLineHeightTextFieldCell *_lineHeightCell;
    NSTextField *_paragraphHeightField;
    NSSegmentedControl *_alignmentButton;
    BCPopover *_popover;
}

+ (void)initialize;

@property(retain, nonatomic) NSSegmentedControl *alignmentButton; // @synthesize alignmentButton=_alignmentButton;
- (void)alignmentButtonAction:(id)arg1;
- (void)awakeFromNib;
@property(retain, nonatomic) NSView *basicView; // @synthesize basicView=_basicView;
- (BOOL)canHandleColorMagnifierAction;
- (void)changeFontFamilyTo:(id)arg1;
- (void)changeFontPropertiesInBlock:(CDUnknownBlockType)arg1;
- (void)changeFontPropertiesOfTextObjectsInBlock:(CDUnknownBlockType)arg1;
- (void)changeParagraphStyleInBlock:(CDUnknownBlockType)arg1;
- (void)changeTextLayerFont:(id)arg1;
- (void)closeExistingPopoverOrShowNewOneWithContentClass:(Class)arg1 sender:(id)arg2 viewCreatorBlock:(CDUnknownBlockType)arg3;
- (void)colorInspector:(id)arg1 didChangeToColor:(id)arg2;
- (void)colorInspectorWillClose:(id)arg1;
- (void)colorMagnifierAction:(id)arg1;
@property(retain, nonatomic) MSColorPreviewButton *colorPickerButton; // @synthesize colorPickerButton=_colorPickerButton;
- (id)colorSpaceForFirstColor;
- (id)comboBox:(id)arg1 objectValueForItemAtIndex:(long long)arg2;
- (id)currentFontFamilyName;
- (id)currentView;
- (void)dealloc;
- (double)defaultLineHeight;
- (id)firstColor;
- (id)firstOccurrenceOfAttributeWithName:(id)arg1;
- (void)fontFamilyAction:(id)arg1;
@property(retain, nonatomic) NSButton *fontFamilyButton; // @synthesize fontFamilyButton=_fontFamilyButton;
- (void)fontSizeAction:(id)arg1;
@property(retain, nonatomic) NSTextField *fontSizeField; // @synthesize fontSizeField=_fontSizeField;
- (void)fontWeightAction:(id)arg1;
@property(retain, nonatomic) NSPopUpButton *fontWeightPopUpButton; // @synthesize fontWeightPopUpButton=_fontWeightPopUpButton;
- (void)kerningAction:(id)arg1;
@property(retain, nonatomic) NSTextField *kerningField; // @synthesize kerningField=_kerningField;
- (double)lineHeight;
- (void)lineHeightAction:(id)arg1;
@property(retain, nonatomic) MSLineHeightTextFieldCell *lineHeightCell; // @synthesize lineHeightCell=_lineHeightCell;
@property(retain, nonatomic) NSTextField *lineHeightField; // @synthesize lineHeightField=_lineHeightField;
- (long long)numberOfItemsInComboBox:(id)arg1;
- (void)paragraphHeightAction:(id)arg1;
@property(retain, nonatomic) NSTextField *paragraphHeightField; // @synthesize paragraphHeightField=_paragraphHeightField;
@property(retain, nonatomic) BCPopover *popover; // @synthesize popover=_popover;
- (void)popoverWillClose:(id)arg1;
- (void)putFocusOnTextView;
- (void)reloadData;
- (void)reloadFontWeightPopUp;
- (void)reloadLineHeightField;
@property(retain, nonatomic) NSView *symbolExclusionView; // @synthesize symbolExclusionView=_symbolExclusionView;
- (void)showColorPickerAction:(id)arg1;
- (void)showParagraphStylingAction:(id)arg1;
- (BOOL)textLayerContainedInSymbol;
- (id)textStorages;
- (id)textView;
- (void)textViewDidChange:(id)arg1;
- (void)updateKerningForFontChangeTo:(id)arg1 string:(id)arg2 range:(struct _NSRange)arg3 effectiveRange:(struct _NSRange)arg4 oldPointSize:(double)arg5;
- (void)viewWillDisappear;
- (id)views;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

