//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSBaseAction.h"

@interface MSTogglePixelGridAction : MSBaseAction
{
}

- (void)doPerformAction:(id)arg1;
- (id)imageName;
- (BOOL)isShowingPixelatedView;
- (id)label;
- (void)togglePixelGrid:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;

@end

