//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSToolbarItem.h"

@class MSZoomAction;

@interface MSZoomActionToolbarItem : NSToolbarItem
{
    MSZoomAction *_zoomAction;
}


@property(nonatomic) __weak MSZoomAction *zoomAction; // @synthesize zoomAction=_zoomAction;
- (void)validate;

@end

