//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (BCFoundation)
- (id)arrayForKey_BC:(id)arg1;
- (BOOL)boolForKey_BC:(id)arg1;
- (id)dictionaryForKey_BC:(id)arg1;
- (id)numberForKey_BC:(id)arg1;
- (id)stringForKey_BC:(id)arg1;
- (id)urlForKey_BC:(id)arg1;
@end

