//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSGradient.h"

@interface NSGradient (CHGradientExtensions)
+ (void)drawHorizontalGradientInRect:(struct CGRect)arg1 leftColor:(id)arg2 rightColor:(id)arg3;
+ (void)drawVerticalGradientInRect:(struct CGRect)arg1 topColor:(id)arg2 bottomColor:(id)arg3;
- (id)debugQuickLookObject;
@end

