//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SVGColor : NSObject
{
    double _red;
    double _green;
    double _blue;
    double _alpha;
}

+ (id)availableRGBColorSpaces;
+ (id)colorWithNSColor:(id)arg1;
+ (id)colorWithRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
+ (id)colorWithSVGString:(id)arg1;
+ (id)namedColor:(id)arg1;
+ (id)rgbColorRed:(long long)arg1 green:(long long)arg2 blue:(long long)arg3;
+ (id)staticColorDictionary;
@property(nonatomic) double alpha; // @synthesize alpha=_alpha;
@property(nonatomic) double blue; // @synthesize blue=_blue;
- (id)colorWithAlphaComponent:(double)arg1;
@property(nonatomic) double green; // @synthesize green=_green;
- (id)hexValue;
@property(nonatomic) double red; // @synthesize red=_red;
- (id)stringValueWithAlpha:(BOOL)arg1;
- (id)stringValueWithAlpha:(BOOL)arg1 alphaMultiplication:(double)arg2;
- (id)svgRepresentation;

@end

