//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _AFURLSessionTaskSwizzling : NSObject
{
}

+ (void)load;
+ (void)swizzleResumeAndSuspendMethodForClass:(Class)arg1;
- (void)af_resume;
- (void)af_suspend;
- (long long)state;

@end

