//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSModelBase.h"

@interface _MSBaseGrid : MSModelBase
{
    BOOL _isEnabled;
}

- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (void)fillInEmptyObjects;
- (BOOL)hasDefaultValues;
- (id)immutableModelObject;
- (void)initEmptyObject;
@property(nonatomic) BOOL isEnabled; // @synthesize isEnabled=_isEnabled;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
- (BOOL)primitiveIsEnabled;
- (void)setAsParentOnChildren;
- (void)setPrimitiveIsEnabled:(BOOL)arg1;

@end

