//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSModelBase.h"

@interface _MSColor : MSModelBase
{
    double _alpha;
    double _blue;
    double _green;
    double _red;
}

@property(readonly, nonatomic) double alpha; // @synthesize alpha=_alpha;
@property(readonly, nonatomic) double blue; // @synthesize blue=_blue;
- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (void)fillInEmptyObjects;
@property(readonly, nonatomic) double green; // @synthesize green=_green;
- (BOOL)hasDefaultValues;
- (id)immutableModelObject;
- (void)initEmptyObject;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
- (double)primitiveAlpha;
- (double)primitiveBlue;
- (double)primitiveGreen;
- (double)primitiveRed;
@property(readonly, nonatomic) double red; // @synthesize red=_red;
- (void)setAlpha:(double)arg1;
- (void)setAsParentOnChildren;
- (void)setBlue:(double)arg1;
- (void)setGreen:(double)arg1;
- (void)setPrimitiveAlpha:(double)arg1;
- (void)setPrimitiveBlue:(double)arg1;
- (void)setPrimitiveGreen:(double)arg1;
- (void)setPrimitiveRed:(double)arg1;
- (void)setRed:(double)arg1;

@end

