//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSModelBase.h"

@interface _MSCurvePoint : MSModelBase
{
    BOOL _hasCurveFrom;
    BOOL _hasCurveTo;
    double _cornerRadius;
    long long _curveMode;
    struct CGPoint _curveFrom;
    struct CGPoint _curveTo;
    struct CGPoint _point;
}

- (void)copyPropertiesToObjectCopy:(id)arg1;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) struct CGPoint curveFrom; // @synthesize curveFrom=_curveFrom;
@property(nonatomic) long long curveMode; // @synthesize curveMode=_curveMode;
@property(nonatomic) struct CGPoint curveTo; // @synthesize curveTo=_curveTo;
- (void)decodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (void)fillInEmptyObjects;
@property(nonatomic) BOOL hasCurveFrom; // @synthesize hasCurveFrom=_hasCurveFrom;
@property(nonatomic) BOOL hasCurveTo; // @synthesize hasCurveTo=_hasCurveTo;
- (BOOL)hasDefaultValues;
- (id)immutableModelObject;
- (void)initEmptyObject;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
@property(nonatomic) struct CGPoint point; // @synthesize point=_point;
- (double)primitiveCornerRadius;
- (struct CGPoint)primitiveCurveFrom;
- (long long)primitiveCurveMode;
- (struct CGPoint)primitiveCurveTo;
- (BOOL)primitiveHasCurveFrom;
- (BOOL)primitiveHasCurveTo;
- (struct CGPoint)primitivePoint;
- (void)setAsParentOnChildren;
- (void)setPrimitiveCornerRadius:(double)arg1;
- (void)setPrimitiveCurveFrom:(struct CGPoint)arg1;
- (void)setPrimitiveCurveMode:(long long)arg1;
- (void)setPrimitiveCurveTo:(struct CGPoint)arg1;
- (void)setPrimitiveHasCurveFrom:(BOOL)arg1;
- (void)setPrimitiveHasCurveTo:(BOOL)arg1;
- (void)setPrimitivePoint:(struct CGPoint)arg1;

@end

