//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSModelBase.h"

@class NSString;

@interface _MSExportSize : MSModelBase
{
    NSString *_format;
    NSString *_name;
    double _scale;
    long long _visibleScaleType;
}


- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (void)fillInEmptyObjects;
@property(retain, nonatomic) NSString *format; // @synthesize format=_format;
- (BOOL)hasDefaultValues;
- (id)immutableModelObject;
- (void)initEmptyObject;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (id)primitiveFormat;
- (id)primitiveName;
- (double)primitiveScale;
- (long long)primitiveVisibleScaleType;
@property(nonatomic) double scale; // @synthesize scale=_scale;
- (void)setAsParentOnChildren;
- (void)setPrimitiveFormat:(id)arg1;
- (void)setPrimitiveName:(id)arg1;
- (void)setPrimitiveScale:(double)arg1;
- (void)setPrimitiveVisibleScaleType:(long long)arg1;
@property(nonatomic) long long visibleScaleType; // @synthesize visibleScaleType=_visibleScaleType;

@end

