//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSImmutableStylePart.h"

@interface _MSImmutableStyleReflection : MSImmutableStylePart
{
    double _distance;
    double _strength;
}

- (void)decodePropertiesWithCoder:(id)arg1;
@property(nonatomic) double distance; // @synthesize distance=_distance;
- (void)encodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (BOOL)hasDefaultValues;
- (id)initWithMutableModelObject:(id)arg1;
@property(nonatomic) double strength; // @synthesize strength=_strength;

@end

