//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSImmutableLayerGroup.h"

@class MSImmutableLayoutGrid, MSImmutableRulerData, MSImmutableSimpleGrid;

@interface _MSImmutablePage : MSImmutableLayerGroup
{
    struct CGPoint _scrollOrigin;
    double _zoomValue;
    MSImmutableSimpleGrid *_grid;
    MSImmutableRulerData *_horizontalRulerData;
    MSImmutableLayoutGrid *_layout;
    MSImmutableRulerData *_verticalRulerData;
}


- (void)decodePropertiesWithCoder:(id)arg1;
- (void)encodePropertiesWithCoder:(id)arg1;
@property(retain, nonatomic) MSImmutableSimpleGrid *grid; // @synthesize grid=_grid;
- (BOOL)hasDefaultValues;
@property(retain, nonatomic) MSImmutableRulerData *horizontalRulerData; // @synthesize horizontalRulerData=_horizontalRulerData;
- (id)initWithMutableModelObject:(id)arg1;
@property(retain, nonatomic) MSImmutableLayoutGrid *layout; // @synthesize layout=_layout;
@property(nonatomic) struct CGPoint scrollOrigin; // @synthesize scrollOrigin=_scrollOrigin;
@property(retain, nonatomic) MSImmutableRulerData *verticalRulerData; // @synthesize verticalRulerData=_verticalRulerData;
@property(nonatomic) double zoomValue; // @synthesize zoomValue=_zoomValue;

@end

