//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSImmutableModelBase.h"

@class NSString;

@interface _MSImmutableExportSize : MSImmutableModelBase
{
    NSString *_format;
    NSString *_name;
    double _scale;
    long long _visibleScaleType;
}


- (void)decodePropertiesWithCoder:(id)arg1;
- (void)encodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSString *format; // @synthesize format=_format;
- (BOOL)hasDefaultValues;
- (id)initWithMutableModelObject:(id)arg1;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) double scale; // @synthesize scale=_scale;
@property(nonatomic) long long visibleScaleType; // @synthesize visibleScaleType=_visibleScaleType;

@end

