//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSImmutableCustomShapeLayer.h"

@interface _MSImmutableRectangleShape : MSImmutableCustomShapeLayer
{
    double _fixedRadius;
    BOOL _hasConvertedToNewRoundCorners;
}

- (void)decodePropertiesWithCoder:(id)arg1;
- (void)encodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
@property(nonatomic) double fixedRadius; // @synthesize fixedRadius=_fixedRadius;
@property(nonatomic) BOOL hasConvertedToNewRoundCorners; // @synthesize hasConvertedToNewRoundCorners=_hasConvertedToNewRoundCorners;
- (BOOL)hasDefaultValues;
- (id)initWithMutableModelObject:(id)arg1;

@end

