//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSImmutableModelBase.h"

@class MSImmutableArray;

@interface _MSImmutableExportOptions : MSImmutableModelBase
{
    MSImmutableArray *_includedLayerIds;
    unsigned long long _layerOptions;
    BOOL _shouldTrim;
    MSImmutableArray *_sizes;
}


- (void)decodePropertiesWithCoder:(id)arg1;
- (void)encodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (BOOL)hasDefaultValues;
@property(retain, nonatomic) MSImmutableArray *includedLayerIds; // @synthesize includedLayerIds=_includedLayerIds;
- (id)initWithMutableModelObject:(id)arg1;
@property(nonatomic) unsigned long long layerOptions; // @synthesize layerOptions=_layerOptions;
@property(nonatomic) BOOL shouldTrim; // @synthesize shouldTrim=_shouldTrim;
@property(retain, nonatomic) MSImmutableArray *sizes; // @synthesize sizes=_sizes;

@end

