//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSModelBase.h"

@class MSBorderStyleCollection, MSFillStyleCollection, MSGraphicsContextSettings, MSInnerShadowStyleCollection, MSShadowStyleCollection, MSStyleBlur, MSStyleBorderOptions, MSStyleColorControls, MSStyleReflection, MSTextStyle, NSString;

@interface _MSStyle : MSModelBase
{
    MSBorderStyleCollection *_borders;
    unsigned long long _endDecorationType;
    MSFillStyleCollection *_fills;
    MSInnerShadowStyleCollection *_innerShadows;
    long long _miterLimit;
    MSShadowStyleCollection *_shadows;
    NSString *_sharedObjectID;
    unsigned long long _startDecorationType;
    MSStyleBlur *_blur;
    MSStyleBorderOptions *_borderOptions;
    MSStyleColorControls *_colorControls;
    MSGraphicsContextSettings *_contextSettings;
    MSStyleReflection *_reflection;
    MSTextStyle *_textStyle;
}


@property(retain, nonatomic) MSStyleBlur *blur; // @synthesize blur=_blur;
@property(retain, nonatomic) MSStyleBorderOptions *borderOptions; // @synthesize borderOptions=_borderOptions;
@property(retain, nonatomic) MSBorderStyleCollection *borders; // @synthesize borders=_borders;
@property(retain, nonatomic) MSStyleColorControls *colorControls; // @synthesize colorControls=_colorControls;
@property(retain, nonatomic) MSGraphicsContextSettings *contextSettings; // @synthesize contextSettings=_contextSettings;
- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
@property(nonatomic) unsigned long long endDecorationType; // @synthesize endDecorationType=_endDecorationType;
- (void)fillInEmptyObjects;
@property(retain, nonatomic) MSFillStyleCollection *fills; // @synthesize fills=_fills;
- (BOOL)hasDefaultValues;
- (id)immutableModelObject;
- (void)initEmptyObject;
@property(retain, nonatomic) MSInnerShadowStyleCollection *innerShadows; // @synthesize innerShadows=_innerShadows;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
@property(nonatomic) long long miterLimit; // @synthesize miterLimit=_miterLimit;
- (id)primitiveBlur;
- (id)primitiveBorderOptions;
- (id)primitiveBorders;
- (id)primitiveColorControls;
- (id)primitiveContextSettings;
- (unsigned long long)primitiveEndDecorationType;
- (id)primitiveFills;
- (id)primitiveInnerShadows;
- (long long)primitiveMiterLimit;
- (id)primitiveReflection;
- (id)primitiveShadows;
- (id)primitiveSharedObjectID;
- (unsigned long long)primitiveStartDecorationType;
- (id)primitiveTextStyle;
@property(retain, nonatomic) MSStyleReflection *reflection; // @synthesize reflection=_reflection;
- (void)setAsParentOnChildren;
- (void)setPrimitiveBlur:(id)arg1;
- (void)setPrimitiveBorderOptions:(id)arg1;
- (void)setPrimitiveBorders:(id)arg1;
- (void)setPrimitiveColorControls:(id)arg1;
- (void)setPrimitiveContextSettings:(id)arg1;
- (void)setPrimitiveEndDecorationType:(unsigned long long)arg1;
- (void)setPrimitiveFills:(id)arg1;
- (void)setPrimitiveInnerShadows:(id)arg1;
- (void)setPrimitiveMiterLimit:(long long)arg1;
- (void)setPrimitiveReflection:(id)arg1;
- (void)setPrimitiveShadows:(id)arg1;
- (void)setPrimitiveSharedObjectID:(id)arg1;
- (void)setPrimitiveStartDecorationType:(unsigned long long)arg1;
- (void)setPrimitiveTextStyle:(id)arg1;
@property(retain, nonatomic) MSShadowStyleCollection *shadows; // @synthesize shadows=_shadows;
@property(retain, nonatomic) NSString *sharedObjectID; // @synthesize sharedObjectID=_sharedObjectID;
@property(nonatomic) unsigned long long startDecorationType; // @synthesize startDecorationType=_startDecorationType;
@property(retain, nonatomic) MSTextStyle *textStyle; // @synthesize textStyle=_textStyle;

@end

