//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSLayerGroup.h"

@interface _MSShapeGroup : _MSLayerGroup <MSLayerGroup>
{
    BOOL _hasClippingMask;
    long long _clippingMaskMode;
    unsigned long long _windingRule;
}

@property(nonatomic) long long clippingMaskMode; // @synthesize clippingMaskMode=_clippingMaskMode;
- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
- (void)fillInEmptyObjects;
@property(nonatomic) BOOL hasClippingMask; // @synthesize hasClippingMask=_hasClippingMask;
- (BOOL)hasDefaultValues;
- (id)immutableModelObject;
- (void)initEmptyObject;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
- (long long)primitiveClippingMaskMode;
- (BOOL)primitiveHasClippingMask;
- (unsigned long long)primitiveWindingRule;
- (void)setAsParentOnChildren;
- (void)setPrimitiveClippingMaskMode:(long long)arg1;
- (void)setPrimitiveHasClippingMask:(BOOL)arg1;
- (void)setPrimitiveWindingRule:(unsigned long long)arg1;
@property(nonatomic) unsigned long long windingRule; // @synthesize windingRule=_windingRule;

@end

