//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSLayer.h"

@class MSStyle;

@interface _MSStyledLayer : MSLayer
{
    MSStyle *_style;
}


- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (void)fillInEmptyObjects;
- (BOOL)hasDefaultValues;
- (id)immutableModelObject;
- (void)initEmptyObject;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
- (id)primitiveStyle;
- (void)setAsParentOnChildren;
- (void)setPrimitiveStyle:(id)arg1;
@property(retain, nonatomic) MSStyle *style; // @synthesize style=_style;

@end

