//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSModelBase.h"

@class NSDictionary;

@interface _MSTextStyle : MSModelBase
{
    NSDictionary *_attributes;
}


@property(copy, nonatomic) NSDictionary *attributes; // @synthesize attributes=_attributes;
- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (void)fillInEmptyObjects;
- (BOOL)hasDefaultValues;
- (id)immutableModelObject;
- (void)initEmptyObject;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
- (id)primitiveAttributes;
- (void)setAsParentOnChildren;
- (void)setPrimitiveAttributes:(id)arg1;

@end

