//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SVGDrawableElement.h"

@class SVGElement;

@interface _SVGLink : SVGDrawableElement
{
    SVGElement *_link;
}

+ (id)attributeNames;
+ (id)propertyNames;
+ (id)relationshipNames;

@property(retain, nonatomic) SVGElement *link; // @synthesize link=_link;
- (void)primitiveSetLink:(id)arg1;

@end

