//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BCBonjourListener : NSObject
{
    int _port;
    CDUnknownBlockType _handler;
    struct __CFSocket *_socket4;
    struct __CFRunLoopSource *_source4;
    struct __CFSocket *_socket6;
    struct __CFRunLoopSource *_source6;
}


- (void)acceptConnectionFromAddress:(struct __CFData *)arg1 onSocket:(int)arg2;
- (void)dealloc;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
- (id)initWithConnectionHandler:(CDUnknownBlockType)arg1;
- (struct __CFRunLoopSource *)newRunLoopSourceForSocket:(struct __CFSocket *)arg1;
- (struct __CFSocket *)newSocket:(id *)arg1 ip4:(BOOL)arg2 source:(struct __CFRunLoopSource **)arg3;
@property(nonatomic) int port; // @synthesize port=_port;
@property(nonatomic) struct __CFSocket *socket4; // @synthesize socket4=_socket4;
@property(nonatomic) struct __CFSocket *socket6; // @synthesize socket6=_socket6;
@property(nonatomic) struct __CFRunLoopSource *source4; // @synthesize source4=_source4;
@property(nonatomic) struct __CFRunLoopSource *source6; // @synthesize source6=_source6;
- (BOOL)start:(id *)arg1;
- (void)stop;

@end

