//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BCBonjourDelegateHandler : NSObject
{
    id _delegate;
}


@property(retain, nonatomic) id delegate; // @synthesize delegate=_delegate;
- (void)handleCommand:(id)arg1 message:(id)arg2 receiver:(id)arg3;
- (id)initWithDelegate:(id)arg1;

@end

