//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSControl.h"

@interface BCColorPickerBaseView : NSControl
{
    id _bc_target;
    SEL _bc_action;
}

+ (id)darkShadow;
+ (void)drawFrameInRect:(struct CGRect)arg1 block:(CDUnknownBlockType)arg2;
+ (id)lightShadow;

- (BOOL)acceptsFirstMouse:(id)arg1;
- (SEL)action;
@property SEL bc_action; // @synthesize bc_action=_bc_action;
@property(nonatomic) __weak id bc_target; // @synthesize bc_target=_bc_target;
- (struct CGRect)contentBounds;
- (void)drawCheckerboardPatternInRect:(struct CGRect)arg1;
- (void)drawContentInRect:(struct CGRect)arg1 dirtyRect:(struct CGRect)arg2;
- (void)drawMarkerInRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initInBounds:(struct CGRect)arg1;
- (id)markerShadow;
- (void)setAction:(SEL)arg1;
- (void)setTarget:(id)arg1;
- (id)target;
- (id)undoManager;

@end

