//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSControl.h"

@class BCAlphaColorPicker, BCColorPreview, BCHueColorPicker, BCMagnifierButton, BCSaturationBrightnessColorPicker, MSColor, NSTextField;

@interface BCHSBColorPicker : NSControl
{
    BCSaturationBrightnessColorPicker *sbPickerView;
    BCHueColorPicker *hPickerView;
    BCAlphaColorPicker *aPickerView;
    BCColorPreview *colorPreviewView;
    BCMagnifierButton *magnifierButton;
    NSTextField *redComponentTextField;
    NSTextField *greenComponentTextField;
    NSTextField *blueComponentTextField;
    NSTextField *hueComponentTextField;
    NSTextField *satComponentTextField;
    NSTextField *ligComponentTextField;
    NSTextField *alphaComponentTextField;
    NSTextField *hexValueTextField;
    long long ignoreColorActionsCounter;
    id _bc_target;
    SEL _bc_action;
}


- (SEL)action;
- (void)alphaChanged:(id)arg1;
- (void)awakeFromNib;
@property SEL bc_action; // @synthesize bc_action=_bc_action;
@property(nonatomic) __weak id bc_target; // @synthesize bc_target=_bc_target;
@property(copy, nonatomic) MSColor *color; // @dynamic color;
- (void)constructSubviews;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (id)flexibleColor;
- (void)frequentColorPicked:(id)arg1;
- (void)hexValueFieldChanged:(id)arg1;
- (void)hslComponentFieldsChanged:(id)arg1;
- (void)hueChanged:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)magnifierAction:(id)arg1;
- (void)rgbComponentFieldsChanged:(id)arg1;
- (void)saturationBrightnessChanged:(id)arg1;
- (BOOL)sendAction:(SEL)arg1 to:(id)arg2;
- (void)setAction:(SEL)arg1;
- (void)setColor:(id)arg1 ignoringFields:(id)arg2;
- (void)setFrequentColors:(id)arg1;
- (void)setTarget:(id)arg1;
- (void)systemColorPanelDidChangeColor:(id)arg1;
- (id)target;
- (void)updateColorPreviewView;

@end

