//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@class BCCollapsableImageView, NSButton, NSDictionary, NSLayoutConstraint, NSPopUpButton;

@interface BCTableCellView : NSTableCellView
{
    BOOL _fakeSelection;
    BOOL _isPreviewImageDirty;
    BOOL _currentSelectedState;
    id <BCTableCellViewDelegate> _delegate;
    unsigned long long _displayState;
    NSButton *_badgeButton;
    NSPopUpButton *_popupBadgeButton;
    BCCollapsableImageView *_previewView;
    NSDictionary *_previewImages;
    BCCollapsableImageView *_secondaryPreviewView;
    NSLayoutConstraint *_badgeTrailingSpaceConstraint;
}


@property(nonatomic) __weak NSButton *badgeButton; // @synthesize badgeButton=_badgeButton;
@property(nonatomic) __weak NSLayoutConstraint *badgeTrailingSpaceConstraint; // @synthesize badgeTrailingSpaceConstraint=_badgeTrailingSpaceConstraint;
@property(nonatomic) BOOL currentSelectedState; // @synthesize currentSelectedState=_currentSelectedState;
- (void)dealloc;
@property(nonatomic) __weak id <BCTableCellViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long displayState; // @synthesize displayState=_displayState;
- (void)drawDragImageInRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawTextFieldBorder;
@property(nonatomic) BOOL fakeSelection; // @synthesize fakeSelection=_fakeSelection;
- (void)handleBadgePressed:(id)arg1;
- (void)internalRefreshPreviewImages;
- (BOOL)isEventCurrent:(id)arg1;
@property(readonly, nonatomic, getter=isNodeSelected) BOOL nodeSelected;
@property(nonatomic) BOOL isPreviewImageDirty; // @synthesize isPreviewImageDirty=_isPreviewImageDirty;
@property(readonly, nonatomic) BOOL isTextFieldEditing;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
@property(readonly, nonatomic) id <BCOutlineViewNode> node;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(nonatomic) __weak NSPopUpButton *popupBadgeButton; // @synthesize popupBadgeButton=_popupBadgeButton;
- (void)prepareForReuse;
@property(retain, nonatomic) NSDictionary *previewImages; // @synthesize previewImages=_previewImages;
@property(nonatomic) __weak BCCollapsableImageView *previewView; // @synthesize previewView=_previewView;
- (void)refreshPreviewImages;
- (void)renameNode;
@property(nonatomic) __weak BCCollapsableImageView *secondaryPreviewView; // @synthesize secondaryPreviewView=_secondaryPreviewView;
- (void)setBackgroundStyle:(long long)arg1;
- (void)setObjectValue:(id)arg1;
- (void)startObserving;
- (void)stopObserving;
- (void)updateBadge;
- (void)updateBadgeImages;
- (void)updatePreview;
- (void)updateSecondaryPreview;
- (void)updateTextColour;
@property(readonly, nonatomic) double widthForDragImage;

@end

