//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@interface CHSheetController : NSWindowController
{
    id _object;
    id _delegate;
}

+ (void)initialize;
+ (id)run;
+ (id)runForWindow:(id)arg1;
+ (id)runForWindow:(id)arg1 withObject:(id)arg2;
+ (id)runForWindow:(id)arg1 withObject:(id)arg2 delegate:(id)arg3;
+ (id)runWithObject:(id)arg1;

- (id)_init;
- (void)_sheetDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)cancel:(id)arg1;
- (void)closeSheet;
- (void)confirm:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id object; // @synthesize object=_object;
- (id)windowNibName;

@end

