//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSMutableDictionary;

@interface ECLogManager : NSObject
{
    BOOL _showMenu;
    NSMutableDictionary *_channels;
    NSMutableDictionary *_handlers;
    NSMutableArray *_defaultHandlers;
    unsigned long long _defaultContextFlags;
    NSMutableDictionary *_settings;
    id <ECLogManagerDelegate> _delegate;
    NSArray *_handlersSorted;
}

+ (id)sharedInstance;

- (void)applySettings:(id)arg1 toChannel:(id)arg2;
@property(retain, nonatomic) NSMutableDictionary *channels; // @synthesize channels=_channels;
- (id)channelsSortedByName;
- (unsigned long long)contextFlagCount;
- (id)contextFlagNameForIndex:(unsigned long long)arg1;
- (unsigned long long)contextFlagValueForIndex:(unsigned long long)arg1;
@property(nonatomic) unsigned long long defaultContextFlags; // @synthesize defaultContextFlags=_defaultContextFlags;
@property(retain, nonatomic) NSMutableArray *defaultHandlers; // @synthesize defaultHandlers=_defaultHandlers;
- (id)defaultSettings;
@property(nonatomic) __weak id <ECLogManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)disableAllChannels;
- (void)enableAllChannels;
- (unsigned long long)expectedSettingsVersionWithDefaultSettings:(id)arg1;
- (void)finishStartup;
- (void)handler:(id)arg1 setDefault:(BOOL)arg2;
- (unsigned long long)handlerCount;
- (id)handlerForIndex:(unsigned long long)arg1;
- (BOOL)handlerIsDefault:(id)arg1;
- (id)handlerNameForIndex:(unsigned long long)arg1;
@property(retain, nonatomic) NSMutableDictionary *handlers; // @synthesize handlers=_handlers;
@property(retain, nonatomic) NSArray *handlersSorted; // @synthesize handlersSorted=_handlersSorted;
- (id)handlersSortedByName;
- (id)init;
- (void)loadChannelSettings;
- (void)loadSettings;
- (void)logFromChannel:(id)arg1 withObject:(id)arg2 arguments:(struct __va_list_tag [1])arg3 context:(CDStruct_5b5d1a5d *)arg4;
- (void)notifyDelegateOfStartup;
- (id)optionsSettings;
- (void)postUpdateNotification;
- (void)processForcedChannels;
- (id)registerChannel:(id)arg1;
- (id)registerChannelWithName:(id)arg1 options:(id)arg2;
- (id)registerChannelWithRawName:(const char *)arg1 options:(id)arg2;
- (void)registerHandlers;
- (void)resetAllChannels;
- (void)resetAllSettings;
- (void)resetChannel:(id)arg1;
- (void)saveChannelSettings;
@property(retain, nonatomic) NSMutableDictionary *settings; // @synthesize settings=_settings;
@property(nonatomic) BOOL showMenu; // @synthesize showMenu=_showMenu;
- (id)settingsFromBundle:(id)arg1;
- (void)shutdown;
- (void)startup;

@end

