//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ECLogHandler : NSObject
{
    NSString *_name;
}


- (long long)caseInsensitiveCompare:(id)arg1;
- (void)logFromChannel:(id)arg1 withObject:(id)arg2 arguments:(struct __va_list_tag [1])arg3 context:(CDStruct_5b5d1a5d *)arg4;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (id)simpleOutputStringForChannel:(id)arg1 withObject:(id)arg2 arguments:(struct __va_list_tag [1])arg3 context:(CDStruct_5b5d1a5d *)arg4;
- (void)wasDisabledForChannel:(id)arg1;
- (void)wasEnabledForChannel:(id)arg1;

@end

