//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBBezierContour, NSArray, NSMutableArray;

@interface FBEdgeOverlapRun : NSObject
{
    NSMutableArray *_overlaps;
}

+ (id)overlapRun;

- (void)addCrossings;
@property(readonly, nonatomic) FBBezierContour *contour1;
@property(readonly, nonatomic) FBBezierContour *contour2;
- (id)description;
- (BOOL)doesContainCrossing:(id)arg1;
- (BOOL)doesContainParameter:(double)arg1 onEdge:(id)arg2;
- (id)init;
- (BOOL)insertOverlap:(id)arg1;
- (BOOL)isComplete;
- (BOOL)isCrossing;
- (BOOL)isCrossingUsingNonZeroWindingRule;
- (BOOL)isCrossingWithTangentsOnly;
- (id)middleIntersection;
@property(readonly, nonatomic) NSArray *overlaps; // @synthesize overlaps=_overlaps;

@end

