//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface MSActionsController : NSObject
{
    NSString *_actionNameForActiveToolbarItem;
    NSMutableDictionary *_actions;
}


- (id)actionClasses;
@property(copy, nonatomic) NSString *actionNameForActiveToolbarItem; // @synthesize actionNameForActiveToolbarItem=_actionNameForActiveToolbarItem;
- (id)actionWithName:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *actions; // @synthesize actions=_actions;
- (id)allActions;
- (void)createActionsForDocument:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)init;

@end

