//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class MSAssetCollection, NSIndexSet;

@interface MSAssetPickerView : NSView
{
    long long sourceDragIndex;
    id <MSPresetPickerViewDelegate> _delegate;
    double _tileMargin;
    double _edgeMargin;
    unsigned long long _hoveringIndex;
    NSIndexSet *_currentIndexes;
    MSAssetCollection *_assetCollection;
    unsigned long long _assetType;
    struct CGSize _tileSize;
}


- (void)addPreset;
- (void)addPreset:(id)arg1;
- (id)addPresetButtonWithOffset:(struct CGPoint)arg1;
@property(retain, nonatomic) MSAssetCollection *assetCollection; // @synthesize assetCollection=_assetCollection;
@property(nonatomic) unsigned long long assetType; // @synthesize assetType=_assetType;
- (BOOL)canDragFromIndex:(unsigned long long)arg1;
- (long long)columnCount;
@property(copy, nonatomic) NSIndexSet *currentIndexes; // @synthesize currentIndexes=_currentIndexes;
@property(nonatomic) __weak id <MSPresetPickerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (BOOL)delegateDidDragPresetToIndex:(unsigned long long)arg1;
- (void)delegateDrawContentInRect:(struct CGRect)arg1 tag:(unsigned long long)arg2;
- (BOOL)delegateDrawFullContentInRect:(struct CGRect)arg1 index:(unsigned long long)arg2;
- (BOOL)delegateInsertPresetFromPasteboardData:(id)arg1 atIndex:(unsigned long long)arg2;
- (unsigned long long)delegateNumberOfPresets;
- (void)delegatePickPresetAtIndex:(unsigned long long)arg1;
- (void)delegateRemovePresetAtIndex:(unsigned long long)arg1;
- (BOOL)delegateShouldShowAddButton;
- (BOOL)delegateShowMenuForIndex:(unsigned long long)arg1;
- (BOOL)delegateSupportsDrop;
- (id)delegateTooltipForIndex:(unsigned long long)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (void)drawContentForButton:(id)arg1 inRect:(struct CGRect)arg2;
- (BOOL)drawFullContentForButton:(id)arg1 inRect:(struct CGRect)arg2;
- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) double edgeMargin; // @synthesize edgeMargin=_edgeMargin;
- (long long)hoverIndexForDraggingInfo:(id)arg1;
@property(nonatomic) unsigned long long hoveringIndex; // @synthesize hoveringIndex=_hoveringIndex;
- (struct MSPresetIteratorStruct)incrementIterator:(struct MSPresetIteratorStruct)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)isFlipped;
- (BOOL)isInStackView;
- (void)moveDraggedViewToRowAtIndex:(long long)arg1;
- (struct MSPresetIteratorStruct)newIterator;
- (BOOL)performDragOperation:(id)arg1;
- (void)pickPresetForButton:(id)arg1;
- (id)presetButtonForIndex:(unsigned long long)arg1 withOffset:(struct CGPoint)arg2;
- (void)reloadData;
- (void)removePresetForButton:(id)arg1;
- (void)removePresetWithTag:(long long)arg1;
- (void)setFrame:(struct CGRect)arg1;
@property(nonatomic) double tileMargin; // @synthesize tileMargin=_tileMargin;
@property(nonatomic) struct CGSize tileSize; // @synthesize tileSize=_tileSize;
- (BOOL)shouldShowMenuForButton:(id)arg1;
- (void)stackIfPossible;

@end

