//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MSEventHandlerManager;

@interface MSBaseView : NSView


- (void)dealloc;
- (void)didUndoNotification:(id)arg1;
@property(retain, nonatomic) MSEventHandlerManager *eventHandlerManager; // @synthesize eventHandlerManager=_eventHandlerManager;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)initialize;
- (BOOL)isFlipped;
- (void)removeFromSuperview;
@property(nonatomic) struct CGPoint scrollOrigin; // @dynamic scrollOrigin;
- (void)setOutletsToNil;
- (void)setViewPort:(id)arg1;
@property(nonatomic) double zoomValue; // @dynamic zoomValue;
- (void)userDefaultsDidChange:(id)arg1;
- (id)viewPort;
- (void)willUndoNotification:(id)arg1;

@end

