//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSRenderingContext, MSShapeGroup, NSBezierPath;

@interface MSBackgroundBlurRenderer : NSObject
{
    MSRenderingContext *_context;
    MSShapeGroup *_layer;
    NSBezierPath *_path;
}

+ (void)blurBackgroundBehindLayer:(id)arg1 path:(id)arg2 context:(id)arg3;

- (struct CGRect)absoluteRectForLayer:(id)arg1 context:(id)arg2;
- (id)blur;
- (void)blurBackgroundWithContext:(id)arg1;
@property(nonatomic) __weak MSRenderingContext *context; // @synthesize context=_context;
@property(retain, nonatomic) MSShapeGroup *layer; // @synthesize layer=_layer;
@property(retain, nonatomic) NSBezierPath *path; // @synthesize path=_path;
- (void)renderCanvasImageInRect:(struct CGRect)arg1 context:(struct CGContext *)arg2;

@end

