//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSColor, NSString;

@interface MSColorCounter : NSObject
{
    MSColor *_color;
    unsigned long long _fillCount;
    unsigned long long _borderCount;
    unsigned long long _shadowCount;
    unsigned long long _textCount;
}

+ (void)initialize;

@property(nonatomic) unsigned long long borderCount; // @synthesize borderCount=_borderCount;
@property(retain, nonatomic) MSColor *color; // @synthesize color=_color;
- (long long)compare:(id)arg1;
- (void)countSource:(id)arg1;
@property(nonatomic) unsigned long long fillCount; // @synthesize fillCount=_fillCount;
@property(nonatomic) unsigned long long shadowCount; // @synthesize shadowCount=_shadowCount;
@property(nonatomic) unsigned long long textCount; // @synthesize textCount=_textCount;
@property(readonly, nonatomic) NSString *title;
@property(readonly, nonatomic) unsigned long long totalCount;

@end

