//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@class MSStyleBasicFill, NSColor;

@interface MSColorPreviewButton : NSButton
{
    MSStyleBasicFill *_basicFill;
    NSColor *_color;
    id _dragOwner;
}


@property(retain, nonatomic) MSStyleBasicFill *basicFill; // @synthesize basicFill=_basicFill;
- (id)borderColor;
@property(copy, nonatomic) NSColor *color; // @synthesize color=_color;
- (struct CGRect)colorFrame;
@property(nonatomic) __weak id dragOwner; // @synthesize dragOwner=_dragOwner;
- (void)drawBasicFillInRect:(struct CGRect)arg1;
- (void)drawButton;
- (void)drawColorFillInRect:(struct CGRect)arg1;
- (void)drawGradientFillInRect:(struct CGRect)arg1;
- (void)drawNoiseFillInRect:(struct CGRect)arg1;
- (void)drawPatternFillInRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)fillColor;
- (id)innerBorderColor;
- (BOOL)isFlipped;
- (void)mouseDown:(id)arg1;

@end

