//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDocumentController.h"

@interface MSDocumentController : NSDocumentController
{
}

- (void)noteNewRecentDocument:(id)arg1;
- (void)noteNewRecentDocumentURL:(id)arg1;
- (void)openDocumentWithContentsOfURL:(id)arg1 display:(BOOL)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (BOOL)shoudNoteRecentDocumentForType:(id)arg1;
- (id)typeForContentsOfURL:(id)arg1 error:(id *)arg2;

@end

