//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MSDotDrawing : NSObject
{
}

+ (double)dotSizeForType:(long long)arg1;
+ (void)drawAtPoint:(struct CGPoint)arg1 isSelected:(BOOL)arg2 color:(id)arg3;
+ (void)drawAtPoint:(struct CGPoint)arg1 ofType:(long long)arg2 isSelected:(BOOL)arg3 isHovering:(BOOL)arg4;
+ (void)drawAtPoint:(struct CGPoint)arg1 ofType:(long long)arg2 isSelected:(BOOL)arg3 isHovering:(BOOL)arg4 transformStruct:(struct _CHTransformStruct)arg5;
+ (void)drawBezier:(id)arg1;
+ (void)drawRectAtPoint:(struct CGPoint)arg1;
+ (void)drawShadowForHover:(BOOL)arg1 inBlock:(CDUnknownBlockType)arg2;
+ (id)gradient;
+ (void)load;
+ (void)resetZoomValue;
+ (void)setZoomValue:(double)arg1;
+ (id)shadowForHover:(BOOL)arg1;

@end

