//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BCUndoManager, MSEventHandler, MSNormalEventHandler;

@protocol MSEventHandlerManager

@optional

- (id)currentHandler;
- (id)currentHandlerKey;
- (id)defaultHandler;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (void)drawInRect:(struct CGRect)arg1;
- (id)handlerForKey:(id)arg1;
- (id)initWithDelegate:(id)arg1 undoManager:(id)arg2;
@property(nonatomic) unsigned long long lastEventType; // @synthesize lastEventType=_lastEventType;
@property(nonatomic) long long lastMouseDownClickCount; // @synthesize lastMouseDownClickCount=_lastMouseDownClickCount;
@property(retain, nonatomic) MSNormalEventHandler *normalHandler; // @synthesize normalHandler=_normalHandler;
- (void)recordEvent:(id)arg1;
@property(retain, nonatomic) MSEventHandler *secondHandler; // @synthesize secondHandler=_secondHandler;
- (void)sendMouseDownEvent:(id)arg1;
- (void)sendMouseDraggedEvent:(id)arg1;
- (void)sendMouseMovedEvent:(id)arg1;
- (void)sendMouseUpEvent:(id)arg1;
- (id)setCurrentHandler:(id)arg1;
- (id)setCurrentHandlerKey:(id)arg1;
@property(retain, nonatomic) BCUndoManager *undoManager; // @synthesize undoManager=_undoManager;
- (id)toggleHandlerKey:(id)arg1;

@end

@interface MSEventHandlerManager : NSObject <MSEventHandlerManager>

@end

