//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSExportSize.h"

@interface MSExportSize : _MSExportSize
{
}

+ (id)defaultNameForScale:(double)arg1;
+ (id)migrateExportSizesWithName:(id)arg1 currentResolution:(long long)arg2 includeRetinaVersion:(BOOL)arg3;
+ (id)sizeWithScale:(double)arg1 name:(id)arg2 format:(id)arg3;
+ (id)validFormats;
- (id)defaultName;
- (id)description;
- (id)initWithScale:(double)arg1 name:(id)arg2 format:(id)arg3;
- (BOOL)isScalableExport;
- (BOOL)isVectorExport;
- (id)parentLayer;
- (void)remove;

@end

