//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CHViewController.h"

@class NSArray, NSButton, NSComboBox, NSPopUpButton, NSView;

@interface MSExportSizeViewController : CHViewController
{
    NSPopUpButton *_formatPopup;
    NSButton *_removeSizeButton;
    NSView *_sizeView;
    NSView *_scaleView;
    NSArray *_exportSizes;
    NSComboBox *_scaleField;
}

+ (void)initialize;

- (void)applyScale:(double)arg1 toExportSize:(id)arg2 scaleType:(long long)arg3 normalSize:(struct CGSize)arg4;
- (BOOL)exportSizeCanBeScaled;
@property(retain, nonatomic) NSArray *exportSizes; // @synthesize exportSizes=_exportSizes;
- (void)findSizeOfLayer:(id)arg1 forScaleType:(long long)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)firstSize;
@property(retain, nonatomic) NSPopUpButton *formatPopup; // @synthesize formatPopup=_formatPopup;
- (void)formatPopupAction:(id)arg1;
- (void)prepare;
- (void)removeExportSize:(id)arg1;
@property(retain, nonatomic) NSButton *removeSizeButton; // @synthesize removeSizeButton=_removeSizeButton;
@property(retain, nonatomic) NSComboBox *scaleField; // @synthesize scaleField=_scaleField;
- (void)scaleFieldAction:(id)arg1;
@property(retain, nonatomic) NSView *scaleView; // @synthesize scaleView=_scaleView;
@property(retain, nonatomic) NSView *sizeView; // @synthesize sizeView=_sizeView;
- (double)sizeByRemovingSuffixes:(id)arg1;

@end

