//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSStylePartInspectorViewController.h"

@class MSColorPreviewButton, NSTextField<MSUpDownProtocol>;

@interface MSFillInspectorViewController : MSStylePartInspectorViewController
{
    MSColorPreviewButton *_colorButton;
    NSTextField<MSUpDownProtocol> *_opacityField;
}


@property(retain, nonatomic) MSColorPreviewButton *colorButton; // @synthesize colorButton=_colorButton;
- (void)dealloc;
@property(retain, nonatomic) NSTextField<MSUpDownProtocol> *opacityField; // @synthesize opacityField=_opacityField;
- (void)opacityFieldAction:(id)arg1;
- (void)prepare;

@end

