//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSGradientStop.h"

@interface MSGradientStop : _MSGradientStop
{
}

+ (id)stopWithPosition:(double)arg1 color:(id)arg2;
- (double)cappedBounds:(double)arg1;
- (id)initWithPosition:(double)arg1 color:(id)arg2;
- (void)setPosition:(double)arg1;

@end

