//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CHSheetController.h"

#import "NSWindowDelegate.h"

@class MSBaseGrid, NSMapTable, NSString;

@interface MSGridSheetBase : CHSheetController <NSWindowDelegate>
{
    NSMapTable *_originalSettings;
    MSBaseGrid *_templateObject;
}


- (void)applyObject:(id)arg1 toLayer:(id)arg2;
- (void)applyTemplateObjectToLayer:(id)arg1;
- (void)awakeFromNib;
- (id)buildApplicableRootLayerList;
- (id)cacheObjectForRootLayer:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)confirm:(id)arg1;
- (void)dealloc;
- (id)defaultObject;
- (void)gridChanged:(id)arg1;
@property(retain, nonatomic) NSMapTable *originalSettings; // @synthesize originalSettings=_originalSettings;
- (void)refreshCanvas:(id)arg1;
- (void)refreshView;
@property(copy, nonatomic) MSBaseGrid *templateObject; // @synthesize templateObject=_templateObject;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

