//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSImmutableStyleFill.h"

#import "MSImageOwner.h"

@class NSString;

@interface MSImmutableStyleFill : _MSImmutableStyleFill <MSImageOwner>
{
    double _parentLayerCachedOpacity;
}

- (id)NSImage;
- (void)initObjectWithCoder:(id)arg1;
- (id)initWithMutableModelObject:(id)arg1;
@property(nonatomic) double parentLayerCachedOpacity; // @synthesize parentLayerCachedOpacity=_parentLayerCachedOpacity;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

