//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MSLayerStylePreviewGenerator : NSObject
{
}

+ (struct CGRect)adjustDrawRect:(struct CGRect)arg1 forStyle:(id)arg2;
+ (void)generateImageForLayerStyle:(id)arg1 imageSize:(struct CGSize)arg2 completionBlock:(CDUnknownBlockType)arg3;
+ (id)previewForStyle:(id)arg1 atSize:(struct CGSize)arg2;

@end

