//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSLayoutGrid.h"

@class NSColor;

@interface MSLayoutGrid : _MSLayoutGrid
{
    NSColor *_lightColor;
    NSColor *_darkColor;
}


@property(retain, nonatomic) NSColor *darkColor; // @synthesize darkColor=_darkColor;
- (void)determineAppropriateColumnWidth;
- (void)drawColumnInRect:(struct CGRect)arg1 zoom:(double)arg2;
- (void)drawInRect:(struct CGRect)arg1 baseLine:(struct CGPoint)arg2 atZoom:(double)arg3;
- (void)drawRowInRect:(struct CGRect)arg1 zoom:(double)arg2;
- (id)horizontalGuidesForRulerData:(id)arg1 inRect:(struct CGRect)arg2;
@property(retain, nonatomic) NSColor *lightColor; // @synthesize lightColor=_lightColor;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setColumnWidth:(double)arg1;
- (void)setGutterWidth:(double)arg1;
- (void)setGuttersOutside:(BOOL)arg1;
- (void)setNumberOfColumns:(double)arg1;
- (void)setTotalWidth:(double)arg1;
- (BOOL)shouldDraw;
- (long long)totalNumberOfGutters;
- (id)verticalGuidesForRulerData:(id)arg1 inRect:(struct CGRect)arg2;

@end

