//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BCEmbeddedServerController, NSMutableArray, NSURL;

@interface MSLocalWebServer : NSObject
{
    BCEmbeddedServerController *_server;
    NSURL *_cacheRoot;
    NSURL *_documentsFolder;
    NSMutableArray *_mountedDocuments;
}


- (id)URLForDocument:(id)arg1;
@property(copy, nonatomic) NSURL *cacheRoot; // @synthesize cacheRoot=_cacheRoot;
- (void)doPublishDocument:(id)arg1 withName:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
@property(copy, nonatomic) NSURL *documentsFolder; // @synthesize documentsFolder=_documentsFolder;
- (id)init;
- (BOOL)isDocumentPublished:(id)arg1;
- (id)mountInfoForDocument:(id)arg1;
@property(retain, nonatomic) NSMutableArray *mountedDocuments; // @synthesize mountedDocuments=_mountedDocuments;
- (void)publishDocument:(id)arg1 withName:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)refreshLoop;
- (void)registerDocument:(id)arg1 locationOnDisk:(id)arg2 publicURL:(id)arg3 exporter:(id)arg4;
@property(retain, nonatomic) BCEmbeddedServerController *server; // @synthesize server=_server;
- (void)startRefreshingLoop;
- (void)startWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)stop;
- (void)togglePublishDocument:(id)arg1 withName:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)unpublishDocument:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)unpublishDocumentInfo:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;

@end

