//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CHSheetController.h"

@class MSDocument, NSButton, NSImageView, NSTextField;

@interface MSMakeGridSheet : CHSheetController
{
    BOOL _isBoxed;
    BOOL _hasHorizontalPadding;
    BOOL _hasVerticalPadding;
    MSDocument *_doc;
    long long _numberOfRows;
    long long _numberOfColumns;
    long long _horizontalPadding;
    long long _verticalPadding;
    long long _boxedWidth;
    long long _boxedHeight;
    long long _shouldFillHoles;
    NSImageView *_imageView;
    NSTextField *_subtextField;
    NSButton *_confirmButton;
}


- (void)awakeFromNib;
- (void)boxedAction:(id)arg1;
@property(nonatomic) long long boxedHeight; // @synthesize boxedHeight=_boxedHeight;
@property(nonatomic) long long boxedWidth; // @synthesize boxedWidth=_boxedWidth;
- (void)changeBoxedImage;
- (void)confirm:(id)arg1;
@property(nonatomic) __weak NSButton *confirmButton; // @synthesize confirmButton=_confirmButton;
- (struct CGSize)defaultBoxSize;
@property(retain, nonatomic) MSDocument *doc; // @synthesize doc=_doc;
@property(nonatomic) BOOL hasHorizontalPadding; // @synthesize hasHorizontalPadding=_hasHorizontalPadding;
@property(nonatomic) BOOL hasVerticalPadding; // @synthesize hasVerticalPadding=_hasVerticalPadding;
@property(nonatomic) long long horizontalPadding; // @synthesize horizontalPadding=_horizontalPadding;
@property(nonatomic) __weak NSImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) BOOL isBoxed; // @synthesize isBoxed=_isBoxed;
- (unsigned long long)layerCount;
- (BOOL)layersHaveSameSize;
@property(nonatomic) long long numberOfColumns; // @synthesize numberOfColumns=_numberOfColumns;
@property(nonatomic) long long numberOfRows; // @synthesize numberOfRows=_numberOfRows;
- (void)registerMarginDefaults;
- (void)setNilValueForKey:(id)arg1;
@property(nonatomic) long long shouldFillHoles; // @synthesize shouldFillHoles=_shouldFillHoles;
@property(nonatomic) __weak NSTextField *subtextField; // @synthesize subtextField=_subtextField;
@property(nonatomic) long long verticalPadding; // @synthesize verticalPadding=_verticalPadding;
- (void)validatePaddingFields;

@end

