//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSBaseMoveBackwardAction.h"

@interface MSMoveToBackAction : MSBaseMoveBackwardAction
{
}

- (void)doPerformAction:(id)arg1;
- (void)moveToBack:(id)arg1;

@end

