//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDictionary;

@interface MSModelFileHeader : NSObject <NSCoding>
{
    long long _version;
    NSDictionary *_metadata;
    id _root;
}

+ (id)latestMetadata;

- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) NSDictionary *metadata; // @synthesize metadata=_metadata;
@property(retain, nonatomic) id root; // @synthesize root=_root;
@property(nonatomic) long long version; // @synthesize version=_version;

@end

