//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CHSingletonObject.h"

@class NSURLSession, NSWindowController;

@interface MSNewsTrigger : CHSingletonObject
{
    NSURLSession *_urlSession;
    NSWindowController *_windowController;
}

+ (void)checkForNews;

- (void)checkForNews;
- (id)init;
@property(retain, nonatomic) NSURLSession *urlSession; // @synthesize urlSession=_urlSession;
@property(retain, nonatomic) NSWindowController *windowController; // @synthesize windowController=_windowController;
- (BOOL)shouldShowNewsWithID:(id)arg1;
- (void)showURL:(id)arg1 newsID:(id)arg2;
- (id)url;
- (void)validateResult:(id)arg1;

@end

