//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSButton, NSString, NSURL, WebView;

@interface MSNewsTriggerWindowController : NSWindowController
{
    BOOL _finishedLoadingData;
    NSURL *_url;
    NSString *_newsID;
    WebView *_webView;
    NSButton *_dontShowAgainButton;
}


- (void)close:(id)arg1;
- (void)dealloc;
@property(nonatomic) NSButton *dontShowAgainButton; // @synthesize dontShowAgainButton=_dontShowAgainButton;
- (void)dontShowNewsWithIDAnymore:(id)arg1;
@property(nonatomic) BOOL finishedLoadingData; // @synthesize finishedLoadingData=_finishedLoadingData;
- (id)initWithURL:(id)arg1 newsID:(id)arg2;
@property(copy, nonatomic) NSString *newsID; // @synthesize newsID=_newsID;
@property(copy, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic) WebView *webView; // @synthesize webView=_webView;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5;
- (void)webView:(id)arg1 didFinishLoadForFrame:(id)arg2;
- (id)webView:(id)arg1 resource:(id)arg2 willSendRequest:(id)arg3 redirectResponse:(id)arg4 fromDataSource:(id)arg5;
- (void)windowDidLoad;

@end

