//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSURL;

@interface MSPluginManager : NSObject
{
    NSDictionary *_plugins;
    NSURL *_pluginsFolderURL;
    NSURL *_metadataURL;
    char *_useLegacyPlugins;
    NSDictionary *_metadata;
    NSArray *_folderMonitors;
}

+ (void)initialisePlugins;
+ (id)pluginsURL;

- (void)addCommands:(id)arg1 toMenu:(id)arg2 fromDescription:(id)arg3 selector:(SEL)arg4;
- (void)addPluginsToMenu:(id)arg1 selector:(SEL)arg2 includeLegacyPlugins:(BOOL)arg3;
- (id)commandWithSpecifier:(id)arg1;
- (BOOL)disablePlugin:(id)arg1;
- (BOOL)enablePlugin:(id)arg1;
@property(retain, nonatomic) NSArray *folderMonitors; // @synthesize folderMonitors=_folderMonitors;
- (id)initWithPluginsFolderURL:(id)arg1 metadataURL:(id)arg2;
- (id)legacyPluginMenuDescriptionWithRelativePath:(id)arg1 commandIdentifier:(id)arg2;
@property(copy, nonatomic) NSDictionary *metadata; // @synthesize metadata=_metadata;
@property(copy, nonatomic) NSURL *metadataURL; // @synthesize metadataURL=_metadataURL;
- (id)metadataValueForKey:(id)arg1 identifier:(id)arg2;
@property(copy, nonatomic) NSDictionary *plugins;
@property(readonly, copy, nonatomic) NSURL *pluginsFolderURL; // @synthesize pluginsFolderURL=_pluginsFolderURL;
- (id)pluginsFromFolderAtURL:(id)arg1 visitedURLs:(id)arg2 relativeFolderPath:(id)arg3;
- (id)relativePathByDeletingCommonPathComponentsWithFileURL:(id)arg1 fromURL:(id)arg2;
- (void)reloadPlugins;
- (BOOL)setMetadataValue:(id)arg1 forKey:(id)arg2 identifier:(id)arg3;
@property(nonatomic) char *useLegacyPlugins; // @synthesize useLegacyPlugins=_useLegacyPlugins;
- (void)sortMenu:(id)arg1 recursively:(BOOL)arg2;

@end

