//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSGradientEventHandler.h"

@interface MSRadialGradientEventHandler : MSGradientEventHandler
{
    BOOL ellipseSelected;
    struct CGSize deltaBetweenRadialPointBeforeDrag;
}

- (BOOL)absoluteMouseDown:(struct CGPoint)arg1 clickCount:(unsigned long long)arg2 flags:(unsigned long long)arg3;
- (BOOL)absoluteMouseDragged:(struct CGPoint)arg1 flags:(unsigned long long)arg2;
- (BOOL)absoluteMouseMoved:(struct CGPoint)arg1 flags:(unsigned long long)arg2;
- (void)drawInRect:(struct CGRect)arg1;
- (struct CGPoint)ellipsePoint;
- (BOOL)hasSelectedPoint;
- (void)markLayerDirtyOfType:(unsigned long long)arg1;
- (BOOL)mouseIsNearEllipsePoint:(struct CGPoint)arg1;
- (BOOL)mouseUp:(struct CGPoint)arg1 flags:(unsigned long long)arg2;
- (id)ovalPath;
- (void)refreshOval;
- (void)replacePointAtIndex:(long long)arg1 withPoint:(struct CGPoint)arg2;
- (void)setEllipsePoint:(struct CGPoint)arg1;

@end

