//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSRect;

@protocol MSRectDelegate <NSObject>
- (void)rectDidChange:(MSRect *)arg1 fromRect:(struct CGRect)arg2;
@end

