//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSReorderingContainerView;

@protocol MSReorderingContainerDelegate <NSObject>
- (void)containerBackground:(MSReorderingContainerView *)arg1 dragDidReorderChildAtIndex:(unsigned long long)arg2 toIndex:(unsigned long long)arg3;

@optional
- (unsigned long long)numberOfReorderableSubviewsForContainerBackground:(MSReorderingContainerView *)arg1;
- (double)startingOffsetForStackingContainerBackground:(MSReorderingContainerView *)arg1;
@end

