//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MSRulerGuides : NSObject
{
}

+ (struct CGRect)absoluteFrameOfSelectedLayers:(id)arg1;
+ (id)horizontalGuidesForGrid:(id)arg1 ruler:(id)arg2 forDrawing:(BOOL)arg3 inRect:(struct CGRect)arg4;
+ (id)horizontalGuidesForVerticalRuler:(id)arg1 forDrawing:(BOOL)arg2 inRect:(struct CGRect)arg3 rulersVisible:(BOOL)arg4;
+ (id)horizontalGuidesForVerticalRuler:(id)arg1 forDrawing:(BOOL)arg2 rulersVisible:(BOOL)arg3;
+ (id)snapGuidesForRulerData:(id)arg1 axis:(unsigned long long)arg2;
+ (id)verticalGuidesForGrid:(id)arg1 ruler:(id)arg2 forDrawing:(BOOL)arg3 inRect:(struct CGRect)arg4 rulersVisible:(BOOL)arg5;
+ (id)verticalGuidesForHorizontalRuler:(id)arg1 forDrawing:(BOOL)arg2 inRect:(struct CGRect)arg3 rulersVisible:(BOOL)arg4;
+ (id)verticalGuidesForHorizontalRuler:(id)arg1 forDrawing:(BOOL)arg2 rulersVisible:(BOOL)arg3;

@end

