//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class MSContentDrawView, MSDocument, MSRulerData, MSRulerViewLayer, NSNumberFormatter;

@interface MSRulerView : NSView
{
    BOOL didOpenUndoGroup;
    unsigned long long dragIndex;
    double baseOffset;
    double previousBase;
    NSNumberFormatter *metricsFormatter;
    BOOL _mouseDidDrag;
    MSRulerData *_rulerData;
    MSDocument *_document;
    MSContentDrawView *_contentView;
    unsigned long long _axis;
    double _temporaryRulerGuide;
    MSRulerViewLayer *_rulerViewLayer;
    struct CGPoint _mouseDownPoint;
}


- (BOOL)acceptsFirstResponder;
- (void)addNewGuideAtMousePoint:(struct CGPoint)arg1;
- (void)awakeFromNib;
@property(nonatomic) unsigned long long axis; // @synthesize axis=_axis;
- (double)baseLine;
- (double)baseLineIncludingScrollOrigin:(BOOL)arg1;
- (void)beginUndo;
- (id)bezierPathForLineAtPosition:(double)arg1 inRect:(struct CGRect)arg2;
- (void)calculateContentsScale;
@property(nonatomic) __weak MSContentDrawView *contentView; // @synthesize contentView=_contentView;
- (void)dealloc;
- (struct CGPoint)distanceFromDragOrigin:(struct CGPoint)arg1;
@property(nonatomic) __weak MSDocument *document; // @synthesize document=_document;
- (void)dragRulerBaseWithMouse:(struct CGPoint)arg1;
- (void)dragSelectedGuideWithMouse:(struct CGPoint)arg1;
- (void)drawGuide:(double)arg1 onCanvasInRect:(struct CGRect)arg2;
- (void)drawGuidesOnCanvasInRect:(struct CGRect)arg1;
- (void)endUndo;
- (BOOL)eventInView:(id)arg1;
- (double)guidePositionForMouse:(struct CGPoint)arg1;
- (id)guides;
- (unsigned long long)indexOfGuideAtMousePoint:(struct CGPoint)arg1;
- (id)makeRulerViewLayer;
- (id)menuForEvent:(id)arg1;
@property(nonatomic) BOOL mouseDidDrag; // @synthesize mouseDidDrag=_mouseDidDrag;
- (void)mouseDown:(id)arg1;
@property(nonatomic) struct CGPoint mouseDownPoint; // @synthesize mouseDownPoint=_mouseDownPoint;
- (void)mouseDragged:(id)arg1;
- (void)mouseDraggedAtPoint:(struct CGPoint)arg1;
- (struct CGPoint)mouseEventToPoint:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseUp:(id)arg1;
- (struct CGRect)occupiedRegion;
- (id)occupiedRegionForRect:(struct CGRect)arg1 withOffset:(long long)arg2 zoom:(double)arg3;
- (double)otherAxisForPoint:(struct CGPoint)arg1;
- (void)prepareRulerViewLayer:(struct CGRect)arg1;
- (void)refreshAllGuidesInDrawView;
- (void)refreshGuideInDrawViewAtIndex:(unsigned long long)arg1;
- (void)refreshGuideInDrawViewAtPosition:(double)arg1;
- (void)refreshGuidesForGrid:(id)arg1;
- (void)refreshTemporaryRulerGuide;
- (double)relevantAxisForPoint:(struct CGPoint)arg1;
- (void)removeGuide:(id)arg1;
- (struct CGRect)rulerBasedRectForLayer:(id)arg1;
@property(retain, nonatomic) MSRulerData *rulerData; // @synthesize rulerData=_rulerData;
- (long long)rulerHeight;
- (long long)rulerLength;
@property(retain, nonatomic) MSRulerViewLayer *rulerViewLayer; // @synthesize rulerViewLayer=_rulerViewLayer;
- (Class)rulerViewLayerClass;
- (struct CGPoint)scrollOrigin;
- (void)setDragCursor;
- (void)setFrame:(struct CGRect)arg1;
- (void)setHidden:(BOOL)arg1;
- (void)setResizeCursor;
@property(nonatomic) double temporaryRulerGuide; // @synthesize temporaryRulerGuide=_temporaryRulerGuide;
- (void)showAppropriateCursorForMouse:(struct CGPoint)arg1;
- (double)snapGuideToSelectedLayers:(double)arg1;
- (id)snapLineWithPosition:(double)arg1;
- (void)turnAlignmentGuidesBackOn;
- (void)updateSelectedLayerOriginsInInspector;
- (void)windowDidChangeScreen:(id)arg1;
- (double)zoomValue;

@end

