//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSView;

@protocol MSSectionProtocol <NSObject>
- (NSArray *)views;

@optional
- (BOOL)wantsSeparatorBetweenView:(NSView *)arg1 andView:(NSView *)arg2;
@end

