//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSMutableArray;

@interface MSSelectionPathCollection : NSObject <NSCopying>
{
    NSMutableArray *_internalPaths;
}


- (void)addSelectionPath:(id)arg1;
- (void)addSelectionsFromCollection:(id)arg1;
- (void)clear;
- (BOOL)containsSelectionPath:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)count;
- (id)description;
- (id)init;
@property(retain, nonatomic) NSMutableArray *internalPaths; // @synthesize internalPaths=_internalPaths;
- (BOOL)isEmpty;
- (id)lastSelectionPath;
- (void)removeSelectionPath:(id)arg1;
- (id)selectionPaths;
- (void)toggleSelectionPath:(id)arg1;
- (void)toggleSelectionsFromCollection:(id)arg1;

@end

