//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSSharedLayerContainer.h"

@interface MSSharedLayerContainer : _MSSharedLayerContainer
{
}

- (id)addSymbolWithName:(id)arg1 firstInstance:(id)arg2;
- (BOOL)canMakeSymbolForLayers:(id)arg1;
- (void)enumeratePotentialInstancesInContainer:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)firstNonSymbolContainerForGroup:(id)arg1;
- (id)fixedObjectIDsForTemplateInstance:(id)arg1;
- (long long)indexOfSymbol:(id)arg1;
- (BOOL)isLayerContainedByAnySymbol:(id)arg1;
- (BOOL)isSymbolForInstance:(id)arg1;
- (id)keyForPreservingTextLayer:(id)arg1;
- (id)layersToIterateOver;
- (id)mergeSymbolWithName:(id)arg1 symbolID:(id)arg2 instance:(id)arg3;
- (unsigned long long)numberOfSymbols;
- (id)preservedTextForSyncingInstance:(id)arg1 withTemplate:(id)arg2;
- (void)registerInstance:(id)arg1 withSharedStyle:(id)arg2;
- (void)removeSymbol:(id)arg1;
- (void)restoreTextOnInstance:(id)arg1 preservedText:(id)arg2;
- (Class)sharedObjectClass;
- (id)sharedObjectContainingLayer:(id)arg1;
- (id)symbolAtIndex:(unsigned long long)arg1;
- (id)symbolForInstance:(id)arg1;
- (id)symbolWithID:(id)arg1;
- (void)syncInstance:(id)arg1 withTemplateInstance:(id)arg2;

@end

