//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSSharedObject.h"

@interface MSSharedObject : _MSSharedObject
{
}

- (id)container;
- (id)defaultName;
- (id)initWithName:(id)arg1 firstInstance:(struct MSModelObject *)arg2;
- (id)initWithName:(id)arg1 sharedObjectID:(id)arg2 value:(struct MSModelObject *)arg3;
- (BOOL)isOutOfSyncWithInstance:(struct MSModelObject *)arg1;
- (BOOL)isSharedObjectForInstance:(struct MSModelObject *)arg1;
- (struct MSModelObject *)newInstance;
- (struct MSModelObject *)newUnregisteredInstance;
- (void)objectDidInit;
- (id)parentGroup;
- (void)prepareToBecomeSharedObjectValue:(struct MSModelObject *)arg1;
- (void)registerInstance:(struct MSModelObject *)arg1;
- (unsigned long long)type;
- (void)unregisterInstance:(struct MSModelObject *)arg1;

@end

