//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSSharedLayer.h"

@interface MSSharedLayer : _MSSharedLayer
{
}

- (id)defaultName;
- (id)ignoredTextLayersFromInstance:(id)arg1;
- (id)newInstance;
- (id)newInstanceReplacingLayer:(id)arg1;
- (id)newUnregisteredInstance;
- (void)prepareToBecomeSharedObjectValue:(struct MSModelObject *)arg1;
- (id)symbol;
- (unsigned long long)type;

@end

