//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSDocumentData, MSLayer, MSPage, MSSidebarListController, NSArray;

@protocol MSSidebarControllerDelegate <NSObject>
@property(readonly, nonatomic) MSDocumentData *documentData;
- (NSArray *)sidebarController:(MSSidebarListController *)arg1 exportLayers:(NSArray *)arg2;
- (void)sidebarController:(MSSidebarListController *)arg1 hoveredLayerDidChangeTo:(MSLayer *)arg2;
- (void)sidebarController:(MSSidebarListController *)arg1 validateRemovalOfPage:(MSPage *)arg2 withRemovalBlock:(void (^)(void))arg3;
- (NSArray *)sidebarControllerContextMenuItemsForCurrentSelection:(MSSidebarListController *)arg1;
- (void)sidebarControllerDidUpdate:(MSSidebarListController *)arg1;
- (void)sidebarControllerSelectionDidChange:(MSSidebarListController *)arg1;
@end

