//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSDocumentData, NSArray;

@interface MSSidebarListController : NSObject
{
    id <MSSidebarControllerDelegate> _delegate;
    id _rootObject;
}


- (BOOL)canCopyNode:(id)arg1 toParent:(id)arg2 after:(id)arg3;
- (BOOL)canCopyNodes:(id)arg1 toParent:(id)arg2 after:(id)arg3;
- (BOOL)canMoveNode:(id)arg1 toParent:(id)arg2 after:(id)arg3;
- (BOOL)canMoveNodes:(id)arg1 toParent:(id)arg2 after:(id)arg3;
- (BOOL)copyNode:(id)arg1 toParent:(id)arg2 after:(id)arg3;
- (BOOL)copyNodes:(id)arg1 toParent:(id)arg2 after:(id)arg3;
@property(nonatomic) __weak id <MSSidebarControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) __weak MSDocumentData *documentData;
@property(readonly, nonatomic) NSArray *dragTypes;
- (id)exportNodes:(id)arg1;
- (id)initWithDelegate:(id)arg1;
- (id)layerForNode:(id)arg1;
- (BOOL)moveNode:(id)arg1 toParent:(id)arg2 after:(id)arg3;
- (BOOL)moveNodes:(id)arg1 toParent:(id)arg2 after:(id)arg3;
- (id)readNodesFromPasteboard:(id)arg1;
@property(readonly, nonatomic) id rootObject; // @synthesize rootObject=_rootObject;
- (BOOL)writeNodes:(id)arg1 toPasteboard:(id)arg2;

@end

