//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSSnapperEdgeHelperBase.h"

@interface MSSnapperEdgeHelperTop : MSSnapperEdgeHelperBase
{
}

+ (struct CGRect)snapLayer:(id)arg1 toLine:(id)arg2 oldFrame:(struct CGRect)arg3 mayResize:(BOOL)arg4;

@end

