//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSStyleBorder.h"

@interface MSStyleBorder : _MSStyleBorder
{
}

+ (id)defaultFillColor;
- (id)CSSAttributeString;
- (void)addSVGAttributes:(id)arg1 forExporter:(id)arg2;
- (id)blendingViewForColorInspector:(id)arg1;
- (id)defaultName;
- (void)drawBorder:(id)arg1 advancedOptions:(id)arg2 context:(id)arg3;
- (void)drawGradientBorder:(id)arg1 originalPath:(id)arg2 isArtistic:(BOOL)arg3 frame:(struct CGRect)arg4 context:(id)arg5;
- (void)initEmptyObject;
- (void)multiplyBy:(double)arg1;
- (double)noiseIntensity;
- (long long)patternFillType;
- (void)setIsEnabled:(BOOL)arg1;
- (void)setPosition:(long long)arg1;
- (void)setThickness:(double)arg1;
- (BOOL)supportsAdvancedBorderSettings;
- (id)topViewForColorInspector:(id)arg1;
- (void)updateColorCounter:(id)arg1;

@end

