//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSStarShape.h"

#import "NSCoding.h"

@interface MSStarShape : _MSStarShape <NSCoding>
{
}

- (id)addContentToElement:(id)arg1 attributes:(id)arg2 exporter:(id)arg3 action:(unsigned long long *)arg4;
- (struct CGRect)boundsForCursorPreview;
- (id)defaultName;
- (id)inspectorViewControllers;
- (void)resetPoints;

@end

