//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSStyleRenderer.h"

@class MSBitmapLayer;

@interface MSStyleImageRenderer : MSStyleRenderer
{
    BOOL _treatAsAlpha;
    MSBitmapLayer *_bitmapLayer;
}

+ (void)drawBitmapLayer:(id)arg1 context:(id)arg2 inRect:(struct CGRect)arg3;

@property(retain, nonatomic) MSBitmapLayer *bitmapLayer; // @synthesize bitmapLayer=_bitmapLayer;
- (BOOL)canDrawNineSliceContent;
- (void)doDrawImage;
- (void)drawImage;
- (void)drawNineSliceImage;
- (void)render;
@property(nonatomic) BOOL treatAsAlpha; // @synthesize treatAsAlpha=_treatAsAlpha;

@end

