//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSStyledLayer.h"

@interface MSStyledLayer : _MSStyledLayer
{
    BOOL ignoreStyleDidChangeNotifications;
    BOOL _lightweightHasBitmapStylesEnabled;
}

+ (void)pasteExportOptions:(id)arg1 onLayers:(id)arg2;
+ (void)pasteStyleDict:(id)arg1 onLayers:(id)arg2 document:(id)arg3;
+ (void)pasteStyleFromPasteboard:(id)arg1 onLayers:(id)arg2 document:(id)arg3;
+ (void)pasteStyleFromPasteboardOnLayers:(id)arg1 document:(id)arg2;
+ (void)pasteTextStyle:(id)arg1 onLayers:(id)arg2;
+ (id)supportedPasteboardTypesForStyleCopying;
+ (unsigned long long)traits;
- (id)CSSAttributes;
- (void)addGradientsToDocument:(id)arg1;
- (id)appendShadowAttributesToString:(id)arg1;
- (BOOL)calculateHasBlendedLayer;
- (void)changeColor:(id)arg1;
- (id)copiedStyleAttributesForLayer:(id)arg1;
- (id)copyStyleToPasteboard;
- (void)copyStyleToPasteboard:(id)arg1;
- (BOOL)hasActiveBackgroundBlur;
- (BOOL)hasBitmapStylesEnabled;
- (BOOL)isSharedObject;
- (void)layerStyleDidChange;
- (id)layersSharingStyle:(id)arg1;
@property(nonatomic) BOOL lightweightHasBitmapStylesEnabled; // @synthesize lightweightHasBitmapStylesEnabled=_lightweightHasBitmapStylesEnabled;
- (void)multiplyBy:(double)arg1;
- (void)prepareObjectCopy:(id)arg1;
- (id)previewBorderColor:(BOOL)arg1;
- (id)previewFillColor:(BOOL)arg1;
- (id)renderBitmapEffects:(id)arg1;
- (void)setStyle:(id)arg1;
- (void)setupWithLayerBuilderDictionary:(id)arg1;
- (id)sharedObjectOfType:(unsigned long long)arg1;
- (unsigned long long)shouldDraw;
- (BOOL)shouldRenderInTransparencyLayer;
- (void)trackColors:(id)arg1;
- (void)trackColorsForBasicFill:(id)arg1 tracker:(id)arg2;
- (struct CGRect)translateInfluenceRectFromBoundsToFrame:(struct CGRect)arg1;
- (id)usedStyle;
- (void)writeStyleToPasteboard:(id)arg1;

@end

