//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSStyleBorderOptions.h"

@interface MSStyleBorderOptions : _MSStyleBorderOptions
{
}

- (void)addSVGAttributes:(id)arg1 forExporter:(id)arg2;
@property(readonly, nonatomic) BOOL hasDashPattern;
- (void)multiplyBy:(double)arg1;
- (BOOL)supportsAdvancedBorderSettings;

@end

