//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MSSymbolCreator : NSObject
{
}

+ (BOOL)canCreateSymbolFromLayers:(id)arg1;
+ (id)createSymbolFromLayers:(id)arg1 suggestedName:(id)arg2;
+ (id)groupForCreatingSymbolsFromLayers:(id)arg1;
+ (void)moveSlicesOutOfGroup:(id)arg1;
+ (BOOL)unHideLayersIfNecessary:(id)arg1;

@end

