//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSEventHandler.h"

#import "MSFirstLineTypesetterDelegate.h"
#import "MSTextLayerEditingDelegate.h"
#import "NSTextStorageDelegate.h"
#import "NSTextViewDelegate.h"
#import "NSWindowDelegate.h"

@class MSTextLayer, MSTextLayerTextView, MSTextWindow, NSString;

@interface MSTextLayerEventHandler : MSEventHandler <NSTextViewDelegate, NSTextStorageDelegate, NSWindowDelegate, MSTextLayerEditingDelegate, MSFirstLineTypesetterDelegate>
{
    MSTextLayerTextView *_textView;
    MSTextWindow *_textViewWindow;
    MSTextLayer *_textLayer;
}


- (void)addTextView;
- (void)adjustForegroundColor;
- (void)adjustTextViewFrame;
- (double)averageLuminanceOfImage:(struct CGImage *)arg1;
- (double)baselineAdjustmentForTypesetter:(id)arg1;
- (void)beginEditing;
- (BOOL)canDuplicate;
- (void)dealloc;
- (void)dispatchTryPutFirstFocusBack;
- (void)doTextModification:(CDUnknownBlockType)arg1;
- (struct CGRect)frameForTextView;
- (struct CGRect)frameForTextViewOnCanvasBasedOnBaseFrame:(struct CGRect)arg1;
- (void)handlerGotFocus;
- (void)handlerWillLoseFocus;
- (id)insertionPointColor;
- (void)makeLowercase:(id)arg1;
- (void)makeTextView;
- (void)makeTextWindow;
- (void)makeUppercase:(id)arg1;
- (BOOL)mouseDown:(struct CGPoint)arg1 clickCount:(unsigned long long)arg2 flags:(unsigned long long)arg3;
- (struct CGImage *)newTextLayerImageFromWindowBackingStore;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeTextView;
- (BOOL)scrollEventShouldExitHandler:(id)arg1;
- (void)selectAll:(id)arg1;
@property(retain, nonatomic) MSTextLayer *textLayer; // @synthesize textLayer=_textLayer;
@property(retain, nonatomic) MSTextLayerTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) MSTextWindow *textViewWindow; // @synthesize textViewWindow=_textViewWindow;
- (BOOL)shouldDrawLayerSelection;
- (void)textStorageDidProcessEditing:(id)arg1;
- (BOOL)textView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (id)toolbarIdentifier;
- (void)tryPutFirstFocusBack;
- (id)undoManager;
- (void)viewDidScroll:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (struct CGRect)windowFrameForDrawView;
- (struct CGRect)windowFrameForTextView;
- (void)zoomValueWillChangeTo:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

