//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSTextLayer.h"

#import "MSColorUser.h"
#import "MSFirstLineTypesetterDelegate.h"
#import "NSTextStorageDelegate.h"

@class MSColor, NSBezierPath, NSDictionary, NSString, NSTextStorage;

@interface MSTextLayer : _MSTextLayer <MSColorUser, NSTextStorageDelegate, MSFirstLineTypesetterDelegate>
{
    BOOL isEditingText;
    int ignoreDelegateNotificationsCounter;
    NSBezierPath *_cachedBezierRepresentation;
    NSTextStorage *_storageBeforeResize;
    id <MSTextLayerEditingDelegate> _editingDelegate;
    NSBezierPath *_lightweightFirstUnderlyingShapePath;
    double _lightweightFontSize;
    struct CGSize _sizeBeforeResize;
    struct CGRect _previousRectCache;
}

+ (void)setTextAlignment:(unsigned long long)arg1 forLayers:(id)arg2;
+ (unsigned long long)traits;

- (id)CSSAttributes;
- (void)addAttribute:(id)arg1 value:(id)arg2;
- (void)addAttribute:(id)arg1 value:(id)arg2 forRange:(struct _NSRange)arg3;
- (void)addAttributes:(id)arg1 forRange:(struct _NSRange)arg2;
- (id)addContentToElement:(id)arg1 attributes:(id)arg2 exporter:(id)arg3 action:(unsigned long long *)arg4;
- (void)addSVGAttributes:(id)arg1 forCharacterAttributes:(id)arg2 forExporter:(id)arg3 origin:(struct CGPoint *)arg4;
- (void)adjustContainerWidthTo:(double)arg1;
- (void)adjustFrameToFit;
- (void)appendBaseTranslation:(id)arg1 exporter:(id)arg2;
- (id)attributeForKey:(id)arg1;
- (double)baseLineHeight;
- (double)baselineAdjustmentForTypesetter:(id)arg1;
- (id)bezierPath;
- (id)bezierPathFromGlyphsInBounds;
- (id)bezierPathFromGlyphsInFrame;
- (id)bezierPathWithTransforms;
@property(retain, nonatomic) NSBezierPath *cachedBezierRepresentation; // @synthesize cachedBezierRepresentation=_cachedBezierRepresentation;
- (void)calculateTextIsClippedAfterResizeFromCorner:(long long)arg1;
- (void)changeColor:(id)arg1;
- (void)changeFont:(id)arg1;
- (void)changeListType:(id)arg1;
- (void)changeTextColorTo:(id)arg1;
@property(nonatomic) double characterSpacing;
- (BOOL)compareAttributes:(id)arg1 withAttributes:(id)arg2;
- (BOOL)constrainProportions;
- (void)copyTextStorageTo:(id)arg1;
- (id)createLayoutManager;
- (id)createTextContainer;
- (double)defaultLineHeight;
- (id)defaultName;
- (void)drawHoverWithZoom:(double)arg1;
- (void)drawPreviewInRect:(struct CGRect)arg1 selected:(BOOL)arg2;
@property(nonatomic) __weak id <MSTextLayerEditingDelegate> editingDelegate; // @synthesize editingDelegate=_editingDelegate;
- (id)elementForSpan:(id)arg1 origin:(struct CGPoint)arg2 exporter:(id)arg3 text:(id)arg4;
- (void)finishEditing;
- (id)font;
@property(retain, nonatomic) NSString *fontPostscriptName;
@property(nonatomic) double fontSize;
- (id)handlerName;
- (void)ignoreDelegateNotificationsInBlock:(CDUnknownBlockType)arg1;
- (struct CGRect)influenceRectForBounds;
- (void)initEmptyObject;
- (void)initObjectWithCoder:(id)arg1;
- (id)initWithAttributedString:(id)arg1 maxWidth:(double)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 attributes:(id)arg2 type:(long long)arg3;
- (id)inspectorViewControllerNames;
- (BOOL)isEditingText;
- (BOOL)isEmpty;
- (BOOL)isFrameEqualForSync:(id)arg1;
- (float)kerning;
- (void)layerDidResizeFromInspector;
- (void)layerDidResizeFromRect:(struct CGRect)arg1 corner:(long long)arg2;
- (Class)layerSnapperObjectClass;
- (void)layerStyleDidChange;
- (void)layerWillResize;
- (id)layoutManager;
- (double)leading;
@property(retain, nonatomic) NSBezierPath *lightweightFirstUnderlyingShapePath; // @synthesize lightweightFirstUnderlyingShapePath=_lightweightFirstUnderlyingShapePath;
@property(nonatomic) double lightweightFontSize; // @synthesize lightweightFontSize=_lightweightFontSize;
@property(nonatomic) double lineSpacing;
- (void)makeLowercase:(id)arg1;
- (void)makeUppercase:(id)arg1;
- (void)markLayerDirtyOfType:(unsigned long long)arg1;
- (void)migratePropertiesFromV44OrEarlierWithCoder:(id)arg1;
- (void)multiplyBy:(double)arg1;
- (void)objectDidInit;
- (id)paragraphStyle;
- (void)parentWillResizeLayerToRect:(struct CGRect)arg1;
- (void)prepareForUndo;
- (void)prepareObjectCopy:(id)arg1;
@property(nonatomic) struct CGRect previousRectCache; // @synthesize previousRectCache=_previousRectCache;
- (void)rectDidChange:(id)arg1 fromRect:(struct CGRect)arg2;
- (Class)rendererClass;
- (void)replaceTextPreservingAttributeRanges:(id)arg1;
- (void)resizeFontToFitFromRect:(struct CGRect)arg1;
- (void)sanityCheckText;
- (unsigned long long)selectionCornerMaskWithZoomValue:(double)arg1;
- (void)setAttributes:(id)arg1 forRange:(struct _NSRange)arg2;
- (void)setContainerSize:(struct CGSize)arg1;
- (void)setFont:(id)arg1;
- (void)setIsEditingText:(BOOL)arg1;
- (void)setKerning:(float)arg1;
- (void)setLeading:(double)arg1;
- (void)setNilValueForKey:(id)arg1;
- (void)setRectAccountingForClipped:(struct CGRect)arg1;
@property(nonatomic) struct CGSize sizeBeforeResize; // @synthesize sizeBeforeResize=_sizeBeforeResize;
@property(copy, nonatomic) NSTextStorage *storageBeforeResize; // @synthesize storageBeforeResize=_storageBeforeResize;
- (void)setStorageContents:(id)arg1;
@property(copy, nonatomic) NSString *stringValue;
- (void)setStringValueWithoutUndo:(id)arg1;
- (void)setStyle:(id)arg1;
@property(copy, nonatomic) NSDictionary *styleAttributes;
@property(nonatomic) unsigned long long textAlignment;
- (void)setTextBehaviour:(long long)arg1;
@property(copy, nonatomic) MSColor *textColor;
- (void)setUpText;
- (void)setupBehaviour:(BOOL)arg1;
- (void)setupWithLayerBuilderDictionary:(id)arg1;
- (id)shapeToUseForTextOnPath;
- (unsigned long long)shouldDraw;
- (BOOL)shouldDrawSelection;
- (BOOL)shouldRenderInTransparencyLayer;
- (BOOL)shouldUseCachedBezierRepresentation;
- (id)spanInfoForRun:(struct _NSRange)arg1 charAttributes:(id)arg2 text:(id)arg3;
- (double)startingPositionOnPath:(id)arg1;
- (BOOL)supportsInnerOuterBorders;
- (id)svgStyle;
- (void)syncTextStorageTo:(id)arg1;
- (void)syncTextStyleAttributes;
- (id)textContainer;
- (struct CGSize)textContainerSize;
- (void)textStorageDidProcessEditing:(id)arg1;
- (BOOL)textStorageIsEqual:(id)arg1;
- (double)totalHeightOfFont:(id)arg1;
- (void)trackColors:(id)arg1;
- (BOOL)treatAsShiftedForCorner:(long long)arg1 onlyForFlexible:(BOOL)arg2;
- (void)updateColorCounter:(id)arg1;
- (BOOL)useProportionalResizingFromCorner:(long long)arg1;
- (id)usedFonts;
- (void)writeStyleToPasteboard:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

