//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSKeyedUnarchiver.h"

@interface MSUnarchiver : NSKeyedUnarchiver
{
    long long _version;
    SEL _propertyDecoder;
}

+ (void)defineReplacementClasses;
+ (void)initialize;
+ (id)unarchiveObjectFromURL:(id)arg1 actualVersion:(long long *)arg2;
+ (id)unarchiveObjectWithData:(id)arg1;
+ (id)unarchiveObjectWithData:(id)arg1 actualVersion:(long long *)arg2;
+ (id)unarchiveObjectWithData:(id)arg1 asVersion:(long long)arg2;
@property(readonly, nonatomic) SEL propertyDecoder; // @synthesize propertyDecoder=_propertyDecoder;
- (void)setDecodingVersion:(long long)arg1;
@property(readonly, nonatomic) long long version; // @synthesize version=_version;

@end

