//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSResponder.h"

@class MSIntegratedStepper, NSTextField<MSUpDownProtocol>;

@interface MSUpDownController : NSResponder
{
    BOOL hasOpenedUndoGroup;
    BOOL didChangeTextDuringEditing;
    NSTextField<MSUpDownProtocol> *_textField;
    MSIntegratedStepper *_stepper;
}

+ (void)initialize;

- (double)adjustValueForMaximum:(double)arg1;
- (double)adjustValueForMinimum:(double)arg1;
- (id)advancedUndoManager;
- (BOOL)becomeFirstResponder;
- (void)cancelOperation:(id)arg1;
- (BOOL)cancelTextEditingForInvalidReplacementString:(id)arg1;
- (void)decrement;
- (BOOL)doCommandBySelector:(SEL)arg1;
- (BOOL)eventIsInsideView:(id)arg1;
- (double)floatValue;
- (BOOL)hasValidFirstResponder;
- (void)hideStepper;
- (void)increment;
- (double)incrementValue;
- (double)incrementValueAccountingForModifierFlags;
- (id)initWithTextField:(id)arg1 createStepper:(BOOL)arg2;
- (BOOL)isEditable;
- (BOOL)isEnabled;
- (void)keyUp;
- (void)makeStepper;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)setFloatValueAndNotifyBindings:(double)arg1;
@property(retain, nonatomic) MSIntegratedStepper *stepper; // @synthesize stepper=_stepper;
@property(nonatomic) __weak NSTextField<MSUpDownProtocol> *textField; // @synthesize textField=_textField;
- (void)textDidChange:(id)arg1;
- (void)textDidEndEditing;

@end

