//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSComboBox.h"

#import "MSUpDownProtocol.h"
#import "NSTextViewDelegate.h"

@class MSUpDownController, NSString;

@interface MSUpDownComboBox : NSComboBox <NSTextViewDelegate, MSUpDownProtocol>
{
    id _refreshDelegate;
    MSUpDownController *_upDownController;
}


- (void)awakeFromNib;
- (BOOL)becomeFirstResponder;
- (double)incrementValue;
- (void)keyUp:(id)arg1;
- (id)maximum;
- (id)minimum;
@property(nonatomic) __weak id refreshDelegate; // @synthesize refreshDelegate=_refreshDelegate;
@property(retain, nonatomic) MSUpDownController *upDownController; // @synthesize upDownController=_upDownController;
- (void)textDidEndEditing:(id)arg1;
- (BOOL)textView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (BOOL)textView:(id)arg1 shouldChangeTextInRanges:(id)arg2 replacementStrings:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

