//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSRulerView.h"

@interface MSVerticalRulerView : MSRulerView
{
}

- (void)awakeFromNib;
- (id)bezierPathForLineAtPosition:(double)arg1 inRect:(struct CGRect)arg2;
- (BOOL)isFlipped;
- (id)occupiedRegionForRect:(struct CGRect)arg1 withOffset:(long long)arg2 zoom:(double)arg3;
- (void)refreshGuideInDrawViewAtPosition:(double)arg1;
- (void)refreshTemporaryRulerGuide;
- (Class)rulerViewLayerClass;
- (void)setResizeCursor;
- (id)snapLineWithPosition:(double)arg1;

@end

