//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (Chocolat)
+ (id)arrayByMergingArrays:(id)arg1;
- (id)arrayByAddingObjects:(id)arg1;
- (id)arrayByRemovingNull;
- (id)arrayByRemovingObject:(id)arg1;
- (id)arrayByRemovingObjects:(id)arg1;
- (BOOL)containsObjectOfClass:(Class)arg1;
- (BOOL)containsOnlyObjectsOfClass:(Class)arg1;
- (id)copyDeep;
- (id)dictionaryBySplittingArrayUsingKey:(id)arg1;
- (void)enumerate:(CDUnknownBlockType)arg1;
- (void)enumerateTailUsingBlock:(CDUnknownBlockType)arg1;
- (void)enumerateWithIndex:(CDUnknownBlockType)arg1;
- (id)filterUsingBlockWithIndex:(CDUnknownBlockType)arg1;
- (id)filteredArrayUsingBlock:(CDUnknownBlockType)arg1;
- (id)filteredByObjectsOfClass:(Class)arg1;
- (BOOL)isValidIndex:(unsigned long long)arg1;
- (id)map:(CDUnknownBlockType)arg1;
- (id)mapWithIndex:(CDUnknownBlockType)arg1;
- (id)mutableCopyDeep;
- (id)objectAtIndexOrNil:(unsigned long long)arg1;
- (id)reversedArray;
- (id)rotateTwoDimensionalArray;
- (id)sortedArray;
- (id)sortedArrayUsingKey:(id)arg1;
- (id)subArrayToIndex:(long long)arg1;
- (id)tail;
- (id)uniqueObjects;
@end

