//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAttributedString.h"

@interface NSAttributedString (CHAttributedString)
- (id)attributeOrNil:(id)arg1 atIndex:(unsigned long long)arg2;
- (BOOL)attributesMatch:(id)arg1;
@end

