//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBezierPath.h"

@interface NSBezierPath (NSBezierPath_Bending)
- (void)addCurveSement:(id)arg1 toBezierPath:(id)arg2 bendingOverPath:(id)arg3 atOffset:(double)arg4;
- (void)addLineSement:(id)arg1 toBezierPath:(id)arg2 bendingOverPath:(id)arg3 atOffset:(double)arg4;
- (void)addShortCurveSegment:(id)arg1 toBezierPath:(id)arg2 bendingOverPath:(id)arg3 atOffset:(double)arg4;
- (void)addShortLineSement:(id)arg1 toBezierPath:(id)arg2 bendingOverPath:(id)arg3 atOffset:(double)arg4;
- (id)bendToBezierPath:(id)arg1 atOffset:(double)arg2;
- (struct CGPoint)putPoint:(struct CGPoint)arg1 onBezierPath:(id)arg2 offset:(long long)arg3;
@end

