//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSBezierPathItem : NSObject
{
    struct CGPoint points[3];
    unsigned long long _type;
}

- (id)bezierPathStartingAtPoint:(struct CGPoint)arg1;
- (id)debugDescription;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqual:(id)arg1 withAccuracy:(double)arg2;
- (struct CGPoint *)points;
- (void)setPoints:(struct CGPoint *)arg1;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;

@end

