//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCursor.h"

@interface NSCursor (NSCursorResizeExtensions)
+ (id)cursorWithName:(id)arg1 hotSpot:(struct CGPoint)arg2;
+ (id)penAddCursor;
+ (id)penCloseCursor;
+ (id)penCursor;
+ (id)resizeBottomLeftToTopRightCursor;
+ (id)resizeHorCursor;
+ (id)resizeTopLeftToBottomRightCursor;
+ (id)resizeVerCursor;
+ (id)rotateBottomCursor;
+ (id)rotateBottomLeftCursor;
+ (id)rotateBottomRightCursor;
+ (id)rotateLeftCursor;
+ (id)rotateRightCursor;
+ (id)rotateTopCursor;
+ (id)rotateTopLeftCursor;
+ (id)rotateTopRightCursor;
@end

