//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (ZKAdditions)
+ (id)zk_totalSizeAndCountDictionaryWithSize:(unsigned long long)arg1 andItemCount:(unsigned long long)arg2;
- (unsigned long long)zk_itemCount;
- (unsigned long long)zk_totalFileSize;
@end

