//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSShadow.h"

@interface NSShadow (CHShadowExtensions)
+ (void)clearShadow;
+ (id)shadowWithColor:(id)arg1 offset:(struct CGSize)arg2 blur:(double)arg3;
@property(nonatomic) double blurRadius;
@property(nonatomic) double offsetX;
@property(nonatomic) double offsetY;
@end

