//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_SVGGradient.h"

@interface SVGGradient : _SVGGradient
{
}

- (struct CGPoint)from;
- (void)processSelf:(id)arg1;
- (void)setupLinearGradientWithXML:(id)arg1;
- (void)setupRadialGradientWithXML:(id)arg1;
- (id)stopsElements;
- (id)svgAttributesDescription;
- (struct CGPoint)to;

@end

