//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDate, NSString;

@interface ZKLFHeader : NSObject
{
    unsigned int _magicNumber;
    unsigned int _versionNeededToExtract;
    unsigned int _generalPurposeBitFlag;
    unsigned int _compressionMethod;
    unsigned int _crc;
    unsigned int _filenameLength;
    unsigned int _extraFieldLength;
    NSDate *_lastModDate;
    unsigned long long _compressedSize;
    unsigned long long _uncompressedSize;
    NSString *_filename;
    NSData *_extraField;
}

+ (id)recordWithArchivePath:(id)arg1 atOffset:(unsigned long long)arg2;
+ (id)recordWithData:(id)arg1 atOffset:(unsigned long long)arg2;

@property unsigned long long compressedSize; // @synthesize compressedSize=_compressedSize;
@property unsigned int compressionMethod; // @synthesize compressionMethod=_compressionMethod;
@property unsigned int crc; // @synthesize crc=_crc;
- (id)data;
- (void)dealloc;
- (id)description;
@property(retain) NSData *extraField; // @synthesize extraField=_extraField;
@property unsigned int extraFieldLength; // @synthesize extraFieldLength=_extraFieldLength;
@property(copy) NSString *filename; // @synthesize filename=_filename;
@property unsigned int filenameLength; // @synthesize filenameLength=_filenameLength;
- (void)finalize;
@property unsigned int generalPurposeBitFlag; // @synthesize generalPurposeBitFlag=_generalPurposeBitFlag;
- (id)init;
- (BOOL)isResourceFork;
@property(retain) NSDate *lastModDate; // @synthesize lastModDate=_lastModDate;
- (unsigned long long)length;
@property unsigned int magicNumber; // @synthesize magicNumber=_magicNumber;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)parseZip64ExtraField;
- (void)removeObservers;
@property unsigned long long uncompressedSize; // @synthesize uncompressedSize=_uncompressedSize;
@property unsigned int versionNeededToExtract; // @synthesize versionNeededToExtract=_versionNeededToExtract;
- (BOOL)useZip64Extensions;
- (id)zip64ExtraField;

@end

