//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSModelBase.h"

@class MSArray;

@interface _MSExportOptions : MSModelBase
{
    BOOL _shouldTrim;
    MSArray *_includedLayerIds;
    unsigned long long _layerOptions;
    MSArray *_sizes;
}


- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (void)fillInEmptyObjects;
- (BOOL)hasDefaultValues;
- (id)immutableModelObject;
@property(retain, nonatomic) MSArray *includedLayerIds; // @synthesize includedLayerIds=_includedLayerIds;
- (void)initEmptyObject;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
@property(nonatomic) unsigned long long layerOptions; // @synthesize layerOptions=_layerOptions;
- (id)primitiveIncludedLayerIds;
- (unsigned long long)primitiveLayerOptions;
- (BOOL)primitiveShouldTrim;
- (id)primitiveSizes;
- (void)setAsParentOnChildren;
- (void)setPrimitiveIncludedLayerIds:(id)arg1;
- (void)setPrimitiveLayerOptions:(unsigned long long)arg1;
- (void)setPrimitiveShouldTrim:(BOOL)arg1;
- (void)setPrimitiveSizes:(id)arg1;
@property(nonatomic) BOOL shouldTrim; // @synthesize shouldTrim=_shouldTrim;
@property(retain, nonatomic) MSArray *sizes; // @synthesize sizes=_sizes;

@end

