//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSImmutableModelBase.h"

@interface _MSImmutableGraphicsContextSettings : MSImmutableModelBase
{
    long long _blendMode;
    double _opacity;
}

@property(nonatomic) long long blendMode; // @synthesize blendMode=_blendMode;
- (void)decodePropertiesWithCoder:(id)arg1;
- (void)encodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (BOOL)hasDefaultValues;
- (id)initWithMutableModelObject:(id)arg1;
@property(nonatomic) double opacity; // @synthesize opacity=_opacity;

@end

