//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSBaseGrid.h"

@interface _MSLayoutGrid : MSBaseGrid
{
    BOOL _drawHorizontal;
    BOOL _drawHorizontalLines;
    BOOL _drawVertical;
    BOOL _guttersOutside;
    double _columnWidth;
    double _gutterHeight;
    double _gutterWidth;
    double _horizontalOffset;
    double _numberOfColumns;
    double _rowHeightMultiplication;
    double _totalWidth;
}

@property(nonatomic) double columnWidth; // @synthesize columnWidth=_columnWidth;
- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
@property(nonatomic) BOOL drawHorizontal; // @synthesize drawHorizontal=_drawHorizontal;
@property(nonatomic) BOOL drawHorizontalLines; // @synthesize drawHorizontalLines=_drawHorizontalLines;
@property(nonatomic) BOOL drawVertical; // @synthesize drawVertical=_drawVertical;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (void)fillInEmptyObjects;
@property(nonatomic) double gutterHeight; // @synthesize gutterHeight=_gutterHeight;
@property(nonatomic) double gutterWidth; // @synthesize gutterWidth=_gutterWidth;
@property(nonatomic) BOOL guttersOutside; // @synthesize guttersOutside=_guttersOutside;
- (BOOL)hasDefaultValues;
@property(nonatomic) double horizontalOffset; // @synthesize horizontalOffset=_horizontalOffset;
- (id)immutableModelObject;
- (void)initEmptyObject;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
@property(nonatomic) double numberOfColumns; // @synthesize numberOfColumns=_numberOfColumns;
- (double)primitiveColumnWidth;
- (BOOL)primitiveDrawHorizontal;
- (BOOL)primitiveDrawHorizontalLines;
- (BOOL)primitiveDrawVertical;
- (double)primitiveGutterHeight;
- (double)primitiveGutterWidth;
- (BOOL)primitiveGuttersOutside;
- (double)primitiveHorizontalOffset;
- (double)primitiveNumberOfColumns;
- (double)primitiveRowHeightMultiplication;
- (double)primitiveTotalWidth;
@property(nonatomic) double rowHeightMultiplication; // @synthesize rowHeightMultiplication=_rowHeightMultiplication;
- (void)setAsParentOnChildren;
- (void)setPrimitiveColumnWidth:(double)arg1;
- (void)setPrimitiveDrawHorizontal:(BOOL)arg1;
- (void)setPrimitiveDrawHorizontalLines:(BOOL)arg1;
- (void)setPrimitiveDrawVertical:(BOOL)arg1;
- (void)setPrimitiveGutterHeight:(double)arg1;
- (void)setPrimitiveGutterWidth:(double)arg1;
- (void)setPrimitiveGuttersOutside:(BOOL)arg1;
- (void)setPrimitiveHorizontalOffset:(double)arg1;
- (void)setPrimitiveNumberOfColumns:(double)arg1;
- (void)setPrimitiveRowHeightMultiplication:(double)arg1;
- (void)setPrimitiveTotalWidth:(double)arg1;
@property(nonatomic) double totalWidth; // @synthesize totalWidth=_totalWidth;

@end

