//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import "MSModelBase.h"

@class MSExportOptions, MSRect, NSDictionary, NSString;

@interface _MSLayer : MSModelBase
{
    BOOL _isFlippedHorizontal;
    BOOL _isFlippedVertical;
    BOOL _isLocked;
    BOOL _isVisible;
    BOOL _nameIsFixed;
    BOOL _shouldBreakMaskChain;
    long long _layerListExpandedType;
    NSString *_name;
    NSString *_originalObjectID;
    double _rotation;
    NSDictionary *_userInfo;
    MSExportOptions *_exportOptions;
    MSRect *_frame;
}


- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
@property(retain, nonatomic) MSExportOptions *exportOptions; // @synthesize exportOptions=_exportOptions;
- (void)fillInEmptyObjects;
@property(retain, nonatomic) MSRect *frame; // @synthesize frame=_frame;
- (BOOL)hasDefaultValues;
- (id)immutableModelObject;
- (void)initEmptyObject;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
@property(nonatomic) BOOL isFlippedHorizontal; // @synthesize isFlippedHorizontal=_isFlippedHorizontal;
@property(nonatomic) BOOL isFlippedVertical; // @synthesize isFlippedVertical=_isFlippedVertical;
@property(nonatomic) BOOL isLocked; // @synthesize isLocked=_isLocked;
@property(nonatomic) BOOL isVisible; // @synthesize isVisible=_isVisible;
@property(nonatomic) long long layerListExpandedType; // @synthesize layerListExpandedType=_layerListExpandedType;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) BOOL nameIsFixed; // @synthesize nameIsFixed=_nameIsFixed;
@property(retain, nonatomic) NSString *originalObjectID; // @synthesize originalObjectID=_originalObjectID;
- (id)primitiveExportOptions;
- (id)primitiveFrame;
- (BOOL)primitiveIsFlippedHorizontal;
- (BOOL)primitiveIsFlippedVertical;
- (BOOL)primitiveIsLocked;
- (BOOL)primitiveIsVisible;
- (long long)primitiveLayerListExpandedType;
- (id)primitiveName;
- (BOOL)primitiveNameIsFixed;
- (id)primitiveOriginalObjectID;
- (double)primitiveRotation;
- (BOOL)primitiveShouldBreakMaskChain;
- (id)primitiveUserInfo;
@property(nonatomic) double rotation; // @synthesize rotation=_rotation;
- (void)setAsParentOnChildren;
- (void)setPrimitiveExportOptions:(id)arg1;
- (void)setPrimitiveFrame:(id)arg1;
- (void)setPrimitiveIsFlippedHorizontal:(BOOL)arg1;
- (void)setPrimitiveIsFlippedVertical:(BOOL)arg1;
- (void)setPrimitiveIsLocked:(BOOL)arg1;
- (void)setPrimitiveIsVisible:(BOOL)arg1;
- (void)setPrimitiveLayerListExpandedType:(long long)arg1;
- (void)setPrimitiveName:(id)arg1;
- (void)setPrimitiveNameIsFixed:(BOOL)arg1;
- (void)setPrimitiveOriginalObjectID:(id)arg1;
- (void)setPrimitiveRotation:(double)arg1;
- (void)setPrimitiveShouldBreakMaskChain:(BOOL)arg1;
- (void)setPrimitiveUserInfo:(id)arg1;
@property(nonatomic) BOOL shouldBreakMaskChain; // @synthesize shouldBreakMaskChain=_shouldBreakMaskChain;
@property(copy, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;

@end

