//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSStylePart.h"

@interface _MSStyleColorControls : MSStylePart
{
    double _brightness;
    double _contrast;
    double _hue;
    double _saturation;
}

@property(nonatomic) double brightness; // @synthesize brightness=_brightness;
@property(nonatomic) double contrast; // @synthesize contrast=_contrast;
- (void)copyPropertiesToObjectCopy:(id)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;
- (void)fillInEmptyObjects;
- (BOOL)hasDefaultValues;
@property(nonatomic) double hue; // @synthesize hue=_hue;
- (id)immutableModelObject;
- (void)initEmptyObject;
- (BOOL)isEqualForSync:(id)arg1 asPartOfSymbol:(id)arg2;
- (double)primitiveBrightness;
- (double)primitiveContrast;
- (double)primitiveHue;
- (double)primitiveSaturation;
@property(nonatomic) double saturation; // @synthesize saturation=_saturation;
- (void)setAsParentOnChildren;
- (void)setPrimitiveBrightness:(double)arg1;
- (void)setPrimitiveContrast:(double)arg1;
- (void)setPrimitiveHue:(double)arg1;
- (void)setPrimitiveSaturation:(double)arg1;

@end

