//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SVGDrawableElement.h"

@class NSImage;

@interface _SVGImage : SVGDrawableElement
{
    NSImage *_image;
}

+ (id)attributeNames;
+ (id)propertyNames;
+ (id)relationshipNames;

@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;

@end

