//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BCColorPickerSliderView.h"

@class BCFlexibleColor;

@interface BCAlphaColorPicker : BCColorPickerSliderView
{
    double _colorAlphaValue;
    BCFlexibleColor *_color;
}


@property(retain, nonatomic) BCFlexibleColor *color; // @synthesize color=_color;
@property(nonatomic) double colorAlphaValue; // @synthesize colorAlphaValue=_colorAlphaValue;
- (void)drawAlphaGradient;
- (void)drawCheckerboard;
- (void)drawContentInRect:(struct CGRect)arg1 dirtyRect:(struct CGRect)arg2;
- (id)initInBounds:(struct CGRect)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseDragged:(id)arg1;

@end

