//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BCColorPickerBaseView.h"

@interface BCSaturationBrightnessColorPicker : BCColorPickerBaseView
{
    struct CGPoint _originalPoint;
    double _hue;
    double _saturation;
    double _brightness;
}

@property(nonatomic) double brightness; // @synthesize brightness=_brightness;
- (void)dealloc;
- (void)drawContentInRect:(struct CGRect)arg1 dirtyRect:(struct CGRect)arg2;
@property(nonatomic) double hue; // @synthesize hue=_hue;
- (id)initInBounds:(struct CGRect)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseUp:(id)arg1;
- (struct CGRect)pickerRect;
@property(nonatomic) double saturation; // @synthesize saturation=_saturation;

@end

