//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableRowView.h"

@class NSColor, NSObject<BCOutlineViewDelegate>, NSObject<BCOutlineViewNode>, NSTableView;

@interface BCTableRowView : NSTableRowView
{
    NSTableView *_parent;
    NSObject<BCOutlineViewNode> *_node;
    NSObject<BCOutlineViewDelegate> *_delegate;
    unsigned long long _expansionState;
}


@property(readonly, nonatomic) NSColor *alternateRowBackgroundColour;
@property(readonly, nonatomic) NSColor *borderColour;
- (id)colourForItem:(SEL)arg1;
- (void)dealloc;
@property(retain, nonatomic) NSObject<BCOutlineViewDelegate> *delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) unsigned long long displayType;
- (void)drawBackgroundInRect:(struct CGRect)arg1;
- (void)drawDisclosureTriangle;
- (void)drawDraggingDestinationFeedbackInRect:(struct CGRect)arg1;
- (void)drawHighlight;
- (void)drawSelectionInRect:(struct CGRect)arg1;
@property(nonatomic) unsigned long long expansionState; // @synthesize expansionState=_expansionState;
- (void)fillBackgroundInRect:(struct CGRect)arg1;
@property(readonly, nonatomic) NSColor *highlightColour;
@property(readonly, nonatomic, getter=isHighlit) BOOL hightlighted;
@property(readonly, nonatomic, getter=isNodeExpanded) BOOL nodeExpanded;
@property(readonly, nonatomic, getter=isNodeSelected) BOOL nodeSelected;
@property(readonly, nonatomic) BOOL isOdd;
- (BOOL)isSelected;
@property(retain, nonatomic) NSObject<BCOutlineViewNode> *node; // @synthesize node=_node;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) NSTableView *parent; // @synthesize parent=_parent;
- (void)prepareForReuse;
@property(readonly, nonatomic) NSColor *rowBackgroundColour;
@property(readonly, nonatomic) NSColor *selectionBackgroundColour;
@property(readonly, nonatomic) NSColor *selectionForegroundColour;

@end

