//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, NSNumber, NSString;

@interface ECLogChannel : NSObject
{
    BOOL _enabled;
    BOOL _setup;
    unsigned long long _context;
    NSNumber *_level;
    NSString *_name;
    NSMutableSet *_handlers;
}

+ (id)cleanName:(const char *)arg1;

- (long long)caseInsensitiveCompare:(id)arg1;
@property(nonatomic) unsigned long long context; // @synthesize context=_context;
- (void)disable;
- (void)disableHandler:(id)arg1;
- (void)enable;
- (void)enableHandler:(id)arg1;
@property(nonatomic) BOOL enabled; // @synthesize enabled=_enabled;
- (id)fileFromContext:(CDStruct_5b5d1a5d *)arg1;
@property(retain, nonatomic) NSMutableSet *handlers; // @synthesize handlers=_handlers;
- (id)init;
- (id)initWithName:(id)arg1;
- (BOOL)isHandlerEnabled:(id)arg1;
@property(retain, nonatomic) NSNumber *level; // @synthesize level=_level;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void)selectFlagWithIndex:(unsigned long long)arg1;
- (void)selectHandlerWithIndex:(unsigned long long)arg1;
@property(nonatomic) BOOL setup; // @synthesize setup=_setup;
- (BOOL)showContext:(unsigned long long)arg1;
- (id)stringFromContext:(CDStruct_5b5d1a5d *)arg1;
- (BOOL)tickFlagWithIndex:(unsigned long long)arg1;
- (BOOL)tickHandlerWithIndex:(unsigned long long)arg1;

@end

