//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSBezierPath, NSMutableArray;

@interface MSBooleanOperationChain : NSObject
{
    NSBezierPath *_subjectPath;
    NSBezierPath *_resultPath;
    NSMutableArray *_steps;
}

+ (id)booleanOperationChainWithSubjectPath:(id)arg1;

- (void)addClippingPath:(id)arg1 forBooleanOperation:(long long)arg2;
- (id)initWithSubjectPath:(id)arg1;
@property(retain, nonatomic) NSBezierPath *resultPath; // @synthesize resultPath=_resultPath;
@property(retain, nonatomic) NSMutableArray *steps; // @synthesize steps=_steps;
@property(retain, nonatomic) NSBezierPath *subjectPath; // @synthesize subjectPath=_subjectPath;

@end

