//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSStylePartInspectorViewController.h"

#import "BCPopoverContentController.h"

@class NSArray, NSPopUpButton, NSSegmentedControl, NSString, NSTextField;

@interface MSBorderOptionsInspectorViewController : MSStylePartInspectorViewController <BCPopoverContentController>
{
    NSPopUpButton *startDecorationButton;
    NSPopUpButton *endDecorationButton;
    NSTextField *dashField1;
    NSTextField *dashField2;
    NSTextField *dashField3;
    NSTextField *dashField4;
    NSArray *_layers;
    NSSegmentedControl *_capSegmentedControl;
    NSSegmentedControl *_joinSegmentedControl;
}


- (void)capAction:(id)arg1;
@property(retain, nonatomic) NSSegmentedControl *capSegmentedControl; // @synthesize capSegmentedControl=_capSegmentedControl;
- (void)dashPatternAction:(id)arg1;
- (void)endDecorationAction:(id)arg1;
- (void)evaluateCapJoinButtons;
- (void)fillDashFields;
- (void)fillDashPlaceholderFields;
- (void)joinAction:(id)arg1;
@property(retain, nonatomic) NSSegmentedControl *joinSegmentedControl; // @synthesize joinSegmentedControl=_joinSegmentedControl;
@property(copy, nonatomic) NSArray *layers; // @synthesize layers=_layers;
- (void)prepareDecorationButtons;
- (void)reloadData;
- (void)startDecorationAction:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

