//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CHSingletonObject.h"

@class MSVersionedArchive;

@interface MSDefaultArchive : CHSingletonObject
{
    MSVersionedArchive *_archive;
}


@property(retain, nonatomic) MSVersionedArchive *archive; // @synthesize archive=_archive;
- (id)archivesNeedingMigration;
- (Class)defaultClass;
- (id)defaultObject;
- (id)filename;
- (id)newObject;
- (id)oldDefaultsName;
- (void)setDefaultObject:(id)arg1;

@end

