//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSDefaultArchive.h"

@interface MSDefaultStyle : MSDefaultArchive
{
}

+ (id)defaultStyle;
+ (void)loadStyleAndPatterns;
+ (void)resetCachedStyleForTesting;
+ (void)saveStyleAndPatterns;
+ (void)setDefaultStyle:(id)arg1;
- (Class)defaultClass;
- (id)filename;
- (id)newObject;
- (id)oldDefaultsName;

@end

