//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSDocumentData.h"

#import "MSArrayDelegate.h"
#import "MSLayerContainment.h"
#import "MSSharedObjectContainerDelegate.h"

@class MSImageCollection, MSPage, NSArray, NSString, NSUndoManager;

@interface MSDocumentData : _MSDocumentData <MSLayerContainment, MSArrayDelegate, MSSharedObjectContainerDelegate>
{
    NSUndoManager *_undoManager;
    id <MSDocumentDataDelegate> _delegate;
    long long _savedVersion;
    NSString *_savedVariant;
    NSString *_savedBy;
}

+ (id)documentDataFromData:(id)arg1 version:(long long)arg2 error:(id *)arg3;

- (id)addBlankPage;
- (void)addImageOwnersToSet:(id)arg1;
- (void)addPage:(id)arg1;
@property(readonly, nonatomic) __weak NSArray *allPages;
- (BOOL)canBeContainedByDocument;
- (BOOL)canBeContainedByGroup;
- (BOOL)canContainLayer:(id)arg1;
- (void)changeSelectionTo:(id)arg1;
- (void)closeParentGroupsIfRequired:(id)arg1;
- (id)colorFinderQueue;
- (id)containedLayers;
- (unsigned long long)containedLayersCount;
- (BOOL)containsLayers;
- (BOOL)containsMultipleLayers;
- (BOOL)containsNoOrOneLayers;
- (BOOL)containsOneLayer;
@property(retain, nonatomic) MSPage *currentPage;
- (void)dataArray:(id)arg1 didAddObject:(id)arg2;
- (void)dataArray:(id)arg1 didRemoveObject:(id)arg2;
- (void)dataArray:(id)arg1 willRemoveObject:(id)arg2;
- (void)dealloc;
- (id)defaultPagesArray;
@property(nonatomic) __weak id <MSDocumentDataDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deselectAllLayers;
- (id)documentData;
- (BOOL)documentIsEmpty;
- (void)enumerateLayers:(CDUnknownBlockType)arg1;
- (BOOL)enumerateLayersWithOptions:(unsigned long long)arg1 block:(CDUnknownBlockType)arg2;
- (void)enumerateSharedObjectContainers:(CDUnknownBlockType)arg1;
- (void)findFrequentColorsWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)firstLayer;
- (id)imageHashes;
@property(readonly, nonatomic) MSImageCollection *images;
- (void)immediatelyShowSelectionForLayer:(id)arg1;
- (unsigned long long)indexOfLayer:(id)arg1;
- (id)lastLayer;
- (id)layerAtIndex:(unsigned long long)arg1;
- (void)layerTreeLayoutDidChange;
- (id)layerWithID:(id)arg1;
- (id)layersSharingStyle:(id)arg1;
- (void)migratePropertiesFromV54OrEarlierWithCoder:(id)arg1;
- (id)nameForNewPage;
- (void)objectDidInit;
- (id)pagesArray;
- (void)performUndoAction:(CDUnknownBlockType)arg1;
- (void)purgeUnusedImages;
- (void)removePage:(id)arg1;
- (id)rootLayersForShareadObjectContainer:(id)arg1 includingSymbols:(BOOL)arg2;
@property(retain, nonatomic) NSString *savedBy; // @synthesize savedBy=_savedBy;
@property(retain, nonatomic) NSString *savedVariant; // @synthesize savedVariant=_savedVariant;
@property(nonatomic) long long savedVersion; // @synthesize savedVersion=_savedVersion;
- (id)selectedLayers;
- (void)setCurrentPageIndex:(unsigned long long)arg1;
- (void)setEnableLayerInteraction:(BOOL)arg1;
- (void)setEnableSliceInteraction:(BOOL)arg1;
@property(nonatomic) __weak NSUndoManager *undoManager; // @synthesize undoManager=_undoManager;
- (id)sharedObjectContainerOfType:(unsigned long long)arg1;
- (void)sharedObjectDidChange:(struct MSModelObject *)arg1;
- (id)standardNameForLayer:(id)arg1;
- (BOOL)syncSharedObjects:(id)arg1;
- (void)temporarilyHideSelectionForLayer:(id)arg1;
- (void)trackColors:(id)arg1;
- (id)usedFontNames;
- (BOOL)wasSavedByOldVersion;
- (BOOL)wasSavedByTestVersion;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

