//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class MSExportRenderer;

@interface MSExportRendererView : NSView
{
    MSExportRenderer *_renderer;
}

+ (id)exportViewWithRenderer:(id)arg1;

- (void)drawRect:(struct CGRect)arg1;
- (BOOL)isFlipped;
@property(nonatomic) __weak MSExportRenderer *renderer; // @synthesize renderer=_renderer;

@end

