//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface MSFontList : NSObject
{
    unsigned long long _cachingIndex;
    NSArray *_commonFonts;
    NSArray *_systemFonts;
    NSArray *_allFonts;
    NSArray *_filterFonts;
}

+ (void)initialize;

@property(retain, nonatomic) NSArray *allFonts; // @synthesize allFonts=_allFonts;
- (void)clearFilter;
@property(retain, nonatomic) NSArray *commonFonts; // @synthesize commonFonts=_commonFonts;
- (void)dispatchStartCachingFonts;
- (void)filter:(id)arg1;
@property(retain, nonatomic) NSArray *filterFonts; // @synthesize filterFonts=_filterFonts;
- (void)findCommonFontsInDocument:(id)arg1;
- (void)findSystemFonts;
- (id)fontForFontAtIndex:(unsigned long long)arg1;
- (id)nameOfFontAtIndex:(unsigned long long)arg1;
- (unsigned long long)numberOfFonts;
- (void)prepareForDealloc;
- (void)prepareList:(id)arg1;
@property(retain, nonatomic) NSArray *systemFonts; // @synthesize systemFonts=_systemFonts;
- (void)startCachingFonts;
- (void)stopCachingFonts;

@end

