//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSImmutableLayer.h"

@class NSAffineTransform;

@interface MSImmutableLayer : _MSImmutableLayer
{
    NSAffineTransform *_transform;
    struct CGRect _drawableFrame;
}


@property(nonatomic) struct CGRect drawableFrame; // @synthesize drawableFrame=_drawableFrame;
- (id)initWithMutableModelObject:(id)arg1;
@property(retain, nonatomic) NSAffineTransform *transform; // @synthesize transform=_transform;

@end

