//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSTransformEventHandler.h"

@interface MSImageTransformEventHandler : MSTransformEventHandler
{
    struct CGImage *_originalImage;
}

- (struct CGRect)bounds;
- (void)dealloc;
- (void)handlerGotFocus;
- (void)handlerWillLoseFocus;
- (id)instructions;
- (struct CGPoint)layerPointForCorner:(long long)arg1;
- (struct CGRect)newLayerRect;
- (id)perspectiveImage;
- (struct CGPoint)pointForCorner:(long long)arg1 rect:(struct CGRect)arg2;
- (id)toolbarIdentifier;
- (void)transformShape;

@end

