//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSInsertSharedObjectAction.h"

#import "NSMenuDelegate.h"

@class NSString;

@interface MSInsertSharedStyleAction : MSInsertSharedObjectAction <NSMenuDelegate>
{
}

- (id)imageName;
- (void)insertSharedObjectInstance:(id)arg1;
- (id)label;
- (id)menuItemForMenu:(id)arg1 name:(id)arg2 sharedObject:(id)arg3;
- (id)sharedObjectName;
- (void)showSharedObjectsSheet:(id)arg1;
- (id)unsortedSharedObjects;
- (BOOL)validateMenuItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

