//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSGridSheetBase.h"

@class NSButton;

@interface MSLayoutSheet : MSGridSheetBase
{
    NSButton *_centerGridButton;
}


- (void)applyObject:(id)arg1 toLayer:(id)arg2;
- (void)awakeFromNib;
- (id)cacheObjectForRootLayer:(id)arg1;
- (void)centerGrid:(id)arg1;
@property(retain, nonatomic) NSButton *centerGridButton; // @synthesize centerGridButton=_centerGridButton;
- (id)defaultObject;
- (void)offsetChanged:(id)arg1;
- (void)setAsDefault:(id)arg1;

@end

