//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CHViewController.h"

#import "MSSectionProtocol.h"
#import "NSMenuDelegate.h"

@class MSElementsInspectorSection, NSArray, NSButton, NSNumberFormatter, NSString, NSTextField, NSView;

@interface MSLayerInspectorViewController : CHViewController <MSSectionProtocol, NSMenuDelegate>
{
    BOOL _shouldShowPositions;
    BOOL _shouldShowSharedStyles;
    BOOL _shouldShowLayerSpecificProperties;
    BOOL _shouldShowBlendingProperties;
    NSArray *_layers;
    NSView *_positionView;
    NSView *_lineView;
    NSView *_artboardView;
    NSTextField *_xTextField;
    NSTextField *_yTextField;
    NSTextField *_artboardXField;
    NSTextField *_artboardYField;
    NSTextField *_widthTextField;
    NSTextField *_heightTextField;
    NSTextField *_artboardWidthField;
    NSTextField *_artboardHeightField;
    NSButton *_lockProportionsButton;
    MSElementsInspectorSection *_sharedStyleController;
    NSNumberFormatter *_numberFormatter;
}


- (double)absoluteXForLayers;
- (double)absoluteYForLayers;
- (long long)anchorFromString:(id)arg1 axis:(unsigned long long)arg2;
@property(nonatomic) __weak NSTextField *artboardHeightField; // @synthesize artboardHeightField=_artboardHeightField;
@property(retain, nonatomic) NSView *artboardView; // @synthesize artboardView=_artboardView;
@property(nonatomic) __weak NSTextField *artboardWidthField; // @synthesize artboardWidthField=_artboardWidthField;
@property(nonatomic) __weak NSTextField *artboardXField; // @synthesize artboardXField=_artboardXField;
@property(nonatomic) __weak NSTextField *artboardYField; // @synthesize artboardYField=_artboardYField;
- (void)beginRenameSharedObject:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (struct CGRect)boundsForParentOf:(id)arg1;
- (BOOL)canHandleColorMagnifierAction;
- (void)changeTextLayerFont:(id)arg1;
- (void)clearPositionAndSizeFields;
- (void)colorMagnifierAction:(id)arg1;
- (id)document;
- (BOOL)hasLineShapeLayer;
@property(nonatomic) __weak NSTextField *heightTextField; // @synthesize heightTextField=_heightTextField;
- (id)init;
- (id)inspectorsWithProperContent;
- (BOOL)layerIsArtboardOrSlice;
- (BOOL)layerIsGroup;
- (id)layerOrContentsOfLayer:(id)arg1 ifKindOfClass:(Class)arg2;
- (void)layerPositionPossiblyChanged;
- (double)layerSizeOnAxis:(unsigned long long)arg1;
@property(copy, nonatomic) NSArray *layers; // @synthesize layers=_layers;
@property(retain, nonatomic) NSView *lineView; // @synthesize lineView=_lineView;
@property(nonatomic) __weak NSButton *lockProportionsButton; // @synthesize lockProportionsButton=_lockProportionsButton;
@property(retain, nonatomic) NSNumberFormatter *numberFormatter; // @synthesize numberFormatter=_numberFormatter;
@property(retain, nonatomic) NSView *positionView; // @synthesize positionView=_positionView;
- (void)refreshAction:(id)arg1;
- (void)refreshBindingsOnShape:(id)arg1;
- (double)rulerOriginXForLayer:(id)arg1;
- (double)rulerOriginYForLayer:(id)arg1;
- (void)setHeightAction:(id)arg1;
- (void)setLayerSizeFromString:(id)arg1 onAxis:(unsigned long long)arg2;
@property(retain, nonatomic) MSElementsInspectorSection *sharedStyleController; // @synthesize sharedStyleController=_sharedStyleController;
@property(nonatomic) BOOL shouldShowBlendingProperties; // @synthesize shouldShowBlendingProperties=_shouldShowBlendingProperties;
@property(nonatomic) BOOL shouldShowLayerSpecificProperties; // @synthesize shouldShowLayerSpecificProperties=_shouldShowLayerSpecificProperties;
@property(nonatomic) BOOL shouldShowPositions; // @synthesize shouldShowPositions=_shouldShowPositions;
@property(nonatomic) BOOL shouldShowSharedStyles; // @synthesize shouldShowSharedStyles=_shouldShowSharedStyles;
- (void)setValue:(double)arg1 forFields:(id)arg2;
- (void)setWidthAction:(id)arg1;
@property(nonatomic) __weak NSTextField *widthTextField; // @synthesize widthTextField=_widthTextField;
- (void)setXAction:(id)arg1;
@property(nonatomic) __weak NSTextField *xTextField; // @synthesize xTextField=_xTextField;
- (void)setYAction:(id)arg1;
@property(nonatomic) __weak NSTextField *yTextField; // @synthesize yTextField=_yTextField;
- (id)sharedObjectsSection;
- (id)valueForUndefinedKey:(id)arg1;
- (id)views;
- (BOOL)wantsSeparatorBetweenView:(id)arg1 andView:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

