//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class NSSet;

@interface MSMasterLayer : CALayer
{
    double _originalZoomLevel;
    NSSet *_tilesToObserve;
    unsigned long long _finishedTileCount;
}

+ (id)masterLayerAtZoomLevel:(double)arg1;

- (void)clear;
@property(readonly, nonatomic) double currentZoomLevel;
- (void)dealloc;
@property(nonatomic) unsigned long long finishedTileCount; // @synthesize finishedTileCount=_finishedTileCount;
@property(readonly, nonatomic) BOOL hasZoomed;
- (double)layerZoom;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(nonatomic) double originalZoomLevel; // @synthesize originalZoomLevel=_originalZoomLevel;
- (void)removeWhenNewTilesAreFinished:(id)arg1;
@property(retain, nonatomic) NSSet *tilesToObserve; // @synthesize tilesToObserve=_tilesToObserve;
- (void)stopRemovalObserving;
- (void)zoomBy:(double)arg1;

@end

