//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CHViewController.h"

#import "MSReorderingContainerDelegate.h"

@class MSReorderingContainerView, NSArray, NSButton, NSString, NSTextField, NSView;

@interface MSMultipleStylePartInspectorViewController : CHViewController <MSReorderingContainerDelegate>
{
    NSArray *_layers;
    NSArray *_stylePartViewControllers;
    id <MSStylePartInspectorDelegate> _delegate;
    MSReorderingContainerView *_reorderingContainer;
    NSTextField *_nameField;
    NSTextField *_nameFieldShadow;
    NSView *_nameView;
    NSButton *_removeDisabledStylesButton;
    NSButton *_showAdvancedOptionsButton;
}


- (void)addStylePartAction:(id)arg1;
- (id)addStylePartsForSelection;
- (void)awakeFromNib;
- (void)containerBackground:(id)arg1 dragDidReorderChildAtIndex:(unsigned long long)arg2 toIndex:(unsigned long long)arg3;
- (void)dealloc;
@property(nonatomic) __weak id <MSStylePartInspectorDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteStylePartAction:(id)arg1;
- (void)deleteUnusedStylePartsAction:(id)arg1;
- (void)duplicateStylePartAction:(id)arg1;
- (BOOL)hasEnabledStyle;
- (BOOL)hasPopOver;
- (id)initWithDelegate:(id)arg1;
- (id)inspectorForStyleParts:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)lastEnabledStylePartController;
@property(copy, nonatomic) NSArray *layers; // @synthesize layers=_layers;
- (void)loadViewControllers;
@property(retain, nonatomic) NSTextField *nameField; // @synthesize nameField=_nameField;
@property(retain, nonatomic) NSTextField *nameFieldShadow; // @synthesize nameFieldShadow=_nameFieldShadow;
@property(retain, nonatomic) NSView *nameView; // @synthesize nameView=_nameView;
- (id)nibName;
- (void)prepare;
- (void)prepareForReuse;
- (void)prepareInspector:(id)arg1 parts:(id)arg2 index:(unsigned long long)arg3;
- (void)prepareParentForDisplay;
@property(retain, nonatomic) NSButton *removeDisabledStylesButton; // @synthesize removeDisabledStylesButton=_removeDisabledStylesButton;
@property(retain, nonatomic) MSReorderingContainerView *reorderingContainer; // @synthesize reorderingContainer=_reorderingContainer;
- (void)resizeViewToFit;
- (id)rotatedStyleParts;
@property(retain, nonatomic) NSButton *showAdvancedOptionsButton; // @synthesize showAdvancedOptionsButton=_showAdvancedOptionsButton;
@property(retain, nonatomic) NSArray *stylePartViewControllers; // @synthesize stylePartViewControllers=_stylePartViewControllers;
- (BOOL)shouldShowAdvancedOptionsButton;
- (double)startingOffsetForStackingContainerBackground:(id)arg1;
- (void)styleDidEnableOrDisable;
- (unsigned long long)stylePartType;
- (unsigned long long)tagFromSender:(id)arg1;
- (void)validateAdvancedOptionsButton;
- (void)validateRemoveDisabledStylesButton;
- (void)validateSpecialButtons;
- (id)viewForStyleAtOffset:(long long)arg1 index:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

