//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MSNoise : NSObject
{
}

+ (void)drawWithIntensity:(double)arg1 ofType:(long long)arg2 inPath:(id)arg3 zoomValue:(double)arg4;
+ (void)drawWithIntensity:(double)arg1 ofType:(long long)arg2 inRect:(struct CGRect)arg3 zoomValue:(double)arg4;

@end

