//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSPage.h"

#import "MSRootLayer.h"

@class MSArtboardGroup, MSLayoutGrid, MSRulerData, MSSimpleGrid, NSArray, NSString;

@interface MSPage : _MSPage <MSRootLayer>
{
    long long ignoreLayerSelectionDidChangeNotificationsCounter;
    BOOL _hasBlendedLayer;
    BOOL _shouldSkipCalculatingLayerBlending;
    BOOL _skipCalculatingBlending;
    id <MSPageDelegate> _pageDelegate;
    MSArtboardGroup *_currentArtboard;
    NSArray *_cachedArtboards;
    NSArray *_cachedExportableLayers;
}

+ (id)page;
+ (unsigned long long)traits;

- (void)addOrRemoveLayerFromArtboardIfNecessary:(id)arg1;
- (id)allAncestorsOfLayers:(id)arg1;
- (id)ancestorTransforms;
- (id)ancestors;
- (id)ancestorsOfLayer:(id)arg1;
- (id)ancestorsOfLayer:(id)arg1 inContainer:(id)arg2;
- (void)appendBaseTranslation:(id)arg1 exporter:(id)arg2;
- (id)artboardForSlice:(id)arg1 inArtboards:(id)arg2;
@property(readonly, nonatomic) __weak NSArray *artboards;
- (id)badgeMap;
@property(retain, nonatomic) NSArray *cachedArtboards; // @synthesize cachedArtboards=_cachedArtboards;
@property(retain, nonatomic) NSArray *cachedExportableLayers; // @synthesize cachedExportableLayers=_cachedExportableLayers;
- (BOOL)canBeContainedByDocument;
- (BOOL)canBeHovered;
- (BOOL)canContainLayer:(id)arg1;
- (BOOL)canCopyToLayer:(id)arg1 beforeLayer:(id)arg2;
- (void)changeLayerExpandedTypeToAutomaticIfCollapsed;
- (void)childDidChangeNotification:(id)arg1;
- (id)cloneForDocument:(id)arg1;
@property(readonly, nonatomic) struct CGRect contentBounds;
@property(nonatomic) __weak MSArtboardGroup *currentArtboard; // @synthesize currentArtboard=_currentArtboard;
- (id)currentGrid;
- (id)currentHorizontalRulerData;
- (id)currentLayout;
- (id)currentRoot;
- (id)currentVerticalRulerData;
- (void)dataArray:(id)arg1 didAddObject:(id)arg2;
- (void)dataArray:(id)arg1 willRemoveObject:(id)arg2;
- (void)dealloc;
- (void)decodePropertiesWithCoder:(id)arg1;
- (id)defaultName;
- (double)defaultZoomValue;
- (id)destinationArtboardForLayers:(id)arg1 artboards:(id)arg2;
- (id)displayName;
- (unsigned long long)displayType;
- (void)duplicate:(id)arg1;
- (id)exportableLayers;
@property(nonatomic) BOOL hasBlendedLayer; // @synthesize hasBlendedLayer=_hasBlendedLayer;
- (BOOL)hasClickThrough;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)invalidateLightweightCopy:(id)arg1;
- (BOOL)isExportableViaDragAndDrop;
- (struct CGPoint)layerOffsetWithExporter:(id)arg1;
- (void)layerSelectionDidChange;
- (BOOL)layers:(id)arg1 fitOnArtboard:(id)arg2;
- (void)moveLayersToArtboards;
- (void)objectDidInit;
@property(nonatomic) __weak id <MSPageDelegate> pageDelegate; // @synthesize pageDelegate=_pageDelegate;
- (id)parentGroup;
- (BOOL)parentOrSelfIsSymbol;
- (id)parentPage;
- (id)parentRoot;
- (void)prepareObjectCopy:(id)arg1;
- (id)previewImages;
- (void)rectSizeDidChange:(id)arg1;
- (void)refreshOfType:(unsigned long long)arg1 rect:(struct CGRect)arg2;
- (void)refreshViewsWithMask:(unsigned long long)arg1;
- (Class)rendererClass;
- (BOOL)resizeRoot:(BOOL)arg1;
@property(nonatomic) struct CGPoint rulerBase;
- (void)scheduleCalculateHasBlendedLayer;
- (id)selectedLayers;
- (void)setCurrentGrid:(id)arg1;
- (void)setCurrentLayout:(id)arg1;
- (void)setName:(id)arg1;
- (void)setScrollOrigin:(struct CGPoint)arg1;
@property(nonatomic) BOOL shouldSkipCalculatingLayerBlending; // @synthesize shouldSkipCalculatingLayerBlending=_shouldSkipCalculatingLayerBlending;
@property(nonatomic) BOOL skipCalculatingBlending; // @synthesize skipCalculatingBlending=_skipCalculatingBlending;
- (void)setZoomValue:(double)arg1;
- (unsigned long long)shouldDraw;
- (BOOL)shouldDrawSelection;
- (BOOL)shouldIncludeLayerInSlice:(id)arg1;
- (BOOL)shouldRenderInTransparencyLayer;
- (id)symbolLayersInGroup:(id)arg1;
- (id)transform;
- (BOOL)transparencyLayerUseRectCondition;
- (void)tryToMoveLayer:(id)arg1 toArtboards:(id)arg2;
- (void)tryToMoveLayerToArtboard:(id)arg1;
- (id)webExporterRepresentationOnPage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;

@end

