//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSRectangleShape.h"

@class NSString;

@interface MSRectangleShape : _MSRectangleShape
{
}

+ (double)lastUsedFixedRadius;
- (id)addContentToElement:(id)arg1 attributes:(id)arg2 exporter:(id)arg3 action:(unsigned long long *)arg4;
- (id)bezierPathForCursorPreview;
@property(nonatomic) double cornerRadiusFloat;
@property(copy, nonatomic) NSString *cornerRadiusString;
- (id)defaultName;
- (void)didChangeValues;
- (double)floatFromNumbers:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)multiplyBy:(double)arg1;
@property(nonatomic) double normalizedExponentialCornerRadius;
- (id)rectangleNumberFormatter;
- (void)removePathsAndReset;
- (void)resetPathsToRect;
- (void)resetPathsToRoundedRect;
- (void)resetPoints;
- (void)resetPointsBasedOnUserInteraction;
- (void)resetPointsIfNecessary;
- (void)setCornerRadiusFromComponents:(id)arg1;
- (void)setCornerRadiusFromSimpleString:(id)arg1;
- (BOOL)shouldDrawLayerSelection;
- (void)willChangeValues;

@end

