//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSRect.h"

@interface MSRect : _MSRect
{
    double proportions;
    BOOL temporarilyConstrainProportions;
    long long proportionsTempDisabled;
    double _right;
    double _bottom;
}

+ (id)rectWithRect:(struct CGRect)arg1;
+ (id)rectWithUnionOfRects:(id)arg1;
+ (id)rectWithX:(double)arg1 y:(double)arg2 width:(double)arg3 height:(double)arg4;
+ (void)shouldNotifyRulerObservers:(BOOL)arg1;
- (void)addHeight:(double)arg1;
- (void)addWidth:(double)arg1;
- (void)addX:(double)arg1;
- (void)addY:(double)arg1;
@property(nonatomic) double bottom; // @synthesize bottom=_bottom;
- (void)calculateProportions;
- (BOOL)containsPoint:(struct CGPoint)arg1;
- (void)decodePropertiesWithCoder:(id)arg1;
- (id)delegate;
- (id)description;
- (void)disableProportionsTemporarily:(BOOL)arg1;
- (id)initWithRect:(struct CGRect)arg1;
- (id)initWithX:(double)arg1 y:(double)arg2 width:(double)arg3 height:(double)arg4;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isIntegral;
@property(nonatomic) double left;
- (void)log;
- (void)makeOriginIntegral;
- (void)makeRectIntegral;
@property(nonatomic) double maxX;
@property(nonatomic) double maxY;
@property(nonatomic) struct CGPoint mid;
@property(nonatomic) double midX;
@property(nonatomic) double midY;
@property(nonatomic) double minX;
@property(nonatomic) double minY;
- (void)objectDidInit;
@property(nonatomic) struct CGPoint origin;
- (double)proportions;
@property(nonatomic) struct CGRect rect;
@property(nonatomic) double right; // @synthesize right=_right;
- (id)scaleBy:(double)arg1;
- (void)setConstrainProportions:(BOOL)arg1;
- (void)setHeight:(double)arg1;
- (void)setNilValueForKey:(id)arg1;
- (void)setProportions:(double)arg1;
- (void)setRectByIgnoringProportions:(struct CGRect)arg1;
@property(nonatomic) struct CGSize size;
- (void)setTemporarilyConstrainProportions:(BOOL)arg1;
@property(nonatomic) double top;
- (void)setWidth:(double)arg1;
- (void)setX:(double)arg1;
- (void)setY:(double)arg1;
- (BOOL)shouldConstrainProportions;
- (void)subtractHeight:(double)arg1;
- (void)subtractWidth:(double)arg1;
- (void)subtractX:(double)arg1;
- (void)subtractY:(double)arg1;

@end

