//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSRulerData.h"

@interface MSRulerData : _MSRulerData
{
}

- (void)addGuide;
- (void)addGuide:(id)arg1;
- (void)addGuideWithValue:(double)arg1;
- (double)guideAtIndex:(unsigned long long)arg1;
- (unsigned long long)numberOfGuides;
- (void)removeGuide:(id)arg1;
- (void)removeGuideAtIndex:(unsigned long long)arg1;
- (void)replaceGuideAtIndex:(unsigned long long)arg1 withGuide:(id)arg2;
- (void)setValue:(double)arg1 forGuideAtIndex:(unsigned long long)arg2;

@end

