//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface MSSharedObjectInstanceCollection : NSObject
{
    NSMutableDictionary *_dictionary;
}

+ (id)collectionWithInstances:(id)arg1;

- (void)addInstance:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *dictionary; // @synthesize dictionary=_dictionary;
- (id)init;
- (id)instancesOfType:(unsigned long long)arg1;
- (void)removeAllInstances;

@end

