//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSLayerSection.h"

#import "NSSharingServiceDelegate.h"
#import "NSSharingServicePickerDelegate.h"
#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"
#import "NSTextFieldDelegate.h"

@class MSSliceDragView, NSButton, NSMatrix, NSMutableArray, NSString, NSTableView;

@interface MSSliceLayerSection : MSLayerSection <NSTableViewDelegate, NSTableViewDataSource, NSTextFieldDelegate, NSSharingServicePickerDelegate, NSSharingServiceDelegate>
{
    NSMatrix *_includeOptions;
    NSTableView *_tableView;
    NSButton *_exportSingleSliceButton;
    NSButton *_trimCheckbox;
    NSButton *_shareButton;
    MSSliceDragView *_sliceDragView;
    NSMutableArray *_possiblyIncludedLayers;
}


- (void)awakeFromNib;
- (void)calculatePossiblyIncludedLayers:(id)arg1;
- (id)currentView;
- (void)dealloc;
@property(retain, nonatomic) NSButton *exportSingleSliceButton; // @synthesize exportSingleSliceButton=_exportSingleSliceButton;
- (id)firstSlice;
- (id)imagesFromSlice:(id)arg1;
@property(retain, nonatomic) NSMatrix *includeOptions; // @synthesize includeOptions=_includeOptions;
- (id)includedLayersForSlice:(id)arg1;
- (id)init;
- (id)layerAtIndex:(long long)arg1;
- (long long)numberOfRowsInTableView:(id)arg1;
@property(retain, nonatomic) NSMutableArray *possiblyIncludedLayers; // @synthesize possiblyIncludedLayers=_possiblyIncludedLayers;
- (id)prefixForLayer:(id)arg1;
- (void)prepareShareButton;
@property(retain, nonatomic) NSButton *shareButton; // @synthesize shareButton=_shareButton;
@property(retain, nonatomic) MSSliceDragView *sliceDragView; // @synthesize sliceDragView=_sliceDragView;
@property(retain, nonatomic) NSTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSButton *trimCheckbox; // @synthesize trimCheckbox=_trimCheckbox;
- (void)shareAction:(id)arg1;
- (struct CGRect)sharingService:(id)arg1 sourceFrameOnScreenForShareItem:(id)arg2;
- (id)sharingService:(id)arg1 sourceWindowForShareItems:(id)arg2 sharingContentScope:(long long *)arg3;
- (id)sharingService:(id)arg1 transitionImageForShareItem:(id)arg2 contentRect:(struct CGRect *)arg3;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)trimBoxChecked:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

