//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSView;

@interface MSSliceExportOptions : NSViewController
{
    NSView *_optionsViewJPG;
    NSView *_optionsViewSaveForWeb;
}

+ (id)exportOptions;

@property(retain, nonatomic) NSView *optionsViewJPG; // @synthesize optionsViewJPG=_optionsViewJPG;
@property(retain, nonatomic) NSView *optionsViewSaveForWeb; // @synthesize optionsViewSaveForWeb=_optionsViewSaveForWeb;
- (void)setExtensions:(id)arg1;

@end

