//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSStylePart.h"

@interface MSStylePart : _MSStylePart <NSCoding, NSCopying>
{
}

- (id)blendingViewForColorInspector:(id)arg1;
- (void)multiplyBy:(double)arg1;
- (id)parentLayer;
- (id)parentStyle;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)topViewForColorInspector:(id)arg1;
- (id)valueForUndefinedKey:(id)arg1;

@end

