//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface MSTileThreadPool : NSObject
{
    long long nextThreadIndex;
    NSMutableArray *_threads;
}

+ (id)sharedController;
+ (id)thread;

- (id)init;
@property(retain, nonatomic) NSMutableArray *threads; // @synthesize threads=_threads;
- (id)thread;
- (void)threadMain;

@end

