//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSBaseAction.h"

@class NSWindow;

@interface MSTogglePresentationModeAction : MSBaseAction
{
    NSWindow *_fullScreenWindow;
}


- (void)dealloc;
- (void)enterFullScreen;
- (void)exitFullScreen;
- (id)fullScreenOptions;
- (id)fullScreenView;
@property(retain, nonatomic) NSWindow *fullScreenWindow; // @synthesize fullScreenWindow=_fullScreenWindow;
- (void)fullScreenWindowDidResignMain:(id)arg1;
- (struct CGRect)rectOfCanvasOnScreen;
- (void)removeObserver;
- (void)togglePresentationMode:(id)arg1;

@end

