//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSBaseAction.h"

@interface MSVectorizeTextAction : MSBaseAction
{
}

- (void)copyStylePropertiesFromLayer:(id)arg1 toShape:(id)arg2;
- (void)copyTextPropertiesFromLayer:(id)arg1 toShape:(id)arg2;
- (void)doPerformAction:(id)arg1;
- (id)imageName;
- (id)label;
- (id)rawCopyOfStyle:(id)arg1;
- (void)refreshAndRemoveOldLayer:(id)arg1;
- (BOOL)validate;
- (void)vectorizeLayer:(id)arg1;

@end

