//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSBaseAction.h"

@interface MSZoomAction : MSBaseAction
{
}

- (id)toolbarItemWithSize:(unsigned long long)arg1;
- (void)zoomModeToggle:(id)arg1;
- (void)zoomValueDidChange;
- (id)zoomValueString;
- (id)zoomViewAtSize:(unsigned long long)arg1;

@end

