//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBezierPath.h"

@interface NSBezierPath (NSBezierPath_Various)
+ (id)bezierCurveFromPoint:(struct CGPoint)arg1 toPoint:(struct CGPoint)arg2 controlPoint1:(struct CGPoint)arg3 controlPoint2:(struct CGPoint)arg4;
+ (id)bezierPathFromPoint:(struct CGPoint)arg1 toPoint:(struct CGPoint)arg2;
+ (id)bezierPathWithSubPaths:(id)arg1;
- (id)bezierPathWithLineWidth:(double)arg1;
- (id)bezierPathWithSquareLineCapStyle;
- (BOOL)containsRect:(struct CGRect)arg1;
- (void)debugWriteToFileNamed:(id)arg1;
- (void)fillEvenOdd;
- (void)fillNonZero;
- (id)insetPathBy:(double)arg1;
- (id)outerPathWithRect:(struct CGRect)arg1;
- (id)outlinePathWithWidth:(double)arg1;
- (id)scaleBy:(double)arg1;
- (void)setDashPattern:(id)arg1;
- (id)simplify;
- (id)simplifyWithMargin:(long long)arg1;
- (void)strokeWithWidth:(double)arg1;
- (id)subPaths;
@end

