//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBezierPath.h"

@interface NSBezierPath (NSBezierPath_Enumerator)
- (void)appendBezierPathItem:(id)arg1;
- (id)bezierCurves;
- (BOOL)customIsEqual:(id)arg1;
- (id)enumerator;
- (id)itemAtIndex:(long long)arg1;
- (id)lastItem;
- (id)reverseEnumerator;
@end

