//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBezierPath.h"

@interface NSBezierPath (Boolean)
- (id)fb_difference:(id)arg1;
- (id)fb_intersect:(id)arg1;
- (id)fb_union:(id)arg1;
- (id)fb_xor:(id)arg1;
@end

