//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableArray.h"

@interface NSMutableArray (SVGNodeAdditions)
+ (id)illegalIdentifierChars;
- (void)addAttributeForID:(id)arg1;
- (void)addAttributeWithName:(id)arg1 numberValue:(double)arg2;
- (void)addAttributeWithName:(id)arg1 percentageFractionalValue:(double)arg2;
- (void)addAttributeWithName:(id)arg1 percentageValue:(double)arg2;
- (void)addAttributeWithName:(id)arg1 pixelValue:(double)arg2;
- (void)addAttributeWithName:(id)arg1 stringValue:(id)arg2;
- (unsigned long long)indexOfAttributeWithName:(id)arg1;
@end

