//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTrackingArea.h"

@interface NSTrackingArea (CHTrackingAreaExtensions)
+ (unsigned long long)defaultOptions;
+ (id)mouseEnterExitTrackingArea:(id)arg1;
+ (id)trackingAreaWithOptions:(unsigned long long)arg1 owner:(id)arg2;
@end

