//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSXMLDocument.h"

@interface NSXMLDocument (SVGDocument)
+ (id)SVGDocumentWithBezierPath:(id)arg1;
- (id)bezierPathElement:(id)arg1;
- (id)createSVGForBezierPath:(id)arg1;
- (id)data;
- (id)description;
@end

