//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, PDFFunction;

@interface PDFPattern : NSObject
{
    unsigned long long _shadingType;
    PDFFunction *_function;
    id _space;
    NSArray *_coords;
}

+ (id)patternWithResource:(id)arg1;

@property(retain, nonatomic) NSArray *coords; // @synthesize coords=_coords;
@property(retain, nonatomic) PDFFunction *function; // @synthesize function=_function;
- (id)initWithResource:(id)arg1;
@property(nonatomic) unsigned long long shadingType; // @synthesize shadingType=_shadingType;
@property(retain, nonatomic) id space; // @synthesize space=_space;
- (void)setupFromDictionary:(id)arg1;
- (void)setupFromStream:(id)arg1;

@end

