//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PDFString : NSObject
{
    struct CGPDFString *_ref;
}

- (id)data;
- (id)initWithStringRef:(struct CGPDFString *)arg1;
@property(nonatomic) struct CGPDFString *ref; // @synthesize ref=_ref;
- (id)string;
- (id)stringWithMap:(id)arg1;

@end

